// Strings for the "सरकारी योजनाएं" module (prefix "schemes."). Scheme content itself
// (names, benefits, steps…) is verified official text in data/schemes.ts and is not
// translated here; only the screen chrome and the category labels are.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';
import { SCHEME_CATEGORIES } from '../../data/schemes';

// Category chip / badge labels come from the catalog so they never drift from it.
const categoryHi = Object.fromEntries(SCHEME_CATEGORIES.map(c => [`schemes.cat.${c.id}`, c.labelHi]));
const categoryEn = Object.fromEntries(SCHEME_CATEGORIES.map(c => [`schemes.cat.${c.id}`, c.labelEn]));

registerStrings({
  hi: {
    ...categoryHi,
    // List screen
    'schemes.title': 'सरकारी योजनाएं',
    'schemes.subtitle': 'किसानों के लिए भारत सरकार की योजनाएं',
    'schemes.filter': 'योजना का प्रकार',
    'schemes.all': 'सभी',
    'schemes.search.label': 'योजना खोजें',
    'schemes.search.placeholder': 'खोजें — जैसे बीमा, पेंशन, ट्रैक्टर',
    'schemes.featured': 'सबसे ज़्यादा उपयोगी',
    'schemes.featured.sub': 'ज़्यादातर किसानों के काम की योजनाएं',
    'schemes.more': 'और योजनाएं',
    'schemes.inCategory': '{n} योजनाएं',
    'schemes.inCategory.one': '1 योजना',
    'schemes.results': '{n} योजनाएं मिलीं',
    'schemes.results.one': '1 योजना मिली',
    'schemes.row.oldSource': 'पुरानी जानकारी — {date} का दस्तावेज़',
    'schemes.empty.title': 'कोई योजना नहीं मिली',
    'schemes.empty.body': 'दूसरे शब्द से खोजकर देखें, जैसे “बीमा”, “पेंशन” या “ट्रैक्टर”।',
    'schemes.empty.searchAll': 'सभी योजनाओं में खोजें',
    'schemes.empty.clear': 'खोज साफ़ करें',
    'schemes.note.title': 'आवेदन से पहले आधिकारिक वेबसाइट पर ताज़ा जानकारी ज़रूर देखें',
    'schemes.note.body': 'यहां की जानकारी सरकारी आधिकारिक स्रोतों से ली गई है।',
    'schemes.note.checked': 'सूची की जांच: {date} — हर योजना के पेज पर उसकी अपनी तारीख है',

    // Detail screen
    'schemes.detail.title': 'योजना की जानकारी',
    'schemes.detail.ministry': 'मंत्रालय',
    'schemes.detail.about': 'योजना क्या है',
    'schemes.detail.eligibility': 'कौन आवेदन कर सकता है',
    'schemes.detail.benefits': 'लाभ',
    'schemes.detail.keyBenefit': 'मुख्य लाभ',
    'schemes.detail.documents': 'ज़रूरी दस्तावेज़',
    'schemes.detail.documentsHint': 'जो कागज़ आपके पास तैयार है, उस पर निशान लगाएं',
    'schemes.detail.docsReady': '{total} में से {done} तैयार',
    'schemes.detail.docsAllReady': 'सभी पर निशान लग गया',
    'schemes.detail.docsAllNote': 'आवेदन के समय कोई और कागज़ भी मांगा जा सकता है।',
    'schemes.detail.docOptional': 'ज़रूरत हो तो',
    'schemes.detail.docsReset': 'सभी निशान हटाएं',
    'schemes.detail.howToApply': 'आवेदन कैसे करें',
    'schemes.detail.official': 'आधिकारिक जानकारी',
    'schemes.detail.officialSite': 'आधिकारिक वेबसाइट',
    'schemes.detail.openSite': 'आधिकारिक वेबसाइट खोलें',
    'schemes.detail.officialDoc': 'आधिकारिक दस्तावेज़ (PDF)',
    'schemes.detail.openDoc': 'आधिकारिक दस्तावेज़ खोलें',
    'schemes.detail.opensBrowser': '{label}, ब्राउज़र में खुलेगा',
    'schemes.detail.needsInternet': 'वेबसाइट खोलने के लिए इंटरनेट चाहिए',
    'schemes.detail.sources': 'जानकारी के स्रोत',
    'schemes.detail.sourcesHint': 'सरकारी वेबसाइट और दस्तावेज़, जिनसे यह जानकारी ली गई है',
    'schemes.detail.showAllSources': 'सभी {n} स्रोत देखें',
    'schemes.detail.showFewerSources': 'कम दिखाएं',
    'schemes.detail.pdf': 'PDF दस्तावेज़',
    'schemes.detail.webPage': 'वेब पेज',
    'schemes.detail.lastVerified': 'अंतिम जांच: {date}',
    'schemes.detail.sourceDate': 'आधिकारिक दस्तावेज़ की तारीख: {date}',
    'schemes.detail.listChecked': 'ऐप में सूची की जांच: {date}',
    'schemes.detail.oldSource': 'पुराने दस्तावेज़ पर आधारित',
    'schemes.detail.disclaimer':
      'सरकारी योजनाओं के नियम, राशि और तारीखें समय-समय पर बदलती रहती हैं। आधिकारिक वेबसाइट पर दी गई जानकारी ही अंतिम मानी जाएगी।',
    'schemes.detail.disclaimerOld':
      'यह जानकारी {date} के आधिकारिक दस्तावेज़ पर आधारित है। आवेदन से पहले आधिकारिक वेबसाइट, बैंक या कृषि कार्यालय से ताज़ा नियम पक्के कर लें।',
    'schemes.detail.isSaved': 'सेव किया हुआ',
    'schemes.detail.removed': 'सेव से हटा दिया',

    // Share / listen text
    'schemes.share.benefit': 'मुख्य लाभ',
    'schemes.share.official': 'आधिकारिक वेबसाइट',
    'schemes.share.footer': 'किसान मित्र ऐप से। आवेदन से पहले आधिकारिक वेबसाइट पर ताज़ा जानकारी ज़रूर देखें।',
    'schemes.share.copied': 'जानकारी कॉपी हो गई — अब इसे कहीं भी पेस्ट करके भेजें',
    'schemes.speak.step': 'चरण {n}',
    'schemes.speak.decimal': 'दशमलव',
    'schemes.speak.dot': 'डॉट',

    // Who published a source (falls back to the web address)
    'schemes.src.pib': 'PIB (भारत सरकार की प्रेस विज्ञप्ति)',
    'schemes.src.budget': 'केंद्रीय बजट',
    'schemes.src.agriwelfare': 'कृषि एवं किसान कल्याण मंत्रालय',
    'schemes.src.maharashtra': 'महाराष्ट्र कृषि विभाग',
    'schemes.src.hp': 'हिमाचल प्रदेश कृषि विभाग',
    'schemes.src.air': 'आकाशवाणी समाचार',
    'schemes.src.pmkisan': 'PM-KISAN पोर्टल',
    'schemes.src.enam': 'ई-नाम पोर्टल',
    'schemes.src.pdmc': 'PDMC पोर्टल',
    'schemes.src.nmnf': 'राष्ट्रीय प्राकृतिक खेती मिशन पोर्टल',

    // Missing scheme
    'schemes.missing.title': 'यह योजना नहीं मिली',
    'schemes.missing.body': 'हो सकता है यह योजना अब हमारी सूची में न हो। बाकी सरकारी योजनाएं देखें।',
    'schemes.missing.action': 'सभी योजनाएं देखें',
  },
  en: {
    ...categoryEn,
    'schemes.title': 'Government schemes',
    'schemes.subtitle': 'Government of India schemes for farmers',
    'schemes.filter': 'Scheme type',
    'schemes.all': 'All',
    'schemes.search.label': 'Search schemes',
    'schemes.search.placeholder': 'Search — e.g. insurance, pension, tractor',
    'schemes.featured': 'Most useful',
    'schemes.featured.sub': 'Schemes most farmers can use',
    'schemes.more': 'More schemes',
    'schemes.inCategory': '{n} schemes',
    'schemes.inCategory.one': '1 scheme',
    'schemes.results': '{n} schemes found',
    'schemes.results.one': '1 scheme found',
    'schemes.row.oldSource': 'Older info — document dated {date}',
    'schemes.empty.title': 'No scheme found',
    'schemes.empty.body': 'Try another word, such as “insurance”, “pension” or “tractor”.',
    'schemes.empty.searchAll': 'Search all schemes',
    'schemes.empty.clear': 'Clear search',
    'schemes.note.title': 'Before applying, always check the latest details on the official website',
    'schemes.note.body': 'This information is taken from official government sources.',
    'schemes.note.checked': "List reviewed: {date} — each scheme's page shows its own date",

    'schemes.detail.title': 'Scheme details',
    'schemes.detail.ministry': 'Ministry',
    'schemes.detail.about': 'About the scheme',
    'schemes.detail.eligibility': 'Who can apply',
    'schemes.detail.benefits': 'Benefits',
    'schemes.detail.keyBenefit': 'Key benefit',
    'schemes.detail.documents': 'Documents needed',
    'schemes.detail.documentsHint': 'Tick the papers you already have ready',
    'schemes.detail.docsReady': '{done} of {total} ready',
    'schemes.detail.docsAllReady': 'All ticked',
    'schemes.detail.docsAllNote': 'You may still be asked for other papers when you apply.',
    'schemes.detail.docOptional': 'Only if it applies to you',
    'schemes.detail.docsReset': 'Clear all ticks',
    'schemes.detail.howToApply': 'How to apply',
    'schemes.detail.official': 'Official information',
    'schemes.detail.officialSite': 'Official website',
    'schemes.detail.openSite': 'Open official website',
    'schemes.detail.officialDoc': 'Official document (PDF)',
    'schemes.detail.openDoc': 'Open official document',
    'schemes.detail.opensBrowser': '{label}, opens in browser',
    'schemes.detail.needsInternet': 'You need internet to open the website',
    'schemes.detail.sources': 'Sources',
    'schemes.detail.sourcesHint': 'Government websites and documents this information comes from',
    'schemes.detail.showAllSources': 'Show all {n} sources',
    'schemes.detail.showFewerSources': 'Show fewer',
    'schemes.detail.pdf': 'PDF document',
    'schemes.detail.webPage': 'Web page',
    'schemes.detail.lastVerified': 'Last checked: {date}',
    'schemes.detail.sourceDate': 'Official document dated {date}',
    'schemes.detail.listChecked': 'List reviewed in the app: {date}',
    'schemes.detail.oldSource': 'Based on an older document',
    'schemes.detail.disclaimer':
      'Scheme rules, amounts and dates change from time to time. The official website is always the final word.',
    'schemes.detail.disclaimerOld':
      'This is based on an official document dated {date}. Before applying, confirm the current rules on the official website or with your bank or agriculture office.',
    'schemes.detail.isSaved': 'Saved',
    'schemes.detail.removed': 'Removed from saved',

    'schemes.share.benefit': 'Key benefit',
    'schemes.share.official': 'Official website',
    'schemes.share.footer': 'Shared from the Kisan Mitra app. Check the latest details on the official website before applying.',
    'schemes.share.copied': 'Copied — paste it anywhere to send',
    'schemes.speak.step': 'Step {n}',
    'schemes.speak.decimal': 'point',
    'schemes.speak.dot': 'dot',

    'schemes.src.pib': 'PIB (Government of India press release)',
    'schemes.src.budget': 'Union Budget',
    'schemes.src.agriwelfare': 'Ministry of Agriculture & Farmers Welfare',
    'schemes.src.maharashtra': 'Maharashtra Agriculture Department',
    'schemes.src.hp': 'Himachal Pradesh Agriculture Department',
    'schemes.src.air': 'All India Radio News',
    'schemes.src.pmkisan': 'PM-KISAN portal',
    'schemes.src.enam': 'e-NAM portal',
    'schemes.src.pdmc': 'PDMC portal',
    'schemes.src.nmnf': 'Natural Farming Mission portal',

    'schemes.missing.title': 'Scheme not found',
    'schemes.missing.body': 'This scheme may no longer be in our list. See the other government schemes.',
    'schemes.missing.action': 'See all schemes',
  },
});
