// Strings for the sign-in flow (splash, welcome carousel, login, signup). Prefix "auth.".
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'auth.appName': 'किसान मित्र',
    'auth.tagline': 'खेती की हर समस्या का समाधान',
    'auth.splash.tap': 'किसान मित्र खोलें',

    'auth.welcome.title': 'किसान मित्र में आपका स्वागत है',
    'auth.welcome.carousel': 'किसान मित्र क्या-क्या करता है',
    'auth.welcome.slide': 'स्लाइड {n}, कुल {total}',
    'auth.welcome.s1.title': 'AI से खेती की सलाह',
    'auth.welcome.s1.body': 'अपनी भाषा में बोलकर या लिखकर सवाल पूछें और आसान शब्दों में सलाह पाएं।',
    'auth.welcome.s2.title': 'मौसम और मंडी भाव',
    'auth.welcome.s2.body': 'अपने इलाके का मौसम, छिड़काव का सही समय और नज़दीकी मंडियों के भाव एक ही जगह।',
    'auth.welcome.s3.title': 'फोटो से फसल रोग पहचान',
    'auth.welcome.s3.body': 'बीमार पत्ती की फोटो लें और रोग की पहचान व बचाव के सुझाव पाएं।',
    'auth.welcome.start': 'शुरू करें',

    'auth.or': 'या',
    'auth.login.heading': 'लॉगिन करें',
    'auth.login.sub': 'अपना मोबाइल नंबर या ईमेल और नाम लिखें',
    'auth.login.submit': 'लॉगिन करें',
    'auth.login.newUser': 'नया उपयोगकर्ता?',
    'auth.login.signup': 'अभी साइन अप करें',

    'auth.contact.label': 'मोबाइल नंबर या ईमेल',
    'auth.contact.phonePlaceholder': '98765 43210',
    'auth.contact.emailPlaceholder': 'naam@gmail.com',
    'auth.contact.useEmail': 'मोबाइल नहीं, ईमेल लिखना है',
    'auth.contact.usePhone': 'ईमेल नहीं, मोबाइल नंबर लिखना है',
    'auth.contact.error.empty': 'मोबाइल नंबर या ईमेल लिखें',
    'auth.contact.error.phone': '10 अंकों का सही मोबाइल नंबर लिखें (6, 7, 8 या 9 से शुरू होने वाला)',
    'auth.contact.error.email': 'ईमेल सही नहीं लग रहा। जैसे: naam@gmail.com',

    'auth.name.label': 'आपका नाम',
    'auth.name.placeholder': 'जैसे: रामलाल यादव',
    'auth.name.voice': 'नाम बोलकर लिखें',
    'auth.name.error': 'अपना नाम लिखें (कम से कम 2 अक्षर)',

    'auth.signup.title': 'नया खाता बनाएं',
    'auth.signup.subtitle': 'बस थोड़ी-सी जानकारी, फिर शुरू करें',
    'auth.signup.heading': 'आपकी जानकारी',
    'auth.signup.areaHeading': 'आपका इलाका',
    'auth.signup.areaHint': 'नीचे के बटन से अपनी जगह चुनें, तो मौसम और मंडी भाव उसी इलाके के दिखेंगे।',
    'auth.signup.village': 'गांव',
    'auth.signup.villagePlaceholder': 'जैसे: रामपुर',
    'auth.signup.villageVoice': 'गांव का नाम बोलकर लिखें',
    'auth.signup.district': 'ज़िला',
    'auth.signup.districtPlaceholder': 'जैसे: वाराणसी',
    'auth.signup.districtVoice': 'ज़िले का नाम बोलकर लिखें',
    'auth.signup.state': 'राज्य',
    'auth.signup.statePlaceholder': 'राज्य चुनें',
    'auth.signup.pickPlace': 'जगह चुनकर ज़िला-राज्य भरें',
    'auth.signup.pickTitle': 'अपना ज़िला चुनें',
    'auth.signup.submit': 'खाता बनाएं',
    'auth.signup.haveAccount': 'पहले से खाता है?',
    'auth.signup.login': 'लॉगिन करें',

    'auth.privacy.line': 'आपकी जानकारी इसी फ़ोन पर सुरक्षित रहती है',
    'auth.privacy.more': 'कैसे?',
    'auth.privacy.title': 'आपकी जानकारी कहां रहती है?',
    'auth.privacy.p1': 'आपका नाम, मोबाइल नंबर और खेत की जानकारी इसी फ़ोन में सेव होती है।',
    'auth.privacy.p2': 'इसलिए यहां कोई पासवर्ड या OTP नहीं मांगा जाता।',
    'auth.privacy.p3': 'AI से सवाल पूछने पर आपका सवाल और ज़रूरी खेती की जानकारी जवाब पाने के लिए AI सेवा को भेजी जाती है।',
    'auth.privacy.p4': 'ऐप से लॉग आउट करने पर यह सारी जानकारी इस फ़ोन से मिट जाती है।',
    'auth.privacy.ok': 'समझ गया',

    'auth.google.error': 'Google से लॉगिन नहीं हो पाया। दोबारा कोशिश करें या मोबाइल नंबर से लॉगिन करें।',
    'auth.hello': 'नमस्ते, {name} जी!',
  },
  en: {
    'auth.appName': 'Kisan Mitra',
    'auth.tagline': 'A solution for every farming problem',
    'auth.splash.tap': 'Open Kisan Mitra',

    'auth.welcome.title': 'Welcome to Kisan Mitra',
    'auth.welcome.carousel': 'What Kisan Mitra does',
    'auth.welcome.slide': 'Slide {n} of {total}',
    'auth.welcome.s1.title': 'Farming advice from AI',
    'auth.welcome.s1.body': 'Ask by voice or text in your language and get advice in simple words.',
    'auth.welcome.s2.title': 'Weather and mandi prices',
    'auth.welcome.s2.body': 'Your local weather, the right time to spray and nearby mandi prices in one place.',
    'auth.welcome.s3.title': 'Spot crop disease from a photo',
    'auth.welcome.s3.body': 'Take a photo of a sick leaf and get the likely disease and ways to protect your crop.',
    'auth.welcome.start': 'Get started',

    'auth.or': 'or',
    'auth.login.heading': 'Log in',
    'auth.login.sub': 'Enter your mobile number or email and your name',
    'auth.login.submit': 'Log in',
    'auth.login.newUser': 'New user?',
    'auth.login.signup': 'Sign up now',

    'auth.contact.label': 'Mobile number or email',
    'auth.contact.phonePlaceholder': '98765 43210',
    'auth.contact.emailPlaceholder': 'name@gmail.com',
    'auth.contact.useEmail': 'Use email instead',
    'auth.contact.usePhone': 'Use mobile number instead',
    'auth.contact.error.empty': 'Enter your mobile number or email',
    'auth.contact.error.phone': 'Enter a valid 10-digit mobile number (starting with 6, 7, 8 or 9)',
    'auth.contact.error.email': 'This email does not look right. Example: name@gmail.com',

    'auth.name.label': 'Your name',
    'auth.name.placeholder': 'e.g. Ramlal Yadav',
    'auth.name.voice': 'Say your name',
    'auth.name.error': 'Enter your name (at least 2 letters)',

    'auth.signup.title': 'Create account',
    'auth.signup.subtitle': 'Just a few details, then you are ready',
    'auth.signup.heading': 'Your details',
    'auth.signup.areaHeading': 'Your area',
    'auth.signup.areaHint': 'Pick your place with the button below and weather and mandi prices will be shown for that area.',
    'auth.signup.village': 'Village',
    'auth.signup.villagePlaceholder': 'e.g. Rampur',
    'auth.signup.villageVoice': 'Say your village name',
    'auth.signup.district': 'District',
    'auth.signup.districtPlaceholder': 'e.g. Varanasi',
    'auth.signup.districtVoice': 'Say your district',
    'auth.signup.state': 'State',
    'auth.signup.statePlaceholder': 'Choose state',
    'auth.signup.pickPlace': 'Pick a place to fill district and state',
    'auth.signup.pickTitle': 'Choose your district',
    'auth.signup.submit': 'Create account',
    'auth.signup.haveAccount': 'Already have an account?',
    'auth.signup.login': 'Log in',

    'auth.privacy.line': 'Your details stay safe on this phone',
    'auth.privacy.more': 'How?',
    'auth.privacy.title': 'Where are your details kept?',
    'auth.privacy.p1': 'Your name, mobile number and farm details are saved on this phone.',
    'auth.privacy.p2': 'That is why no password or OTP is asked here.',
    'auth.privacy.p3': 'When you ask the AI, your question and the farm details it needs are sent to the AI service to get an answer.',
    'auth.privacy.p4': 'Logging out of the app erases all of this from this phone.',
    'auth.privacy.ok': 'Got it',

    'auth.google.error': 'Could not sign in with Google. Try again or log in with your mobile number.',
    'auth.hello': 'Hello, {name}!',
  },
});
