// Strings for "मेरी सेव की गई जानकारी" (saved items).
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'saved.title': 'मेरी सेव की गई जानकारी',
    'saved.countOne': '1 चीज़ सेव है',
    'saved.countMany': '{n} चीज़ें सेव हैं',
    'saved.filter': 'सेव की गई जानकारी का प्रकार',
    'saved.type.all': 'सभी',
    'saved.type.ai-answer': 'AI जवाब',
    'saved.type.guide': 'खेती गाइड',
    'saved.type.advice': 'फसल सलाह',
    'saved.type.mandi-crop': 'मंडी फसल',
    'saved.type.scheme': 'योजनाएं',
    'saved.type.diagnosis': 'फसल रोग जांच',
    'saved.type.soil-report': 'मिट्टी रिपोर्ट',
    'saved.kind.ai-answer': 'AI जवाब',
    'saved.kind.guide': 'खेती गाइड',
    'saved.kind.advice': 'फसल सलाह',
    'saved.kind.mandi-crop': 'मंडी भाव',
    'saved.kind.scheme': 'योजना',
    'saved.kind.diagnosis': 'फसल जांच',
    'saved.kind.soil-report': 'मिट्टी रिपोर्ट',
    'saved.kind.disease': 'रोग की जानकारी',
    'saved.savedOn': 'सेव किया: {date}',
    'saved.remove': 'सेव से हटाएं: {title}',
    'saved.removed': 'सेव से हटा दिया गया',
    'saved.undo': 'वापस लाएं',
    'saved.empty.title': 'अभी कुछ सेव नहीं किया है',
    'saved.empty.body': "किसी भी जवाब या योजना पर 'सेव' दबाएं। सेव की गई जानकारी यहां मिलेगी — बिना इंटरनेट के भी।",
    'saved.empty.schemes': 'सरकारी योजनाएं देखें',
    'saved.empty.ai': 'AI से सवाल पूछें',
    'saved.emptyType.title': 'इसमें अभी कुछ सेव नहीं है',
    'saved.emptyType.body': "जानकारी खोलकर 'सेव' दबाएं, वह यहां आ जाएगी।",
    'saved.emptyType.action': 'सभी सेव की गई जानकारी देखें',
    'saved.offline': 'इंटरनेट नहीं है, फिर भी आपकी सेव की गई जानकारी खुल जाएगी।',
    'saved.offlineNote': 'सेव की गई जानकारी आपके फ़ोन में रहती है, इसलिए बिना इंटरनेट के भी खुलती है।',
    'saved.notOpenable': 'यह जानकारी अब अलग से नहीं खुल सकती, पर इसका सार यहां सेव है।',
  },
  en: {
    'saved.title': 'My saved items',
    'saved.countOne': '1 item saved',
    'saved.countMany': '{n} items saved',
    'saved.filter': 'Saved item type',
    'saved.type.all': 'All',
    'saved.type.ai-answer': 'AI answers',
    'saved.type.guide': 'Farming guides',
    'saved.type.advice': 'Crop advice',
    'saved.type.mandi-crop': 'Mandi crops',
    'saved.type.scheme': 'Schemes',
    'saved.type.diagnosis': 'Crop checks',
    'saved.type.soil-report': 'Soil reports',
    'saved.kind.ai-answer': 'AI answer',
    'saved.kind.guide': 'Farming guide',
    'saved.kind.advice': 'Crop advice',
    'saved.kind.mandi-crop': 'Mandi price',
    'saved.kind.scheme': 'Scheme',
    'saved.kind.diagnosis': 'Crop check',
    'saved.kind.soil-report': 'Soil report',
    'saved.kind.disease': 'Disease guide',
    'saved.savedOn': 'Saved {date}',
    'saved.remove': 'Remove from saved: {title}',
    'saved.removed': 'Removed from saved',
    'saved.undo': 'Undo',
    'saved.empty.title': 'Nothing saved yet',
    'saved.empty.body': "Tap 'Save' on any answer or scheme. It will appear here — even without internet.",
    'saved.empty.schemes': 'See government schemes',
    'saved.empty.ai': 'Ask the AI',
    'saved.emptyType.title': 'Nothing saved here yet',
    'saved.emptyType.body': "Open something and tap 'Save' to keep it here.",
    'saved.emptyType.action': 'See all saved items',
    'saved.offline': 'No internet, but your saved items still open.',
    'saved.offlineNote': 'Saved items stay on your phone, so they open without internet.',
    'saved.notOpenable': 'This item can no longer be opened on its own, but its summary is saved here.',
  },
});
