// Strings for the calculators module (CalculatorsScreen, CalculatorScreen and its kinds).
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';
// Expense category names (hisab.cat.*) are shared with the cost calculator.
import '../hisab/strings';

registerStrings({
  hi: {
    'calc.title': 'खेती कैलकुलेटर',
    'calc.subtitle': 'बीज, खाद, पानी और लागत का आसान हिसाब',
    'calc.section.farm': 'खेती के कैलकुलेटर',
    'calc.section.units': 'इकाई बदलें',
    'calc.hisabLink.title': 'मेरा खेती हिसाब',
    'calc.hisabLink.body': 'असली खर्च और आय लिखें, लाभ अपने-आप जुड़ेगा',
    'calc.listNote': 'ये सामान्य अनुमान हैं। खाद और दवा की सही मात्रा के लिए मिट्टी जांच और कृषि विशेषज्ञ की सलाह लें।',
    'calc.notFound.title': 'यह कैलकुलेटर नहीं मिला',
    'calc.notFound.body': 'सभी कैलकुलेटर की सूची से चुनें।',
    'calc.notFound.action': 'सभी कैलकुलेटर',

    'calc.k.seed.title': 'बीज कैलकुलेटर',
    'calc.k.seed.desc': 'खेत के लिए कितना बीज',
    'calc.k.fertilizer.title': 'खाद कैलकुलेटर',
    'calc.k.fertilizer.desc': 'यूरिया, DAP, पोटाश की बोरी',
    'calc.k.pesticide.title': 'कीटनाशक मिश्रण',
    'calc.k.pesticide.desc': 'टंकी में कितनी दवा',
    'calc.k.irrigation.title': 'सिंचाई कैलकुलेटर',
    'calc.k.irrigation.desc': 'कितना पानी, कितने घंटे',
    'calc.k.cost.title': 'खेती लागत',
    'calc.k.cost.desc': 'कुल और प्रति एकड़ खर्च',
    'calc.k.profit.title': 'लाभ कैलकुलेटर',
    'calc.k.profit.desc': 'उपज × भाव − लागत',
    'calc.k.area.title': 'क्षेत्र बदलें',
    'calc.k.area.desc': 'एकड़, बीघा, हेक्टेयर',
    'calc.k.weight.title': 'वज़न बदलें',
    'calc.k.weight.desc': 'क्विंटल, किलो, टन',

    // Units
    'calc.unit.sqm': 'वर्ग मीटर',
    'calc.unit.sqft': 'वर्ग फुट',
    'calc.unit.sqyd': 'गज (वर्ग गज)',
    'calc.unit.tonne': 'टन',
    'calc.unit.litre': 'लीटर',
    'calc.unit.ml': 'मि.ली.',
    'calc.unit.g': 'ग्राम',
    'calc.unit.perAcre': 'किलो/एकड़',
    'calc.unit.perHa': 'किलो/हेक्टेयर',
    'calc.unit.gPerAcre': 'ग्राम/एकड़',
    'calc.q.kg': '{n} किलो',
    'calc.q.g': '{n} ग्राम',
    'calc.q.kgQtl': '{n} किलो ({q} क्विंटल)',
    'calc.q.ml': '{n} मि.ली.',
    'calc.q.l': '{n} लीटर',
    'calc.q.range': '{min} – {max}',

    // Shared parts
    'calc.area.label': 'ज़मीन',
    'calc.area.unit': 'इकाई',
    'calc.area.inAcres': '= {n} एकड़',
    'calc.area.bighaIs': '1 बीघा = {acre} एकड़ — {name}',
    'calc.area.changeBigha': 'बीघा का माप बदलें',
    'calc.area.error': 'ज़मीन लिखें (0 से ज़्यादा)',
    'calc.result.waiting': 'ऊपर की जानकारी भरें, नतीजा यहां दिखेगा',
    'calc.how.title': 'कैसे निकाला?',
    'calc.crop.label': 'फसल',
    'calc.crop.pick': 'फसल चुनें',
    'calc.crop.change': 'फसल बदलें',
    'calc.crop.sheet': 'फसल चुनें',
    'calc.crop.none': 'कोई फसल नहीं चुनी',

    // Bigha
    'calc.bigha.title': 'आपके इलाके का बीघा',
    'calc.bigha.preset': 'राज्य / इलाका',
    'calc.bigha.custom': '1 बीघा कितना है?',
    'calc.bigha.customUnit': 'इकाई',
    'calc.bigha.customHint': 'सही माप अपने पटवारी या खतौनी से पूछ लें',
    'calc.bigha.customError': '{min} से {max} वर्ग मीटर के बीच का माप लिखें',
    'calc.bigha.note': 'बीघा हर राज्य में अलग होता है, और कई जगह एक ही ज़िले में भी (जैसे पक्का और कच्चा बीघा)। यहां आम तौर पर चलने वाले माप दिए हैं — अपनी ज़मीन के कागज़ से मिला लें।',
    'calc.bigha.current': '1 बीघा = {sqm} वर्ग मीटर = {acre} एकड़',
    'calc.bigha.sheet': 'बीघा का माप',
    'calc.bigha.customName': 'आपका अपना माप',
    'calc.bigha.usedEverywhere': 'यही माप पूरे ऐप में बीघा के हिसाब के लिए इस्तेमाल होगा।',
    'calc.bigha.apply': 'यह माप लगाएं',
    'calc.saved.on': 'ये आंकड़े पिछली बार {date} को भरे थे — एक बार जांच लें',
    'calc.saved.old': 'ये आंकड़े पिछली बार भरे गए थे — एक बार जांच लें',

    // Seed
    'calc.seed.option': 'बीज का प्रकार',
    'calc.seed.rateMin': 'बीज दर (कम से कम)',
    'calc.seed.rateMax': 'बीज दर (ज़्यादा से ज़्यादा)',
    'calc.seed.rateHint': 'फसल चुनने पर सामान्य दर भर जाती है। अपने बीज के पैकेट के हिसाब से बदल सकते हैं।',
    'calc.seed.rateError': 'बीज दर लिखें',
    'calc.seed.result': 'कुल बीज चाहिए',
    'calc.seed.perAcre': 'प्रति एकड़: {range}',
    'calc.seed.forArea': '{area} के लिए',
    'calc.seed.catalogNote': 'सुझाई गई दर: {note}',
    'calc.seed.treatTitle': 'बुवाई से पहले बीज उपचार',
    'calc.seed.treatGeneric': 'बुवाई से पहले बीज को अनुशंसित फफूंदनाशक या ट्राइकोडर्मा से उपचारित करें। दलहन में राइजोबियम कल्चर भी लगाएं। दवा की मात्रा पैकेट या कृषि विशेषज्ञ के अनुसार रखें।',
    'calc.seed.germination': 'बीज का अंकुरण 70% से कम हो तो बीज थोड़ा ज़्यादा लें। 100 दाने गीले कपड़े में रखकर अंकुरण जांच सकते हैं।',
    'calc.seed.howArea': '{area} = {acres} एकड़',
    'calc.seed.howCalc': '{acres} एकड़ × {rate}/एकड़ = {total}',
    'calc.seed.howSource': 'बीज दर सामान्य सलाह है (PAU, ICAR और कृषि विश्वविद्यालयों की पैकेज ऑफ़ प्रैक्टिसेज़ से)। किस्म, बुवाई का समय और अंकुरण देखकर दर बदल सकती है।',

    // Fertilizer
    'calc.fert.mode': 'खाद की मात्रा कहां से लें',
    'calc.fert.modeCrop': 'फसल की सलाह',
    'calc.fert.modeCustom': 'अपनी मात्रा',
    'calc.fert.need': 'प्रति एकड़ ज़रूरत',
    'calc.fert.n': 'नाइट्रोजन (N)',
    'calc.fert.p': 'फॉस्फोरस (P₂O₅)',
    'calc.fert.k': 'पोटाश (K₂O)',
    'calc.fert.customHint': 'यहां पोषक तत्व की मात्रा भरें: नाइट्रोजन (N), फॉस्फोरस (P₂O₅) और पोटाश (K₂O) — यूरिया या DAP की मात्रा नहीं। मिट्टी जांच कार्ड (Soil Health Card) पर मात्रा ज़्यादातर प्रति हेक्टेयर लिखी होती है, तब नीचे "किलो/हेक्टेयर" चुनें।',
    'calc.fert.basis': 'मात्रा किस हिसाब से लिखी है',
    'calc.fert.perAcreIs': 'प्रति एकड़: N {n}, P₂O₅ {p}, K₂O {k} किलो',
    'calc.fert.pickCropFirst': 'फसल चुनें, या "अपनी मात्रा" में N, P, K लिखें',
    'calc.fert.result': 'कुल खाद चाहिए',
    'calc.fert.urea': 'यूरिया',
    'calc.fert.dap': 'DAP',
    'calc.fert.mop': 'पोटाश (MOP)',
    'calc.fert.bags': '{n} बोरी ({size} किलो वाली)',
    'calc.fert.exactKg': 'असल ज़रूरत {kg}',
    'calc.fert.left': 'आख़िरी बोरी से {kg} बचेगा',
    'calc.fert.none': 'ज़रूरत नहीं',
    'calc.fert.extraN': 'DAP से ही ज़रूरत भर नाइट्रोजन मिल जाएगा, यूरिया की ज़रूरत नहीं।',
    'calc.fert.splitTitle': 'खाद कब और कैसे डालें',
    'calc.fert.splitGeneric': 'DAP और पोटाश की पूरी मात्रा बुवाई के समय डालें। यूरिया को 2–3 हिस्सों में बांटें — बुवाई पर, और फिर सिंचाई के साथ। एक साथ सारा यूरिया डालने से वह बेकार बह जाता है।',
    'calc.fert.soilTitle': 'पहले मिट्टी जांच कराएं',
    'calc.fert.soilBody': 'मिट्टी जांच से पता चलता है कि खेत में असल में किस तत्व की कमी है। इससे खाद का खर्च भी बचता है।',
    'calc.fert.soilAction': 'मिट्टी जांच देखें',
    'calc.fert.howDap': 'DAP = फॉस्फोरस {p} ÷ 0.46 = {dap} किलो/एकड़',
    'calc.fert.howNDap': 'DAP से मिला नाइट्रोजन = {dap} × 0.18 = {nDap} किलो/एकड़',
    'calc.fert.howUrea': 'यूरिया = (नाइट्रोजन {n} − {nDap}) ÷ 0.46 = {urea} किलो/एकड़',
    'calc.fert.howMop': 'पोटाश (MOP) = {k} ÷ 0.60 = {mop} किलो/एकड़',
    'calc.fert.howTotal': 'इसे {acres} एकड़ से गुणा किया। यूरिया की बोरी 45 किलो की, DAP और MOP की 50 किलो की मानी है।',
    'calc.fert.howSource': 'फसल की मात्रा मध्यम उपजाऊ मिट्टी के लिए सामान्य सलाह है (PAU, ICAR और कृषि विश्वविद्यालयों से)।',

    // Pesticide
    'calc.pest.mode': 'लेबल पर दवा की मात्रा कैसे लिखी है?',
    'calc.pest.modeLitre': 'प्रति लीटर',
    'calc.pest.modeAcre': 'प्रति एकड़',
    'calc.pest.unit': 'दवा की इकाई',
    'calc.pest.ml': 'मि.ली. (तरल)',
    'calc.pest.g': 'ग्राम (पाउडर)',
    'calc.pest.dosePerL': 'दवा प्रति लीटर पानी',
    'calc.pest.dosePerAcre': 'दवा प्रति एकड़',
    'calc.pest.doseHint': 'दवा के डिब्बे या लेबल पर लिखी मात्रा ही लिखें',
    'calc.pest.tank': 'टंकी (पंप) का साइज़',
    'calc.pest.tankHint': 'आम कमर वाली टंकी 15–16 लीटर की होती है',
    'calc.pest.water': 'पानी प्रति एकड़',
    'calc.pest.waterHint': 'आम तौर पर 150–200 लीटर प्रति एकड़ — लेबल देखें',
    'calc.pest.areaOptional': 'कुल टंकी और कुल दवा जानने के लिए ज़मीन भी लिखें',
    'calc.pest.result': 'हर टंकी में दवा',
    'calc.pest.perTank': '{tank} लीटर पानी में',
    'calc.pest.tanks': 'कुल टंकी: {n}',
    'calc.pest.total': 'कुल दवा: {total}',
    'calc.pest.totalWater': 'कुल पानी: {n} लीटर',
    'calc.pest.lastTank': 'आख़िरी टंकी अधूरी भरनी हो तो दवा भी उसी हिसाब से कम डालें।',
    'calc.pest.checkLabelTitle': 'लेबल दोबारा देखें',
    'calc.pest.checkLabel': 'इस हिसाब से हर लीटर पानी में {dose} दवा जा रही है। ज़्यादातर दवाएं 1 लीटर में {max} मि.ली. या ग्राम से बहुत कम डाली जाती हैं। देखें कि मात्रा प्रति लीटर लिखी है या प्रति एकड़, और ऊपर सही विकल्प चुना है।',
    'calc.pest.safetyTitle': 'छिड़काव में सावधानी',
    'calc.pest.safety1': 'दस्ताने, मास्क और पूरे कपड़े पहनें।',
    'calc.pest.safety2': 'हवा के रुख के साथ छिड़कें; तेज़ हवा या बारिश में छिड़काव न करें।',
    'calc.pest.safety3': 'छिड़काव के समय कुछ न खाएं-पिएं, बीड़ी-तंबाकू न लें।',
    'calc.pest.safety4': 'लेबल से ज़्यादा दवा न डालें — इससे फसल, सेहत और पैसा तीनों का नुकसान होता है।',
    'calc.pest.safety5': 'खाली डिब्बा धोकर ज़मीन में गाड़ दें; दवा बच्चों और पशुओं से दूर रखें।',
    'calc.pest.safety6': 'कटाई से पहले लेबल पर लिखा इंतज़ार का समय ज़रूर मानें।',
    'calc.pest.disclaimer': 'कौन-सी दवा और कितनी मात्रा — यह कृषि विशेषज्ञ या KVK से पूछकर ही तय करें। यह कैलकुलेटर सिर्फ़ घोल बनाने का हिसाब करता है।',
    'calc.pest.howTank': 'हर टंकी: {dose}/लीटर × {tank} लीटर = {perTank}',
    'calc.pest.howWater': 'कुल पानी: {water} लीटर/एकड़ × {acres} एकड़ = {total} लीटर',
    'calc.pest.howTanks': 'टंकी: {total} लीटर ÷ {tank} लीटर = {exact} → {n} टंकी',
    'calc.pest.howDose': 'कुल दवा: {dose}/लीटर × {water} लीटर = {total}',
    'calc.pest.howAcreTotal': 'कुल दवा: {dose}/एकड़ × {acres} एकड़ = {total}',
    'calc.pest.howAcreTank': 'हर टंकी: {dose} ÷ {water} लीटर × {tank} लीटर = {perTank}',

    // Irrigation
    'calc.irr.depth': 'पानी की गहराई',
    'calc.irr.depthUnit': 'इकाई',
    'calc.irr.depthHint': 'एक सिंचाई में आम तौर पर 5–7 सेमी पानी लगता है (जैसे गेहूं)',
    'calc.irr.mm': 'मि.मी.',
    'calc.irr.cm': 'सेमी',
    'calc.irr.flowTitle': 'मोटर कितनी देर चलेगी?',
    'calc.irr.flowMode': 'पानी का बहाव कैसे पता करें',
    'calc.irr.modeLps': 'लीटर/सेकंड',
    'calc.irr.modeHp': 'मोटर HP',
    'calc.irr.modeDrum': 'ड्रम से नापें',
    'calc.irr.flow': 'पानी का बहाव',
    'calc.irr.lps': 'लीटर/सेकंड',
    'calc.irr.hp': 'मोटर की ताकत',
    'calc.irr.hpUnit': 'HP',
    'calc.irr.head': 'पानी कितनी गहराई से उठता है',
    'calc.irr.metre': 'मीटर',
    'calc.irr.headHint': 'कुएं या बोरिंग में पानी की सतह से निकास तक की ऊंचाई',
    'calc.irr.hpNote': 'HP से बहाव सिर्फ़ मोटा अंदाज़ा है (मोटर-पंप की क्षमता 40% मानी है)। सही बहाव के लिए ड्रम से नापें।',
    'calc.irr.drum': 'ड्रम या बाल्टी का साइज़',
    'calc.irr.drumTime': 'भरने में लगा समय',
    'calc.irr.seconds': 'सेकंड',
    'calc.irr.drumHint': 'पाइप के मुंह पर ड्रम रखें और भरने का समय घड़ी से नापें',
    'calc.irr.flowCalc': 'बहाव ≈ {n} लीटर/सेकंड',
    'calc.irr.result': 'कुल पानी चाहिए',
    'calc.irr.m3': '{n} घन मीटर',
    'calc.irr.hours': 'मोटर लगभग {time} चलेगी',
    'calc.irr.hm': '{h} घंटे {m} मिनट',
    'calc.irr.min': '{m} मिनट',
    'calc.irr.addFlow': 'मोटर का समय जानने के लिए नीचे पानी का बहाव भरें',
    'calc.irr.loss': 'नाली में रिसाव और भाप से असल में 20–40% ज़्यादा पानी लग सकता है।',
    'calc.irr.howArea': 'ज़मीन: {area} = {sqm} वर्ग मीटर',
    'calc.irr.howVolume': 'पानी: {sqm} वर्ग मीटर × {depth} मीटर = {m3} घन मीटर = {litres} लीटर',
    'calc.irr.howHp': 'बहाव ≈ {hp} HP × 746 × 0.4 ÷ (9.81 × {head} मीटर) = {flow} लीटर/सेकंड',
    'calc.irr.howDrum': 'बहाव = {drum} लीटर ÷ {sec} सेकंड = {flow} लीटर/सेकंड',
    'calc.irr.howTime': 'समय: {litres} लीटर ÷ {flow} लीटर/सेकंड ≈ {time}',

    // Cost
    'calc.cost.items': 'खर्च लिखें',
    'calc.cost.itemsHint': 'जिस चीज़ पर खर्च नहीं हुआ, उसे खाली छोड़ दें',
    'calc.cost.fromHisab': 'खेती हिसाब से भरें',
    'calc.cost.fromHisabTitle': 'हिसाब से कौन-सा खर्च लें?',
    'calc.cost.fromSeason': '{season} के सभी खर्च',
    'calc.cost.fromHisabDesc': 'कुल {amount} • {n} एंट्री',
    'calc.cost.filled': 'हिसाब से खर्च भर दिया',
    'calc.cost.clear': 'सब खाली करें',
    'calc.cost.cleared': 'सब खाली कर दिया',
    'calc.cost.result': 'कुल लागत',
    'calc.cost.perAcre': 'प्रति एकड़ लागत: {amount}',
    'calc.cost.biggest': 'सबसे बड़ा खर्च: {category} ({pct}%)',
    'calc.cost.toProfit': 'इस लागत से लाभ निकालें',
    'calc.cost.ownNote': 'अपनी मेहनत, ज़मीन का किराया और कर्ज़ का ब्याज भी "अन्य" में जोड़ें, तभी असली लागत पता चलती है।',
    'calc.cost.howTotal': 'कुल लागत = सभी खर्च का जोड़ = {total}',
    'calc.cost.howPerAcre': 'प्रति एकड़ = {total} ÷ {acres} एकड़ = {perAcre}',

    // Profit
    'calc.profit.crop': 'फसल (मंडी भाव के लिए)',
    'calc.profit.yield': 'अनुमानित उपज',
    'calc.profit.yieldUnit': 'क्विंटल/एकड़',
    'calc.profit.yieldHint': 'पिछले साल की अपनी उपज देखकर लिखें',
    'calc.profit.price': 'अनुमानित भाव',
    'calc.profit.mandi': 'मंडी भाव (अनुमानित): {price}/क्विंटल',
    'calc.profit.mandiMeta': '{market} • भाव की तारीख: {date}',
    'calc.profit.useMandi': 'यह भाव भरें',
    'calc.profit.noMandi': 'इस फसल का हाल का मंडी भाव फ़ोन में सेव नहीं है।',
    'calc.profit.oldMandi': 'यह भाव पुराना है ({date} का मंडी भाव)',
    'calc.profit.oldMandiNoDate': 'यह पुराना मंडी भाव हो सकता है',
    'calc.profit.oldMandiHint': 'आज का भाव इससे अलग हो सकता है। नया भाव देखें या अपना अंदाज़ा लिखें।',
    'calc.profit.openMandi': 'मंडी भाव देखें',
    'calc.profit.indicative': 'अनुमानित',
    'calc.profit.cost': 'कुल लागत',
    'calc.profit.costHint': 'पूरी ज़मीन पर बीज, खाद, मजदूरी आदि का कुल खर्च',
    'calc.profit.useCost': 'लागत कैलकुलेटर से लें: {area} की लागत {amount}',
    'calc.profit.costFromCalc': 'लागत कैलकुलेटर से ली गई: {area} की लागत {amount}',
    'calc.profit.costScaled': 'लागत कैलकुलेटर में {area} की लागत {amount} है। इस ज़मीन ({acres} एकड़) के हिसाब से {scaled} मानी है।',
    'calc.profit.findCost': 'लागत निकालें',
    'calc.profit.resultProfit': 'अनुमानित लाभ',
    'calc.profit.resultLoss': 'अनुमानित घाटा',
    'calc.profit.resultRevenue': 'अनुमानित आमदनी',
    'calc.profit.noCost': 'लागत नहीं जोड़ी — यह सिर्फ़ आमदनी है, लाभ नहीं। लाभ जानने के लिए ऊपर कुल लागत लिखें।',
    'calc.profit.need': 'नतीजे के लिए यह भरें: {fields}',
    'calc.profit.totalYield': 'कुल उपज: {n} क्विंटल',
    'calc.profit.revenue': 'कुल आमदनी: {amount}',
    'calc.profit.costLine': 'लागत: {amount}',
    'calc.profit.perAcre': 'प्रति एकड़ लाभ: {amount}',
    'calc.profit.perAcreLoss': 'प्रति एकड़ घाटा: {amount}',
    'calc.profit.breakEven': 'बिना घाटे का भाव: {price}/क्विंटल',
    'calc.profit.breakEvenHint': 'इससे कम भाव मिला तो घाटा होगा',
    'calc.profit.note': 'उपज और भाव अंदाज़े हैं। मौसम और बाज़ार के हिसाब से असली लाभ अलग हो सकता है।',
    'calc.profit.howYield': 'कुल उपज = {yield} क्विंटल/एकड़ × {acres} एकड़ = {total} क्विंटल',
    'calc.profit.howRevenue': 'आमदनी = {total} क्विंटल × {price} = {revenue}',
    'calc.profit.howScaled': 'लागत = {amount} ÷ {costAcres} एकड़ × {acres} एकड़ = {scaled}',
    'calc.profit.howProfit': 'लाभ = {revenue} − {cost} = {profit}',
    'calc.profit.howBreakEven': 'बिना घाटे का भाव = {cost} ÷ {total} क्विंटल = {be}',

    // Area converter
    'calc.areaConv.result': 'बराबर है',
    'calc.areaConv.table': 'सभी इकाइयों में',
    'calc.areaConv.how1': '1 एकड़ = 4,046.86 वर्ग मीटर = 43,560 वर्ग फुट',
    'calc.areaConv.how2': '1 हेक्टेयर = 10,000 वर्ग मीटर = 2.471 एकड़',
    'calc.areaConv.how3': '1 बीघा = {sqm} वर्ग मीटर — {name}',
    'calc.areaConv.how4': '1 गज = 9 वर्ग फुट = 0.836 वर्ग मीटर',

    // Weight converter
    'calc.weight.value': 'वज़न',
    'calc.weight.unit': 'इकाई',
    'calc.weight.error': 'वज़न लिखें (0 से ज़्यादा)',
    'calc.weight.how1': '1 क्विंटल = 100 किलो',
    'calc.weight.how2': '1 टन = 10 क्विंटल = 1,000 किलो',
  },
  en: {
    'calc.title': 'Farm calculators',
    'calc.subtitle': 'Easy sums for seed, fertilizer, water and cost',
    'calc.section.farm': 'Farm calculators',
    'calc.section.units': 'Convert units',
    'calc.hisabLink.title': 'My farm accounts',
    'calc.hisabLink.body': 'Note real expenses and income; profit adds up automatically',
    'calc.listNote': 'These are general estimates. Use a soil test and an agriculture expert for exact fertilizer and pesticide doses.',
    'calc.notFound.title': 'Calculator not found',
    'calc.notFound.body': 'Pick one from the list of calculators.',
    'calc.notFound.action': 'All calculators',

    'calc.k.seed.title': 'Seed calculator',
    'calc.k.seed.desc': 'How much seed for your field',
    'calc.k.fertilizer.title': 'Fertilizer calculator',
    'calc.k.fertilizer.desc': 'Bags of urea, DAP, potash',
    'calc.k.pesticide.title': 'Spray mixing',
    'calc.k.pesticide.desc': 'Pesticide per tank',
    'calc.k.irrigation.title': 'Irrigation calculator',
    'calc.k.irrigation.desc': 'How much water, how many hours',
    'calc.k.cost.title': 'Cost of cultivation',
    'calc.k.cost.desc': 'Total and per-acre cost',
    'calc.k.profit.title': 'Profit calculator',
    'calc.k.profit.desc': 'Yield × price − cost',
    'calc.k.area.title': 'Convert area',
    'calc.k.area.desc': 'Acre, bigha, hectare',
    'calc.k.weight.title': 'Convert weight',
    'calc.k.weight.desc': 'Quintal, kg, tonne',

    'calc.unit.sqm': 'sq metre',
    'calc.unit.sqft': 'sq ft',
    'calc.unit.sqyd': 'sq yard (gaj)',
    'calc.unit.tonne': 'tonne',
    'calc.unit.litre': 'litre',
    'calc.unit.ml': 'ml',
    'calc.unit.g': 'g',
    'calc.unit.perAcre': 'kg/acre',
    'calc.unit.perHa': 'kg/hectare',
    'calc.unit.gPerAcre': 'g/acre',
    'calc.q.kg': '{n} kg',
    'calc.q.g': '{n} g',
    'calc.q.kgQtl': '{n} kg ({q} quintal)',
    'calc.q.ml': '{n} ml',
    'calc.q.l': '{n} litre',
    'calc.q.range': '{min} – {max}',

    'calc.area.label': 'Land',
    'calc.area.unit': 'Unit',
    'calc.area.inAcres': '= {n} acres',
    'calc.area.bighaIs': '1 bigha = {acre} acre — {name}',
    'calc.area.changeBigha': 'Change bigha size',
    'calc.area.error': 'Enter the land (more than 0)',
    'calc.result.waiting': 'Fill in the details above to see the result here',
    'calc.how.title': 'How was this worked out?',
    'calc.crop.label': 'Crop',
    'calc.crop.pick': 'Choose crop',
    'calc.crop.change': 'Change crop',
    'calc.crop.sheet': 'Choose crop',
    'calc.crop.none': 'No crop chosen',

    'calc.bigha.title': 'Bigha in your area',
    'calc.bigha.preset': 'State / area',
    'calc.bigha.custom': 'How big is 1 bigha?',
    'calc.bigha.customUnit': 'Unit',
    'calc.bigha.customHint': 'Ask your patwari or check your land record for the exact size',
    'calc.bigha.customError': 'Enter a size between {min} and {max} sq metres',
    'calc.bigha.note': 'A bigha differs from state to state, and often within one district (pucca and kachcha bigha). These are typical values — check them against your land papers.',
    'calc.bigha.current': '1 bigha = {sqm} sq m = {acre} acre',
    'calc.bigha.sheet': 'Bigha size',
    'calc.bigha.customName': 'your own size',
    'calc.bigha.usedEverywhere': 'This size is used for bigha everywhere in the app.',
    'calc.bigha.apply': 'Use this size',
    'calc.saved.on': 'You entered these on {date} — check they still apply',
    'calc.saved.old': 'These numbers are from an earlier visit — check they still apply',

    'calc.seed.option': 'Seed type',
    'calc.seed.rateMin': 'Seed rate (minimum)',
    'calc.seed.rateMax': 'Seed rate (maximum)',
    'calc.seed.rateHint': 'Choosing a crop fills in the usual rate. You can change it to match your seed packet.',
    'calc.seed.rateError': 'Enter the seed rate',
    'calc.seed.result': 'Total seed needed',
    'calc.seed.perAcre': 'Per acre: {range}',
    'calc.seed.forArea': 'For {area}',
    'calc.seed.catalogNote': 'Suggested rate: {note}',
    'calc.seed.treatTitle': 'Treat the seed before sowing',
    'calc.seed.treatGeneric': 'Treat seed with a recommended fungicide or Trichoderma before sowing. For pulses, also apply Rhizobium culture. Follow the packet or an expert for the dose.',
    'calc.seed.germination': 'If germination is below 70%, use a little more seed. Test it by keeping 100 seeds in a wet cloth.',
    'calc.seed.howArea': '{area} = {acres} acres',
    'calc.seed.howCalc': '{acres} acres × {rate}/acre = {total}',
    'calc.seed.howSource': 'Seed rates are general guidance (PAU, ICAR and agricultural university packages of practices). Variety, sowing time and germination can change them.',

    'calc.fert.mode': 'Where should the doses come from',
    'calc.fert.modeCrop': 'Crop advice',
    'calc.fert.modeCustom': 'My own dose',
    'calc.fert.need': 'Need per acre',
    'calc.fert.n': 'Nitrogen (N)',
    'calc.fert.p': 'Phosphorus (P₂O₅)',
    'calc.fert.k': 'Potash (K₂O)',
    'calc.fert.customHint': 'Enter nutrient amounts: nitrogen (N), phosphorus (P₂O₅) and potash (K₂O) — not amounts of urea or DAP. Soil Health Cards usually give them per hectare; then choose "kg/hectare" below.',
    'calc.fert.basis': 'The amounts are written per',
    'calc.fert.perAcreIs': 'Per acre: N {n}, P₂O₅ {p}, K₂O {k} kg',
    'calc.fert.pickCropFirst': 'Choose a crop, or enter N, P, K under "My own dose"',
    'calc.fert.result': 'Total fertilizer needed',
    'calc.fert.urea': 'Urea',
    'calc.fert.dap': 'DAP',
    'calc.fert.mop': 'Potash (MOP)',
    'calc.fert.bags': '{n} bags ({size} kg)',
    'calc.fert.exactKg': 'Exact need {kg}',
    'calc.fert.left': '{kg} left from the last bag',
    'calc.fert.none': 'Not needed',
    'calc.fert.extraN': 'DAP alone supplies the nitrogen needed; no urea required.',
    'calc.fert.splitTitle': 'When and how to apply',
    'calc.fert.splitGeneric': 'Apply all the DAP and potash at sowing. Split urea into 2–3 doses — at sowing, then with irrigations. Putting all the urea at once wastes it.',
    'calc.fert.soilTitle': 'Get a soil test first',
    'calc.fert.soilBody': 'A soil test shows which nutrient your field really lacks, and saves money on fertilizer.',
    'calc.fert.soilAction': 'Open soil health',
    'calc.fert.howDap': 'DAP = phosphorus {p} ÷ 0.46 = {dap} kg/acre',
    'calc.fert.howNDap': 'Nitrogen from DAP = {dap} × 0.18 = {nDap} kg/acre',
    'calc.fert.howUrea': 'Urea = (nitrogen {n} − {nDap}) ÷ 0.46 = {urea} kg/acre',
    'calc.fert.howMop': 'Potash (MOP) = {k} ÷ 0.60 = {mop} kg/acre',
    'calc.fert.howTotal': 'Multiplied by {acres} acres. Urea bags are 45 kg; DAP and MOP bags 50 kg.',
    'calc.fert.howSource': 'Crop doses are general advice for medium-fertility soil (PAU, ICAR and agricultural universities).',

    'calc.pest.mode': 'How is the dose written on the label?',
    'calc.pest.modeLitre': 'Per litre',
    'calc.pest.modeAcre': 'Per acre',
    'calc.pest.unit': 'Product unit',
    'calc.pest.ml': 'ml (liquid)',
    'calc.pest.g': 'g (powder)',
    'calc.pest.dosePerL': 'Product per litre of water',
    'calc.pest.dosePerAcre': 'Product per acre',
    'calc.pest.doseHint': 'Enter only the dose written on the label',
    'calc.pest.tank': 'Tank (sprayer) size',
    'calc.pest.tankHint': 'A common knapsack sprayer holds 15–16 litres',
    'calc.pest.water': 'Water per acre',
    'calc.pest.waterHint': 'Usually 150–200 litres per acre — check the label',
    'calc.pest.areaOptional': 'Add your land to see total tanks and total product',
    'calc.pest.result': 'Product per tank',
    'calc.pest.perTank': 'in {tank} litres of water',
    'calc.pest.tanks': 'Total tanks: {n}',
    'calc.pest.total': 'Total product: {total}',
    'calc.pest.totalWater': 'Total water: {n} litres',
    'calc.pest.lastTank': 'If the last tank is only part full, reduce the product in the same proportion.',
    'calc.pest.checkLabelTitle': 'Check the label again',
    'calc.pest.checkLabel': 'This puts {dose} of product in every litre of water. Most products are used at well under {max} ml or g per litre. Check whether the label dose is per litre or per acre, and that the right option is chosen above.',
    'calc.pest.safetyTitle': 'Spray safely',
    'calc.pest.safety1': 'Wear gloves, a mask and full clothing.',
    'calc.pest.safety2': 'Spray with the wind behind you; never in strong wind or rain.',
    'calc.pest.safety3': 'Do not eat, drink or smoke while spraying.',
    'calc.pest.safety4': 'Never use more than the label dose — it harms the crop, your health and your pocket.',
    'calc.pest.safety5': 'Rinse empty containers and bury them; keep chemicals away from children and animals.',
    'calc.pest.safety6': 'Respect the waiting period before harvest written on the label.',
    'calc.pest.disclaimer': 'Decide the product and dose only with an agriculture expert or KVK. This calculator only works out the mixing.',
    'calc.pest.howTank': 'Per tank: {dose}/litre × {tank} litres = {perTank}',
    'calc.pest.howWater': 'Total water: {water} litres/acre × {acres} acres = {total} litres',
    'calc.pest.howTanks': 'Tanks: {total} litres ÷ {tank} litres = {exact} → {n} tanks',
    'calc.pest.howDose': 'Total product: {dose}/litre × {water} litres = {total}',
    'calc.pest.howAcreTotal': 'Total product: {dose}/acre × {acres} acres = {total}',
    'calc.pest.howAcreTank': 'Per tank: {dose} ÷ {water} litres × {tank} litres = {perTank}',

    'calc.irr.depth': 'Water depth',
    'calc.irr.depthUnit': 'Unit',
    'calc.irr.depthHint': 'One irrigation is usually 5–7 cm of water (e.g. wheat)',
    'calc.irr.mm': 'mm',
    'calc.irr.cm': 'cm',
    'calc.irr.flowTitle': 'How long will the pump run?',
    'calc.irr.flowMode': 'How to know the water flow',
    'calc.irr.modeLps': 'Litre/sec',
    'calc.irr.modeHp': 'Motor HP',
    'calc.irr.modeDrum': 'Drum test',
    'calc.irr.flow': 'Water flow',
    'calc.irr.lps': 'litre/sec',
    'calc.irr.hp': 'Motor power',
    'calc.irr.hpUnit': 'HP',
    'calc.irr.head': 'Lift (depth of water)',
    'calc.irr.metre': 'metre',
    'calc.irr.headHint': 'Height from the water level in the well or bore to the outlet',
    'calc.irr.hpNote': 'Flow from HP is only a rough guess (40% pump efficiency assumed). Time a drum for the real flow.',
    'calc.irr.drum': 'Drum or bucket size',
    'calc.irr.drumTime': 'Time to fill',
    'calc.irr.seconds': 'seconds',
    'calc.irr.drumHint': 'Hold the drum at the pipe outlet and time how long it takes to fill',
    'calc.irr.flowCalc': 'Flow ≈ {n} litre/sec',
    'calc.irr.result': 'Total water needed',
    'calc.irr.m3': '{n} cubic metres',
    'calc.irr.hours': 'Pump runs about {time}',
    'calc.irr.hm': '{h} h {m} min',
    'calc.irr.min': '{m} min',
    'calc.irr.addFlow': 'Add the water flow below to see the pump time',
    'calc.irr.loss': 'Seepage in channels and evaporation can add 20–40% more water.',
    'calc.irr.howArea': 'Land: {area} = {sqm} sq m',
    'calc.irr.howVolume': 'Water: {sqm} sq m × {depth} m = {m3} cubic m = {litres} litres',
    'calc.irr.howHp': 'Flow ≈ {hp} HP × 746 × 0.4 ÷ (9.81 × {head} m) = {flow} litre/sec',
    'calc.irr.howDrum': 'Flow = {drum} litres ÷ {sec} sec = {flow} litre/sec',
    'calc.irr.howTime': 'Time: {litres} litres ÷ {flow} litre/sec ≈ {time}',

    'calc.cost.items': 'Enter expenses',
    'calc.cost.itemsHint': 'Leave blank anything you did not spend on',
    'calc.cost.fromHisab': 'Fill from farm accounts',
    'calc.cost.fromHisabTitle': 'Which expenses should we use?',
    'calc.cost.fromSeason': 'All expenses — {season}',
    'calc.cost.fromHisabDesc': 'Total {amount} • {n} entries',
    'calc.cost.filled': 'Filled from your accounts',
    'calc.cost.clear': 'Clear all',
    'calc.cost.cleared': 'Cleared',
    'calc.cost.result': 'Total cost',
    'calc.cost.perAcre': 'Cost per acre: {amount}',
    'calc.cost.biggest': 'Biggest expense: {category} ({pct}%)',
    'calc.cost.toProfit': 'Work out profit with this cost',
    'calc.cost.ownNote': 'Add your own labour, land rent and loan interest under "Other" to see the real cost.',
    'calc.cost.howTotal': 'Total cost = sum of all expenses = {total}',
    'calc.cost.howPerAcre': 'Per acre = {total} ÷ {acres} acres = {perAcre}',

    'calc.profit.crop': 'Crop (for mandi price)',
    'calc.profit.yield': 'Expected yield',
    'calc.profit.yieldUnit': 'quintal/acre',
    'calc.profit.yieldHint': 'Use your own yield from last year',
    'calc.profit.price': 'Expected price',
    'calc.profit.mandi': 'Mandi price (indicative): {price}/quintal',
    'calc.profit.mandiMeta': '{market} • price date: {date}',
    'calc.profit.useMandi': 'Use this price',
    'calc.profit.noMandi': 'No recent mandi price for this crop is saved on the phone.',
    'calc.profit.oldMandi': 'This is an old mandi price (from {date})',
    'calc.profit.oldMandiNoDate': 'This may be an old mandi price',
    'calc.profit.oldMandiHint': 'Today’s price may be different. Check the latest price or enter your own estimate.',
    'calc.profit.openMandi': 'See mandi prices',
    'calc.profit.indicative': 'Indicative',
    'calc.profit.cost': 'Total cost',
    'calc.profit.costHint': 'All spending on the whole land: seed, fertilizer, labour…',
    'calc.profit.useCost': 'Use cost calculator: {amount} for {area}',
    'calc.profit.costFromCalc': 'From the cost calculator: {amount} for {area}',
    'calc.profit.costScaled': 'The cost calculator has {amount} for {area}. For this land ({acres} acres) that is taken as {scaled}.',
    'calc.profit.findCost': 'Work out cost',
    'calc.profit.resultProfit': 'Estimated profit',
    'calc.profit.resultLoss': 'Estimated loss',
    'calc.profit.resultRevenue': 'Estimated income',
    'calc.profit.noCost': 'No cost added — this is income only, not profit. Enter the total cost above to see profit.',
    'calc.profit.need': 'To see the result, fill in: {fields}',
    'calc.profit.totalYield': 'Total yield: {n} quintal',
    'calc.profit.revenue': 'Total income: {amount}',
    'calc.profit.costLine': 'Cost: {amount}',
    'calc.profit.perAcre': 'Profit per acre: {amount}',
    'calc.profit.perAcreLoss': 'Loss per acre: {amount}',
    'calc.profit.breakEven': 'Break-even price: {price}/quintal',
    'calc.profit.breakEvenHint': 'Below this price you make a loss',
    'calc.profit.note': 'Yield and price are estimates. Weather and markets can change the real profit.',
    'calc.profit.howYield': 'Total yield = {yield} quintal/acre × {acres} acres = {total} quintal',
    'calc.profit.howRevenue': 'Income = {total} quintal × {price} = {revenue}',
    'calc.profit.howScaled': 'Cost = {amount} ÷ {costAcres} acres × {acres} acres = {scaled}',
    'calc.profit.howProfit': 'Profit = {revenue} − {cost} = {profit}',
    'calc.profit.howBreakEven': 'Break-even price = {cost} ÷ {total} quintal = {be}',

    'calc.areaConv.result': 'Equals',
    'calc.areaConv.table': 'In every unit',
    'calc.areaConv.how1': '1 acre = 4,046.86 sq m = 43,560 sq ft',
    'calc.areaConv.how2': '1 hectare = 10,000 sq m = 2.471 acres',
    'calc.areaConv.how3': '1 bigha = {sqm} sq m — {name}',
    'calc.areaConv.how4': '1 gaj = 9 sq ft = 0.836 sq m',

    'calc.weight.value': 'Weight',
    'calc.weight.unit': 'Unit',
    'calc.weight.error': 'Enter the weight (more than 0)',
    'calc.weight.how1': '1 quintal = 100 kg',
    'calc.weight.how2': '1 tonne = 10 quintal = 1,000 kg',
  },
});
