// Strings for the Home module (prefix "home."). Shared words (today, retry, see all…) come from common.*.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'home.title': 'किसान मित्र',
    'home.changePlace': 'स्थान बदलें, अभी: {place}',
    'home.changeLanguage': 'भाषा बदलें, अभी: {lang}',

    // Greeting
    'home.greeting': 'नमस्ते, {name} जी',
    'home.greetingNoName': 'नमस्ते, किसान साथी',

    // Weather card
    'home.weather.title': 'आज का मौसम',
    'home.weather.forecastTitle': 'आज का अनुमान',
    'home.weather.humidity': '{n}% नमी',
    'home.weather.wind': 'हवा {n} किलोमीटर प्रति घंटा',
    'home.weather.windShort': '{n} km/h',
    'home.weather.rain': 'बारिश {n}%',
    'home.weather.rainShort': '{n}%',
    'home.weather.aqi': 'AQI {value} · {level}',
    'home.weather.maxMin': 'अधिकतम {max}°, न्यूनतम {min}°',
    'home.weather.tomorrowAria': 'कल: {max}° / {min}°, बारिश {p}%',
    'home.weather.updating': 'ताज़ा हो रहा है…',
    'home.weather.openHint': 'पूरा मौसम और अगले दिनों का अनुमान देखने के लिए दबाएं',
    'home.weather.errorTitle': 'मौसम की जानकारी नहीं मिली',
    'home.weather.outdatedTitle': 'मौसम की जानकारी पुरानी हो गई है',
    'home.weather.outdatedBody': 'इंटरनेट मिलते ही आज का ताज़ा मौसम यहां दिखेगा।',

    // Weather alert strip
    'home.alert.seeAria': 'मौसम चेतावनी देखें',
    'home.alert.seeAllAria': 'सभी {n} मौसम चेतावनियां देखें',
    'home.alert.more': '+{n} और',
    'home.alert.oldForecast': 'पुराने पूर्वानुमान के अनुसार',

    // "आज किसान के लिए"
    'home.today.title': 'आज किसान के लिए',
    'home.today.subtitle': 'मौसम और आपकी फसल के हिसाब से',
    'home.today.aiLoading': 'AI आपकी फसल के लिए आज की सलाह तैयार कर रहा है…',
    'home.today.aiError': 'AI सलाह अभी नहीं मिल पाई। {reason}',
    'home.today.aiUpdated': 'AI सलाह: {time}',
    'home.today.addCrop': 'फसल जोड़ें ताकि सलाह आपकी फसल के हिसाब से मिले',
    'home.today.addCropBtn': 'फसल जोड़ें',
    'home.today.empty': 'आज के लिए अभी कोई खास सलाह नहीं है। मौसम की जानकारी मिलते ही सलाह यहां दिखेगी।',
    'home.today.more': 'और {n} सुझाव देखें',
    'home.today.less': 'कम दिखाएं',
    'home.today.diagnosis': '{crop} में {issue} की आशंका',
    'home.today.diagnosisSpeech': '{crop} में {issue} की आशंका है',
    'home.today.diagnosisMeta': 'फोटो जांच: {date} • इलाज देखें',
    'home.today.priceLead': '{crop} का अनुमानित भाव',
    'home.today.priceSpeech': '{crop} का अनुमानित भाव {price} रुपये प्रति क्विंटल',
    'home.today.checkDisease': 'फसल में रोग का शक? फोटो खींचकर जांचें',
    'home.today.cropLink': '{crop} की पूरी जानकारी',
    'home.kind.do': 'करें',
    'home.kind.warn': 'सावधान',
    'home.kind.info': 'जानकारी',

    // Quick actions
    'home.quick.title': 'मुख्य सेवाएं',
    'home.quick.advice': 'फसल सलाह',
    'home.quick.mandi': 'मंडी भाव',
    'home.quick.weather': 'मौसम',
    'home.quick.doctor': 'फसल रोग',
    'home.quick.soil': 'मिट्टी जांच',
    'home.quick.schemes': 'सरकारी योजना',
    'home.quick.calendar': 'कैलेंडर',
    'home.quick.experts': 'विशेषज्ञ',

    // My crops
    'home.crops.title': 'मेरी फसलें',
    'home.crops.add': 'जोड़ें',
    'home.crops.addAria': 'नई फसल जोड़ें',
    'home.crops.area': '{n} {unit}',
    'home.crops.noArea': 'रकबा नहीं जोड़ा',
    'home.crops.progress': 'फसल की प्रगति {pct}%',
    'home.crops.next': 'अगला काम: {task} ({when})',
    'home.crops.overdue': 'बाकी काम: {task} ({date} से)',
    'home.crops.noTask': 'अभी कोई काम तय नहीं है',
    'home.crops.emptyTitle': 'अभी कोई फसल नहीं जोड़ी',
    'home.crops.emptyBody': 'अपनी फसल जोड़ें — रोज़ की सलाह, काम की याद और भाव आपकी फसल के हिसाब से मिलेंगे।',
    'home.crops.emptyAction': 'नई फसल जोड़ें',

    // Mandi
    'home.mandi.title': 'आज की मंडी',
    'home.mandi.trend.up': 'बढ़ा',
    'home.mandi.trend.down': 'घटा',
    'home.mandi.trend.stable': 'स्थिर',
    'home.mandi.errorTitle': 'मंडी भाव नहीं मिल पाए',
    'home.mandi.emptyTitle': 'अभी भाव नहीं मिले',
    'home.mandi.emptyBody': 'आपके क्षेत्र के ताज़ा मंडी भाव अभी उपलब्ध नहीं हैं। मंडी टैब में दूसरी फसल या मंडी देखें।',
    'home.mandi.open': 'मंडी भाव देखें',
    'home.mandi.sources': 'स्रोत: {list}',
    'home.mandi.refreshFailed': 'ताज़ा भाव नहीं मिल पाए, पिछली बार के भाव दिखा रहे हैं।',

    // Upcoming tasks
    'home.tasks.title': 'आने वाले काम',
    'home.tasks.markDone': 'पूरा होने का निशान लगाएं: {task}',
    'home.tasks.doneToast': 'काम पूरा हुआ',
    'home.tasks.undo': 'वापस लें',
    'home.tasks.general': 'सामान्य काम',
    'home.tasks.emptyTitle': 'इस हफ्ते कोई काम नहीं',
    'home.tasks.emptyBody': 'अगले 7 दिन में कोई काम तय नहीं है। पूरा कैलेंडर देखें या अपना काम जोड़ें।',
    'home.tasks.emptyNoCrops': 'फसल जोड़ने पर बुवाई से कटाई तक के सारे काम यहां अपने आप दिखेंगे।',
    'home.tasks.open': 'कैलेंडर खोलें',

    // Voice CTA
    'home.voice.title': 'बोलकर पूछें',
    'home.voice.body': 'अपनी भाषा में सवाल करें — लिखने की ज़रूरत नहीं',
    'home.voice.example': 'जैसे: "गेहूं की पत्तियां पीली क्यों हो रही हैं?"',
    'home.voice.aria': 'बोलकर पूछें — अपनी भाषा में सवाल करें',
  },
  en: {
    'home.title': 'Kisan Mitra',
    'home.changePlace': 'Change location, now: {place}',
    'home.changeLanguage': 'Change language, now: {lang}',

    'home.greeting': 'Namaste, {name} ji',
    'home.greetingNoName': 'Namaste, farmer friend',

    'home.weather.title': "Today's weather",
    'home.weather.forecastTitle': "Today's forecast",
    'home.weather.humidity': '{n}% humidity',
    'home.weather.wind': 'Wind {n} km per hour',
    'home.weather.windShort': '{n} km/h',
    'home.weather.rain': 'Rain {n}%',
    'home.weather.rainShort': '{n}%',
    'home.weather.aqi': 'AQI {value} · {level}',
    'home.weather.maxMin': 'High {max}°, low {min}°',
    'home.weather.tomorrowAria': 'Tomorrow: {max}° / {min}°, rain {p}%',
    'home.weather.updating': 'Refreshing…',
    'home.weather.openHint': 'Tap to see full weather and the coming days',
    'home.weather.errorTitle': 'Could not load weather',
    'home.weather.outdatedTitle': 'Weather information is out of date',
    'home.weather.outdatedBody': "Today's weather will show here once you are online.",

    'home.alert.seeAria': 'View weather alert',
    'home.alert.seeAllAria': 'View all {n} weather alerts',
    'home.alert.more': '+{n} more',
    'home.alert.oldForecast': 'From an older forecast',

    'home.today.title': 'For you today',
    'home.today.subtitle': 'Based on the weather and your crops',
    'home.today.aiLoading': "AI is preparing today's advice for your crops…",
    'home.today.aiError': 'AI advice is not available right now. {reason}',
    'home.today.aiUpdated': 'AI advice: {time}',
    'home.today.addCrop': 'Add your crop to get advice made for it',
    'home.today.addCropBtn': 'Add crop',
    'home.today.empty': 'No special advice for today yet. It will appear here once weather information is available.',
    'home.today.more': 'See {n} more tips',
    'home.today.less': 'Show less',
    'home.today.diagnosis': 'Possible {issue} in {crop}',
    'home.today.diagnosisSpeech': 'Possible {issue} in {crop}',
    'home.today.diagnosisMeta': 'Photo check: {date} • see treatment',
    'home.today.priceLead': 'Estimated {crop} price',
    'home.today.priceSpeech': 'Estimated {crop} price: {price} rupees per quintal',
    'home.today.checkDisease': 'Worried about a crop disease? Check with a photo',
    'home.today.cropLink': 'Open {crop}',
    'home.kind.do': 'Do',
    'home.kind.warn': 'Caution',
    'home.kind.info': 'Info',

    'home.quick.title': 'Main services',
    'home.quick.advice': 'Crop advice',
    'home.quick.mandi': 'Mandi prices',
    'home.quick.weather': 'Weather',
    'home.quick.doctor': 'Crop disease',
    'home.quick.soil': 'Soil test',
    'home.quick.schemes': 'Govt. schemes',
    'home.quick.calendar': 'Calendar',
    'home.quick.experts': 'Experts',

    'home.crops.title': 'My crops',
    'home.crops.add': 'Add',
    'home.crops.addAria': 'Add a new crop',
    'home.crops.area': '{n} {unit}',
    'home.crops.noArea': 'Area not added',
    'home.crops.progress': 'Crop progress {pct}%',
    'home.crops.next': 'Next: {task} ({when})',
    'home.crops.overdue': 'Pending: {task} (since {date})',
    'home.crops.noTask': 'No task planned yet',
    'home.crops.emptyTitle': 'No crops added yet',
    'home.crops.emptyBody': 'Add your crop to get daily advice, task reminders and prices made for it.',
    'home.crops.emptyAction': 'Add a new crop',

    'home.mandi.title': "Today's mandi",
    'home.mandi.trend.up': 'Up',
    'home.mandi.trend.down': 'Down',
    'home.mandi.trend.stable': 'Steady',
    'home.mandi.errorTitle': 'Could not load mandi prices',
    'home.mandi.emptyTitle': 'No prices yet',
    'home.mandi.emptyBody': 'Fresh mandi prices for your area are not available right now. Try another crop or mandi in the Mandi tab.',
    'home.mandi.open': 'See mandi prices',
    'home.mandi.sources': 'Sources: {list}',
    'home.mandi.refreshFailed': 'Could not get fresh prices; showing the last ones.',

    'home.tasks.title': 'Upcoming tasks',
    'home.tasks.markDone': 'Mark done: {task}',
    'home.tasks.doneToast': 'Task done',
    'home.tasks.undo': 'Undo',
    'home.tasks.general': 'General task',
    'home.tasks.emptyTitle': 'No tasks this week',
    'home.tasks.emptyBody': 'Nothing is planned for the next 7 days. Open the calendar or add your own task.',
    'home.tasks.emptyNoCrops': 'Add a crop and every task from sowing to harvest will appear here.',
    'home.tasks.open': 'Open calendar',

    'home.voice.title': 'Ask by voice',
    'home.voice.body': 'Ask in your own language — no typing needed',
    'home.voice.example': 'For example: "Why are my wheat leaves turning yellow?"',
    'home.voice.aria': 'Ask by voice — ask in your own language',
  },
});
