// Strings for expert consultation (prefix "experts."). Errors come from services/community.ts.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'experts.title': 'विशेषज्ञ से सलाह',
    'experts.subtitle': 'कृषि विशेषज्ञ से सीधी बात',

    // Coming-soon preview
    'experts.soon.title': 'विशेषज्ञ सलाह जल्द आ रही है',
    'experts.soon.body': 'जांचे हुए कृषि विशेषज्ञों से चैट, फ़ोन या वीडियो पर अपनी फसल के लिए सीधी सलाह ले सकेंगे।',
    'experts.soon.features': 'क्या-क्या मिलेगा',
    'experts.soon.f.chat': 'चैट पर सलाह',
    'experts.soon.f.chatDesc': 'फसल की फोटो भेजकर लिखित सलाह',
    'experts.soon.f.voice': 'फ़ोन पर बात',
    'experts.soon.f.voiceDesc': 'अपनी भाषा में सीधी बात',
    'experts.soon.f.video': 'वीडियो कॉल',
    'experts.soon.f.videoDesc': 'खेत दिखाकर सलाह',
    'experts.soon.f.fee': 'फीस पहले दिखेगी',
    'experts.soon.f.feeDesc': 'बुकिंग से पहले पूरी फीस साफ़ दिखेगी — कोई छुपा चार्ज नहीं',
    'experts.soon.f.verified': 'जांचे हुए विशेषज्ञ',
    'experts.soon.f.verifiedDesc': 'पढ़ाई, अनुभव और भाषा की जानकारी हर विशेषज्ञ के साथ',
    'experts.soon.specsTitle': 'इन विषयों पर सलाह की योजना है',
    'experts.spec.pests': 'फसल रोग और कीट',
    'experts.spec.soil': 'मिट्टी और खाद',
    'experts.spec.horticulture': 'बागवानी और सब्ज़ी',
    'experts.spec.irrigation': 'सिंचाई',
    'experts.spec.organic': 'जैविक व प्राकृतिक खेती',
    'experts.spec.livestock': 'पशुपालन',

    // Full UI (behind FEATURES.experts)
    'experts.filter': 'विषय चुनें',
    'experts.filter.all': 'सभी विषय',
    'experts.listAria': 'उपलब्ध विशेषज्ञ',
    'experts.experience': '{n} साल का अनुभव',
    'experts.languages': 'भाषा: {list}',
    'experts.availability': 'उपलब्ध: {text}',
    'experts.fee': '{fee} प्रति परामर्श',
    'experts.free': 'मुफ़्त परामर्श',
    'experts.verified': 'सत्यापित विशेषज्ञ',
    'experts.mode.chat': 'चैट',
    'experts.mode.voice': 'कॉल',
    'experts.mode.video': 'वीडियो',
    'experts.modeAria': '{name} से {mode} परामर्श',
    'experts.empty': 'अभी कोई विशेषज्ञ उपलब्ध नहीं',
    'experts.emptyBody': 'थोड़ी देर बाद देखें, या अभी AI किसान मित्र से पूछें।',
    'experts.emptyAction': 'AI से पूछें',
    'experts.book.title': '{mode} परामर्श',
    'experts.book.with': '{name} • {spec}',
    'experts.book.fee': 'परामर्श फीस',
    'experts.book.feeNote': 'बुकिंग पक्की करने से पहले फीस दोबारा दिखाई जाएगी। अभी कोई पैसा नहीं कटेगा।',
    'experts.book.question': 'अपनी समस्या लिखें',
    'experts.book.questionPlaceholder': 'जैसे: धान की पत्तियों पर भूरे धब्बे हैं',
    'experts.book.send': 'अनुरोध भेजें',
    'experts.book.sent': 'आपका अनुरोध भेज दिया गया।',
    'experts.book.reviewTitle': 'आपका अनुरोध',
    'experts.book.confirmedFee': 'पक्की फीस',
    'experts.book.feeChangedTitle': 'फीस बदल गई है',
    'experts.book.feeChanged': 'सूची में {listed} लिखी थी, पर विशेषज्ञ की पक्की फीस {fee} है। सहमत न हों तो आगे भुगतान न करें।',
    'experts.book.status.requested': 'अनुरोध भेज दिया गया है। विशेषज्ञ के समय तय करने पर आपको बताया जाएगा।',
    'experts.book.status.confirmed': 'आपका परामर्श पक्का हो गया है।',
    'experts.book.when': 'समय: {date}, {time}',
    'experts.book.noCharge': 'भुगतान से पहले फीस फिर दिखाई जाएगी। आपकी मंज़ूरी के बिना कोई पैसा नहीं कटेगा।',
    'experts.book.done': 'ठीक है',
    'experts.book.confirmedToast': 'परामर्श पक्का हो गया।',
  },
  en: {
    'experts.title': 'Expert advice',
    'experts.subtitle': 'Talk directly to an agriculture expert',

    'experts.soon.title': 'Expert advice is coming soon',
    'experts.soon.body': 'You will be able to get direct advice for your crop from verified agriculture experts over chat, phone or video.',
    'experts.soon.features': 'What you will get',
    'experts.soon.f.chat': 'Advice on chat',
    'experts.soon.f.chatDesc': 'Send crop photos and get written advice',
    'experts.soon.f.voice': 'Phone call',
    'experts.soon.f.voiceDesc': 'Talk directly in your language',
    'experts.soon.f.video': 'Video call',
    'experts.soon.f.videoDesc': 'Show your field and get advice',
    'experts.soon.f.fee': 'Fee shown first',
    'experts.soon.f.feeDesc': 'The full fee is shown before booking — no hidden charges',
    'experts.soon.f.verified': 'Verified experts',
    'experts.soon.f.verifiedDesc': 'Qualifications, experience and languages shown for every expert',
    'experts.soon.specsTitle': 'Planned topics',
    'experts.spec.pests': 'Crop diseases and pests',
    'experts.spec.soil': 'Soil and fertiliser',
    'experts.spec.horticulture': 'Horticulture and vegetables',
    'experts.spec.irrigation': 'Irrigation',
    'experts.spec.organic': 'Organic and natural farming',
    'experts.spec.livestock': 'Livestock',

    'experts.filter': 'Choose a topic',
    'experts.filter.all': 'All topics',
    'experts.listAria': 'Available experts',
    'experts.experience': '{n} years of experience',
    'experts.languages': 'Languages: {list}',
    'experts.availability': 'Available: {text}',
    'experts.fee': '{fee} per consultation',
    'experts.free': 'Free consultation',
    'experts.verified': 'Verified expert',
    'experts.mode.chat': 'Chat',
    'experts.mode.voice': 'Call',
    'experts.mode.video': 'Video',
    'experts.modeAria': '{mode} consultation with {name}',
    'experts.empty': 'No expert available right now',
    'experts.emptyBody': 'Check again later, or ask AI Kisan Mitra now.',
    'experts.emptyAction': 'Ask the AI',
    'experts.book.title': '{mode} consultation',
    'experts.book.with': '{name} • {spec}',
    'experts.book.fee': 'Consultation fee',
    'experts.book.feeNote': 'The fee will be shown again before the booking is confirmed. Nothing is charged now.',
    'experts.book.question': 'Describe your problem',
    'experts.book.questionPlaceholder': 'e.g. Brown spots on paddy leaves',
    'experts.book.send': 'Send request',
    'experts.book.sent': 'Your request has been sent.',
    'experts.book.reviewTitle': 'Your request',
    'experts.book.confirmedFee': 'Confirmed fee',
    'experts.book.feeChangedTitle': 'The fee has changed',
    'experts.book.feeChanged': 'The list showed {listed}, but the confirmed fee is {fee}. If you do not agree, do not pay.',
    'experts.book.status.requested': 'Your request has been sent. You will be told when the expert sets a time.',
    'experts.book.status.confirmed': 'Your consultation is confirmed.',
    'experts.book.when': 'Time: {date}, {time}',
    'experts.book.noCharge': 'The fee will be shown again before payment. Nothing is charged without your approval.',
    'experts.book.done': 'OK',
    'experts.book.confirmedToast': 'Consultation confirmed.',
  },
});
