// Strings for the notification center ("सूचनाएं").
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'notifications.title': 'सूचनाएं',
    'notifications.unreadOne': '1 नई सूचना',
    'notifications.unreadMany': '{n} नई सूचनाएं',
    'notifications.allRead': 'सभी सूचनाएं पढ़ ली गई हैं',
    'notifications.markAllRead': 'सभी पढ़ा हुआ',
    'notifications.markAllReadDone': 'सभी सूचनाएं पढ़ ली गईं',
    'notifications.settings': 'सूचना सेटिंग',
    'notifications.filter': 'सूचना का प्रकार',
    'notifications.list': 'सूचनाओं की सूची',
    'notifications.cat.all': 'सभी',
    'notifications.cat.weather': 'मौसम',
    'notifications.cat.crop': 'फसल',
    'notifications.cat.mandi': 'मंडी',
    'notifications.cat.government': 'सरकारी',
    'notifications.cat.reminder': 'रिमाइंडर',
    'notifications.cat.ai': 'AI',
    'notifications.earlier': 'इससे पहले',
    'notifications.urgent': 'ज़रूरी',
    'notifications.important': 'ध्यान दें',
    'notifications.new': 'नई',
    'notifications.more': 'और विकल्प',
    'notifications.open': 'खोलें',
    'notifications.markRead': 'पढ़ा हुआ करें',
    'notifications.deleted': 'सूचना हटा दी गई',
    'notifications.undo': 'वापस लाएं',
    'notifications.clearAll': 'सभी हटाएं',
    'notifications.clearAllTitle': 'सभी सूचनाएं हटाएं?',
    'notifications.clearAllBody': 'आपकी सभी {n} सूचनाएं हट जाएंगी।',
    'notifications.clearAllBodyOne': 'यह 1 सूचना हट जाएगी।',
    'notifications.cleared': 'सभी सूचनाएं हटा दी गईं',
    'notifications.received': 'मिली: {time}',
    'notifications.infoOnly': 'यह सूचना सिर्फ़ जानकारी के लिए है।',
    'notifications.hoursAgo': '{n} घंटे पहले',
    'notifications.daysAgo': '{n} दिन पहले',
    'notifications.empty.title': 'अभी कोई सूचना नहीं है',
    'notifications.empty.body': 'मौसम की चेतावनी, मंडी भाव में बदलाव, खेती के काम और सरकारी योजनाओं की ख़बर यहां मिलेगी।',
    'notifications.empty.action': 'सूचना सेटिंग देखें',
    'notifications.emptyFilter.title': 'इस प्रकार की कोई सूचना नहीं',
    'notifications.emptyFilter.body': 'दूसरा प्रकार चुनें या सभी सूचनाएं देखें।',
    'notifications.emptyFilter.action': 'सभी सूचनाएं देखें',
    'notifications.off.title': 'सूचनाएं बंद हैं',
    'notifications.off.body': 'मौसम की चेतावनी और मंडी भाव की ख़बर पाने के लिए सेटिंग में सूचनाएं चालू करें।',
    'notifications.off.action': 'सेटिंग खोलें',
  },
  en: {
    'notifications.title': 'Notifications',
    'notifications.unreadOne': '1 new notification',
    'notifications.unreadMany': '{n} new notifications',
    'notifications.allRead': 'All caught up',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.markAllReadDone': 'All notifications marked as read',
    'notifications.settings': 'Notification settings',
    'notifications.filter': 'Notification type',
    'notifications.list': 'Notification list',
    'notifications.cat.all': 'All',
    'notifications.cat.weather': 'Weather',
    'notifications.cat.crop': 'Crop',
    'notifications.cat.mandi': 'Mandi',
    'notifications.cat.government': 'Government',
    'notifications.cat.reminder': 'Reminders',
    'notifications.cat.ai': 'AI',
    'notifications.earlier': 'Earlier',
    'notifications.urgent': 'Urgent',
    'notifications.important': 'Important',
    'notifications.new': 'New',
    'notifications.more': 'More options',
    'notifications.open': 'Open',
    'notifications.markRead': 'Mark as read',
    'notifications.deleted': 'Notification deleted',
    'notifications.undo': 'Undo',
    'notifications.clearAll': 'Delete all',
    'notifications.clearAllTitle': 'Delete all notifications?',
    'notifications.clearAllBody': 'All {n} notifications will be removed.',
    'notifications.clearAllBodyOne': 'This 1 notification will be removed.',
    'notifications.cleared': 'All notifications deleted',
    'notifications.received': 'Received: {time}',
    'notifications.infoOnly': 'This notification is for your information.',
    'notifications.hoursAgo': '{n} h ago',
    'notifications.daysAgo': '{n} days ago',
    'notifications.empty.title': 'No notifications yet',
    'notifications.empty.body': 'Weather warnings, mandi price changes, farm tasks and scheme news will appear here.',
    'notifications.empty.action': 'Notification settings',
    'notifications.emptyFilter.title': 'No notifications of this type',
    'notifications.emptyFilter.body': 'Pick another type or see all notifications.',
    'notifications.emptyFilter.action': 'See all notifications',
    'notifications.off.title': 'Notifications are off',
    'notifications.off.body': 'Turn notifications on in Settings to get weather warnings and mandi price news.',
    'notifications.off.action': 'Open settings',
  },
});
