// Strings for the farm money module (खेती हिसाब): HisabScreen and HisabEntryScreen.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'hisab.title': 'खेती हिसाब',
    'hisab.subtitle': 'खर्च और आय एक जगह',
    'hisab.calculators': 'खेती कैलकुलेटर',

    'hisab.tab.label': 'हिसाब का हिस्सा चुनें',
    'hisab.tab.expense': 'खर्च',
    'hisab.tab.income': 'आय',
    'hisab.tab.total': 'कुल',

    'hisab.filter.label': 'हिसाब छांटें',
    'hisab.period.title': 'समय चुनें',
    'hisab.period.seasonNamed': 'यह सीजन ({season})',
    'hisab.period.prevNamed': 'पिछला सीजन ({season})',
    'hisab.period.seasonDesc': '{from} से {to} तक की एंट्री, और इस सीजन की फसलों का पूरा हिसाब',
    'hisab.period.year': 'इस साल',
    'hisab.period.yearDesc': '1 जनवरी {year} से अब तक',
    'hisab.period.all': 'सभी',
    'hisab.period.allDesc': 'शुरू से अब तक का पूरा हिसाब',
    'hisab.crop.title': 'फसल चुनें',
    'hisab.crop.all': 'सभी फसलें',
    'hisab.crop.allDesc': 'बिना फसल वाली एंट्री भी',
    'hisab.crop.noCrops': 'फसल के हिसाब से देखने के लिए "मेरी फसलें" में फसल जोड़ें।',
    'hisab.crop.removed': 'हटाई गई फसल',
    'hisab.crop.addCrop': 'फसल जोड़ें',

    'hisab.stat.expense': 'कुल खर्च',
    'hisab.stat.income': 'कुल आय',
    'hisab.stat.profit': 'अनुमानित लाभ',
    'hisab.stat.loss': 'अनुमानित घाटा',
    'hisab.stat.perAcre': 'प्रति एकड़ लाभ',
    'hisab.stat.perAcreLoss': 'प्रति एकड़ घाटा',
    'hisab.stat.perAcreBasis': '{area} एकड़ के हिसाब से',
    'hisab.stat.perAcreUnknown': 'प्रति एकड़ देखने के लिए फसल में ज़मीन (रकबा) लिखें',
    'hisab.stat.profitNote': 'यह आपकी लिखी एंट्री से निकला है। जो खर्च या आय नहीं लिखी, वह इसमें नहीं है।',

    'hisab.chart.category': 'किस काम में कितना खर्च',
    'hisab.chart.categorySub': 'खर्च, रुपये में',
    'hisab.chart.categoryTitle': 'खर्च का बंटवारा',
    'hisab.chart.top': 'सबसे ज़्यादा खर्च: {category} — {amount} ({pct}%)',
    'hisab.chart.months': 'महीने के हिसाब से',
    'hisab.chart.monthsIncome': 'महीने के हिसाब से आय',
    'hisab.chart.monthsTitle': 'हर महीने की आय और खर्च',
    'hisab.chart.monthsIncomeTitle': 'हर महीने की आय',
    'hisab.chart.range': '{from} से {to}',

    'hisab.list.expenses': 'खर्च की एंट्री',
    'hisab.list.incomes': 'आय की एंट्री',
    'hisab.list.all': 'सभी एंट्री',
    'hisab.list.more': 'और {n} एंट्री दिखाएं',
    'hisab.list.dayTotal': 'दिन का कुल',
    'hisab.row.expenseAria': '{category}, खर्च {amount}',
    'hisab.row.incomeAria': '{category}, आय {amount}',
    'hisab.row.qty': '{qty} क्विंटल',

    'hisab.addExpense': '+ खर्च जोड़ें',
    'hisab.addIncome': '+ आय जोड़ें',

    'hisab.empty.title': 'अभी कोई हिसाब नहीं लिखा',
    'hisab.empty.body': 'बीज, खाद, मजदूरी जैसे खर्च और फसल बेचने की आय लिखें। हम कुल खर्च, आय और लाभ अपने-आप जोड़ देंगे।',
    'hisab.empty.filteredTitle': 'चुने गए समय में कोई एंट्री नहीं',
    'hisab.empty.filteredExpense': 'चुने गए समय और फसल में कोई खर्च नहीं लिखा है।',
    'hisab.empty.filteredIncome': 'चुने गए समय और फसल में कोई आय नहीं लिखी है।',
    'hisab.empty.filteredAll': 'चुने गए समय और फसल में कोई एंट्री नहीं है।',
    'hisab.empty.showAll': 'पूरा हिसाब देखें',

    // Categories
    'hisab.cat.seed': 'बीज',
    'hisab.cat.fertilizer': 'खाद',
    'hisab.cat.pesticide': 'कीटनाशक',
    'hisab.cat.labour': 'मजदूरी',
    'hisab.cat.irrigation': 'सिंचाई',
    'hisab.cat.machine': 'मशीन',
    'hisab.cat.diesel': 'डीज़ल',
    'hisab.cat.other': 'अन्य',
    'hisab.catShort.pesticide': 'दवा',
    'hisab.catDesc.seed': 'बीज, पौध',
    'hisab.catDesc.fertilizer': 'यूरिया, DAP, गोबर खाद',
    'hisab.catDesc.pesticide': 'कीट, रोग, खरपतवार दवा',
    'hisab.catDesc.labour': 'दिहाड़ी, कटाई',
    'hisab.catDesc.irrigation': 'पानी, बिजली बिल',
    'hisab.catDesc.machine': 'ट्रैक्टर, थ्रेशर किराया',
    'hisab.catDesc.diesel': 'पंप, ट्रैक्टर',
    'hisab.catDesc.other': 'ढुलाई, बोरी आदि',
    'hisab.inc.crop-sale': 'फसल बिक्री',
    'hisab.inc.mandi-sale': 'मंडी बिक्री',
    'hisab.inc.other': 'अन्य आय',
    'hisab.incDesc.crop-sale': 'व्यापारी या गांव में',
    'hisab.incDesc.mandi-sale': 'मंडी या सरकारी खरीद',
    'hisab.incDesc.other': 'भूसा, किराया, सहायता',

    // Entry screen
    'hisab.entry.addExpense': 'खर्च जोड़ें',
    'hisab.entry.addIncome': 'आय जोड़ें',
    'hisab.entry.editExpense': 'खर्च बदलें',
    'hisab.entry.editIncome': 'आय बदलें',
    'hisab.entry.subtitle': 'खेती हिसाब',
    'hisab.entry.category': 'किस चीज़ का खर्च है?',
    'hisab.entry.incomeCategory': 'आय कहां से हुई?',
    'hisab.entry.categoryHint': 'जिस काम या चीज़ पर पैसा लगा, उसे चुनें',
    'hisab.entry.amount': 'रकम',
    'hisab.entry.amountHint': 'पूरी रकम रुपये में लिखें',
    'hisab.entry.amountError': 'रकम लिखें (0 से ज़्यादा)',
    'hisab.entry.amountTooBig': 'रकम बहुत बड़ी है, एक बार जांच लें',
    'hisab.entry.date': 'तारीख',
    'hisab.entry.dateError': 'सही तारीख चुनें (आज या उससे पहले की)',
    'hisab.entry.crop': 'फसल',
    'hisab.entry.cropNone': 'किसी एक फसल का नहीं',
    'hisab.entry.cropHint': 'फसल चुनने से प्रति एकड़ लाभ निकल पाएगा',
    'hisab.entry.noCropsHint': 'अभी आपकी कोई फसल नहीं जुड़ी है। फसल और उसकी ज़मीन जोड़ेंगे तो हर एंट्री उस फसल से जुड़ सकेगी और प्रति एकड़ लाभ भी दिखेगा।',
    'hisab.entry.qty': 'कितना बेचा',
    'hisab.entry.rate': 'भाव',
    'hisab.entry.qtyRateHint': 'मात्रा और भाव लिखेंगे तो रकम अपने-आप भर जाएगी',
    'hisab.entry.qtyRateCalc': '{qty} क्विंटल × {rate} = {amount}',
    'hisab.entry.useCalc': 'यह रकम भरें',
    'hisab.entry.note': 'नोट',
    'hisab.entry.notePlaceholder': 'जैसे: 2 बोरी DAP, रामू की दुकान से',
    'hisab.entry.save': 'सेव करें',
    'hisab.entry.saved': 'हिसाब में जुड़ गया',
    'hisab.entry.updated': 'बदलाव सेव हो गया',
    'hisab.entry.deleteBody': 'यह एंट्री हिसाब से हट जाएगी।',
    'hisab.entry.deleted': 'एंट्री हटा दी गई',
    'hisab.entry.undo': 'वापस लाएं',
    'hisab.entry.notFound': 'यह एंट्री नहीं मिली',
    'hisab.entry.notFoundBody': 'शायद यह पहले ही हटा दी गई है।',
    'hisab.entry.backToHisab': 'हिसाब पर जाएं',
    'hisab.entry.fixErrors': 'लाल रंग में दिखी जानकारी ठीक करें',
  },
  en: {
    'hisab.title': 'Farm accounts',
    'hisab.subtitle': 'Expenses and income in one place',
    'hisab.calculators': 'Farm calculators',

    'hisab.tab.label': 'Choose a view',
    'hisab.tab.expense': 'Expenses',
    'hisab.tab.income': 'Income',
    'hisab.tab.total': 'Total',

    'hisab.filter.label': 'Filter accounts',
    'hisab.period.title': 'Choose a period',
    'hisab.period.seasonNamed': 'This season ({season})',
    'hisab.period.prevNamed': 'Last season ({season})',
    'hisab.period.seasonDesc': 'Entries from {from} to {to}, plus everything for this season’s crops',
    'hisab.period.year': 'This year',
    'hisab.period.yearDesc': '1 January {year} until today',
    'hisab.period.all': 'All',
    'hisab.period.allDesc': 'Everything from the start',
    'hisab.crop.title': 'Choose a crop',
    'hisab.crop.all': 'All crops',
    'hisab.crop.allDesc': 'Includes entries without a crop',
    'hisab.crop.noCrops': 'Add crops in "My crops" to see accounts per crop.',
    'hisab.crop.removed': 'Removed crop',
    'hisab.crop.addCrop': 'Add crop',

    'hisab.stat.expense': 'Total expenses',
    'hisab.stat.income': 'Total income',
    'hisab.stat.profit': 'Estimated profit',
    'hisab.stat.loss': 'Estimated loss',
    'hisab.stat.perAcre': 'Profit per acre',
    'hisab.stat.perAcreLoss': 'Loss per acre',
    'hisab.stat.perAcreBasis': 'Based on {area} acres',
    'hisab.stat.perAcreUnknown': 'Add the crop area to see the per-acre figure',
    'hisab.stat.profitNote': 'Worked out from your entries. Anything you have not entered is not included.',

    'hisab.chart.category': 'Where the money went',
    'hisab.chart.categorySub': 'Expenses, in ₹',
    'hisab.chart.categoryTitle': 'Expenses by category',
    'hisab.chart.top': 'Biggest expense: {category} — {amount} ({pct}%)',
    'hisab.chart.months': 'Month by month',
    'hisab.chart.monthsIncome': 'Income by month',
    'hisab.chart.monthsTitle': 'Income and expenses per month',
    'hisab.chart.monthsIncomeTitle': 'Income per month',
    'hisab.chart.range': '{from} to {to}',

    'hisab.list.expenses': 'Expense entries',
    'hisab.list.incomes': 'Income entries',
    'hisab.list.all': 'All entries',
    'hisab.list.more': 'Show {n} more',
    'hisab.list.dayTotal': 'Day total',
    'hisab.row.expenseAria': '{category}, expense {amount}',
    'hisab.row.incomeAria': '{category}, income {amount}',
    'hisab.row.qty': '{qty} quintal',

    'hisab.addExpense': '+ Add expense',
    'hisab.addIncome': '+ Add income',

    'hisab.empty.title': 'No accounts yet',
    'hisab.empty.body': 'Note expenses like seed, fertilizer and labour, and income from selling your crop. We add up the totals and profit for you.',
    'hisab.empty.filteredTitle': 'No entries for the chosen period',
    'hisab.empty.filteredExpense': 'No expenses for the chosen period and crop.',
    'hisab.empty.filteredIncome': 'No income for the chosen period and crop.',
    'hisab.empty.filteredAll': 'No entries for the chosen period and crop.',
    'hisab.empty.showAll': 'Show everything',

    'hisab.cat.seed': 'Seed',
    'hisab.cat.fertilizer': 'Fertilizer',
    'hisab.cat.pesticide': 'Pesticide',
    'hisab.cat.labour': 'Labour',
    'hisab.cat.irrigation': 'Irrigation',
    'hisab.cat.machine': 'Machinery',
    'hisab.cat.diesel': 'Diesel',
    'hisab.cat.other': 'Other',
    'hisab.catShort.pesticide': 'Spray',
    'hisab.catDesc.seed': 'Seed, seedlings',
    'hisab.catDesc.fertilizer': 'Urea, DAP, manure',
    'hisab.catDesc.pesticide': 'Insect, disease, weed sprays',
    'hisab.catDesc.labour': 'Daily wages, harvest',
    'hisab.catDesc.irrigation': 'Water, power bill',
    'hisab.catDesc.machine': 'Tractor, thresher hire',
    'hisab.catDesc.diesel': 'Pump, tractor',
    'hisab.catDesc.other': 'Transport, bags…',
    'hisab.inc.crop-sale': 'Crop sale',
    'hisab.inc.mandi-sale': 'Mandi sale',
    'hisab.inc.other': 'Other income',
    'hisab.incDesc.crop-sale': 'To a trader or in the village',
    'hisab.incDesc.mandi-sale': 'Mandi or government purchase',
    'hisab.incDesc.other': 'Straw, rent, support',


    'hisab.entry.addExpense': 'Add expense',
    'hisab.entry.addIncome': 'Add income',
    'hisab.entry.editExpense': 'Edit expense',
    'hisab.entry.editIncome': 'Edit income',
    'hisab.entry.subtitle': 'Farm accounts',
    'hisab.entry.category': 'What was it for?',
    'hisab.entry.incomeCategory': 'Where did the income come from?',
    'hisab.entry.categoryHint': 'Pick what the money was spent on',
    'hisab.entry.amount': 'Amount',
    'hisab.entry.amountHint': 'The full amount in rupees',
    'hisab.entry.amountError': 'Enter an amount (more than 0)',
    'hisab.entry.amountTooBig': 'This amount looks too large, please check',
    'hisab.entry.date': 'Date',
    'hisab.entry.dateError': 'Choose a valid date (today or earlier)',
    'hisab.entry.crop': 'Crop',
    'hisab.entry.cropNone': 'Not for one crop',
    'hisab.entry.cropHint': 'Choosing a crop lets us work out profit per acre',
    'hisab.entry.noCropsHint': 'You have not added any crops yet. Add a crop with its land to link entries to it and see profit per acre.',
    'hisab.entry.qty': 'Quantity sold',
    'hisab.entry.rate': 'Price',
    'hisab.entry.qtyRateHint': 'Enter quantity and price to fill the amount automatically',
    'hisab.entry.qtyRateCalc': '{qty} quintal × {rate} = {amount}',
    'hisab.entry.useCalc': 'Use this amount',
    'hisab.entry.note': 'Note',
    'hisab.entry.notePlaceholder': 'e.g. 2 bags of DAP from Ramu’s shop',
    'hisab.entry.save': 'Save',
    'hisab.entry.saved': 'Added to your accounts',
    'hisab.entry.updated': 'Changes saved',
    'hisab.entry.deleteBody': 'This entry will be removed from your accounts.',
    'hisab.entry.deleted': 'Entry deleted',
    'hisab.entry.undo': 'Undo',
    'hisab.entry.notFound': 'Entry not found',
    'hisab.entry.notFoundBody': 'It may already have been deleted.',
    'hisab.entry.backToHisab': 'Go to accounts',
    'hisab.entry.fixErrors': 'Please fix the fields marked in red',
  },
});
