// Strings for the first-run questionnaire (spec §20). Prefix "onboarding.".
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'onboarding.stepOf': 'चरण {n} / {total}',
    'onboarding.readyTitle': 'सब तैयार है',

    'onboarding.name.q': 'आपका नाम क्या है?',
    'onboarding.name.help': 'किसान मित्र आपको इसी नाम से बुलाएगा।',
    'onboarding.name.label': 'आपका नाम',
    'onboarding.name.placeholder': 'जैसे: रामलाल यादव',
    'onboarding.name.voice': 'नाम बोलकर लिखें',
    'onboarding.name.error': 'अपना नाम लिखें, या ऊपर "छोड़ें" दबाएं।',

    'onboarding.place.q': 'आपका खेत कहां है?',
    'onboarding.place.help': 'इससे आपके इलाके का मौसम, मंडी भाव और सलाह दिखेगी।',
    'onboarding.place.detect': 'मेरी जगह अपने-आप पता करें',
    'onboarding.place.search': 'जगह खोजें या सूची से चुनें',
    'onboarding.place.chosen': 'आपकी जगह',
    'onboarding.place.change': 'जगह बदलें',
    'onboarding.place.none': 'अभी कोई जगह नहीं चुनी गई',
    'onboarding.place.noneHelp': 'GPS से पता करें, या अपना ज़िला खोजकर चुनें।',
    'onboarding.place.typed': 'आपने यह जगह लिखी थी',
    'onboarding.place.typedHelp': 'मौसम और मंडी भाव के लिए नीचे से जगह खोजकर पक्का करें।',
    'onboarding.place.suggestHelp': 'क्या यही आपकी जगह है? पक्का करने के लिए नीचे दबाएं।',
    'onboarding.place.confirm': 'हां, {place} सही है',
    'onboarding.place.sheet': 'अपने खेत की जगह चुनें',
    'onboarding.place.error': 'अपनी जगह चुनें, या ऊपर "छोड़ें" दबाएं।',

    'onboarding.land.q': 'आपकी जमीन कितनी है?',
    'onboarding.land.help': 'खेती की कुल जमीन बताएं। अंदाज़ा भी चलेगा।',
    'onboarding.land.label': 'कुल जमीन',
    'onboarding.land.unit': 'जमीन का माप',
    'onboarding.land.approx': 'लगभग {n} एकड़',
    'onboarding.land.bigha': 'आपके इलाके का बीघा',
    'onboarding.land.bighaHint': 'बीघा का माप हर राज्य में अलग होता है। इसे बाद में सेटिंग में भी बदल सकते हैं।',
    'onboarding.land.error': 'जमीन लिखें (जैसे 2 या 2.5), या ऊपर "छोड़ें" दबाएं।',

    'onboarding.crops.q': 'आप कौन-कौन सी फसल उगाते हैं?',
    'onboarding.crops.help': 'एक से ज़्यादा फसल चुन सकते हैं।',
    'onboarding.crops.label': 'फसलें',
    'onboarding.crops.season': '{season} की फसलें',
    'onboarding.crops.others': 'बाकी फसलें',
    'onboarding.crops.results': 'खोज में मिली फसलें',
    'onboarding.crops.search': 'फसल का नाम खोजें…',
    'onboarding.crops.selected': '{n} फसलें चुनी गईं',
    'onboarding.crops.selectedOne': '1 फसल चुनी गई',
    'onboarding.crops.error': 'कम से कम एक फसल चुनें, या ऊपर "छोड़ें" दबाएं।',

    'onboarding.irrigation.q': 'सिंचाई कैसे करते हैं?',
    'onboarding.irrigation.help': 'जो तरीका सबसे ज़्यादा इस्तेमाल करते हैं, वह चुनें।',
    'onboarding.irrigation.label': 'सिंचाई का तरीका',
    'onboarding.irrigation.canal': 'नहर',
    'onboarding.irrigation.tubewell': 'ट्यूबवेल / कुआं',
    'onboarding.irrigation.drip': 'ड्रिप',
    'onboarding.irrigation.sprinkler': 'स्प्रिंकलर (फव्वारा)',
    'onboarding.irrigation.rainfed': 'बारिश पर निर्भर',
    'onboarding.irrigation.pond': 'तालाब',
    'onboarding.irrigation.other': 'अन्य',
    'onboarding.irrigation.error': 'सिंचाई का एक तरीका चुनें, या ऊपर "छोड़ें" दबाएं।',

    'onboarding.soil.q': 'आपकी मिट्टी कैसी है?',
    'onboarding.soil.help': 'पक्का पता न हो तो "पता नहीं" चुनें। मिट्टी जांच से बाद में सही जानकारी मिल जाएगी।',
    'onboarding.soil.label': 'मिट्टी का प्रकार',
    'onboarding.soil.alluvial': 'जलोढ़ (कछारी)',
    'onboarding.soil.alluvial.hint': 'नदियों के मैदान की उपजाऊ मिट्टी, जैसे गंगा-यमुना का इलाका',
    'onboarding.soil.loamy': 'दोमट',
    'onboarding.soil.loamy.hint': 'न ज़्यादा चिकनी, न ज़्यादा रेतीली; ज़्यादातर फसलों के लिए अच्छी',
    'onboarding.soil.black': 'काली',
    'onboarding.soil.black.hint': 'पानी देर तक रोकती है; कपास और सोयाबीन के इलाकों में आम',
    'onboarding.soil.red': 'लाल',
    'onboarding.soil.red.hint': 'लाल-भूरी, हल्की मिट्टी; पठारी इलाकों में आम',
    'onboarding.soil.sandy': 'रेतीली',
    'onboarding.soil.sandy.hint': 'हल्की, पानी जल्दी नीचे चला जाता है; सूखे इलाकों में आम',
    'onboarding.soil.clay': 'चिकनी (मटियार)',
    'onboarding.soil.clay.hint': 'भारी, गीली होने पर चिपचिपी; पानी देर तक भरा रहता है',
    'onboarding.soil.unknown': 'पता नहीं',
    'onboarding.soil.unknown.hint': 'कोई बात नहीं, बाद में भी बता सकते हैं',
    'onboarding.soil.error': 'मिट्टी का प्रकार चुनें ("पता नहीं" भी चुन सकते हैं)।',

    'onboarding.language.q': 'ऐप किस भाषा में चलाना है?',
    'onboarding.language.help': 'भाषा चुनते ही ऐप बदल जाएगा। AI के जवाब भी इसी भाषा में आएंगे।',
    'onboarding.language.label': 'भाषा',
    'onboarding.language.partial': 'कुछ हिस्से हिंदी में',

    'onboarding.notify.q': 'ज़रूरी सूचनाएं समय पर पाएं',
    'onboarding.notify.help': 'किसान मित्र आपको सिर्फ़ काम की बातें बताएगा।',
    'onboarding.notify.list': 'सूचनाओं के फ़ायदे',
    'onboarding.notify.weather': 'मौसम चेतावनी',
    'onboarding.notify.weatherBody': 'तेज़ बारिश, आंधी या पाले से पहले खबर',
    'onboarding.notify.tasks': 'काम की याद',
    'onboarding.notify.tasksBody': 'सिंचाई, खाद और छिड़काव का सही समय',
    'onboarding.notify.settings': 'सूचनाएं आप कभी भी सेटिंग में बंद कर सकते हैं।',
    'onboarding.notify.web': 'ब्राउज़र में ये चेतावनियां और याद ऐप खुला होने पर यहीं दिखेंगी।',
    'onboarding.notify.allow': 'अनुमति दें',
    'onboarding.notify.later': 'बाद में',
    'onboarding.notify.granted': 'सूचनाएं चालू हो गईं',
    'onboarding.notify.denied': 'अनुमति नहीं मिली। फ़ोन की सेटिंग में जाकर कभी भी चालू कर सकते हैं।',

    'onboarding.done.title': 'आपका किसान मित्र तैयार है ✓',
    'onboarding.done.greet': 'बधाई हो, {name} जी!',
    'onboarding.done.greetNoName': 'बधाई हो!',
    'onboarding.done.help': 'अब आपको आपके इलाके और आपकी फसलों के हिसाब से सलाह मिलेगी।',
    'onboarding.done.summary': 'आपकी जानकारी',
    'onboarding.done.editHint': 'कुछ बदलना हो तो उस पर दबाएं।',
    'onboarding.done.name': 'नाम',
    'onboarding.done.place': 'जगह',
    'onboarding.done.land': 'जमीन',
    'onboarding.done.crops': 'फसलें',
    'onboarding.done.notSet': 'नहीं बताया',
    'onboarding.done.confirmPlace': 'पक्का करें',
    'onboarding.done.edit': '{label} बदलें: {value}',
    'onboarding.done.start': 'शुरू करें',

    'onboarding.farmName': 'मेरा खेत',
  },
  en: {
    'onboarding.stepOf': 'Step {n} of {total}',
    'onboarding.readyTitle': 'All set',

    'onboarding.name.q': 'What is your name?',
    'onboarding.name.help': 'Kisan Mitra will call you by this name.',
    'onboarding.name.label': 'Your name',
    'onboarding.name.placeholder': 'e.g. Ramlal Yadav',
    'onboarding.name.voice': 'Say your name',
    'onboarding.name.error': 'Enter your name, or tap "Skip" at the top.',

    'onboarding.place.q': 'Where is your farm?',
    'onboarding.place.help': 'This shows weather, mandi prices and advice for your area.',
    'onboarding.place.detect': 'Find my location',
    'onboarding.place.search': 'Search or pick from the list',
    'onboarding.place.chosen': 'Your place',
    'onboarding.place.change': 'Change place',
    'onboarding.place.none': 'No place chosen yet',
    'onboarding.place.noneHelp': 'Use GPS, or search for your district.',
    'onboarding.place.typed': 'The place you entered',
    'onboarding.place.typedHelp': 'Search for it below to confirm it for weather and mandi prices.',
    'onboarding.place.suggestHelp': 'Is this your place? Tap below to confirm.',
    'onboarding.place.confirm': 'Yes, {place} is right',
    'onboarding.place.sheet': 'Choose your farm location',
    'onboarding.place.error': 'Choose your place, or tap "Skip" at the top.',

    'onboarding.land.q': 'How much land do you have?',
    'onboarding.land.help': 'Total farm land. A rough figure is fine.',
    'onboarding.land.label': 'Total land',
    'onboarding.land.unit': 'Land unit',
    'onboarding.land.approx': 'About {n} acres',
    'onboarding.land.bigha': 'Bigha in your area',
    'onboarding.land.bighaHint': 'A bigha differs from state to state. You can change this later in Settings.',
    'onboarding.land.error': 'Enter your land (e.g. 2 or 2.5), or tap "Skip" at the top.',

    'onboarding.crops.q': 'Which crops do you grow?',
    'onboarding.crops.help': 'You can choose more than one.',
    'onboarding.crops.label': 'Crops',
    'onboarding.crops.season': '{season} crops',
    'onboarding.crops.others': 'Other crops',
    'onboarding.crops.results': 'Crops found',
    'onboarding.crops.search': 'Search crop name…',
    'onboarding.crops.selected': '{n} crops selected',
    'onboarding.crops.selectedOne': '1 crop selected',
    'onboarding.crops.error': 'Choose at least one crop, or tap "Skip" at the top.',

    'onboarding.irrigation.q': 'How do you irrigate?',
    'onboarding.irrigation.help': 'Choose the method you use the most.',
    'onboarding.irrigation.label': 'Irrigation method',
    'onboarding.irrigation.canal': 'Canal',
    'onboarding.irrigation.tubewell': 'Tubewell / well',
    'onboarding.irrigation.drip': 'Drip',
    'onboarding.irrigation.sprinkler': 'Sprinkler',
    'onboarding.irrigation.rainfed': 'Rain-fed',
    'onboarding.irrigation.pond': 'Pond',
    'onboarding.irrigation.other': 'Other',
    'onboarding.irrigation.error': 'Choose an irrigation method, or tap "Skip" at the top.',

    'onboarding.soil.q': 'What is your soil like?',
    'onboarding.soil.help': 'Not sure? Choose "Don\'t know". A soil test will tell you later.',
    'onboarding.soil.label': 'Soil type',
    'onboarding.soil.alluvial': 'Alluvial',
    'onboarding.soil.alluvial.hint': 'Fertile river-plain soil, like the Ganga–Yamuna plains',
    'onboarding.soil.loamy': 'Loamy',
    'onboarding.soil.loamy.hint': 'Neither too sticky nor too sandy; good for most crops',
    'onboarding.soil.black': 'Black',
    'onboarding.soil.black.hint': 'Holds water long; common in cotton and soybean areas',
    'onboarding.soil.red': 'Red',
    'onboarding.soil.red.hint': 'Reddish-brown, light soil; common on plateaus',
    'onboarding.soil.sandy': 'Sandy',
    'onboarding.soil.sandy.hint': 'Light, water drains quickly; common in dry areas',
    'onboarding.soil.clay': 'Clay',
    'onboarding.soil.clay.hint': 'Heavy and sticky when wet; water stands for long',
    'onboarding.soil.unknown': "Don't know",
    'onboarding.soil.unknown.hint': 'No problem, you can tell us later',
    'onboarding.soil.error': 'Choose a soil type ("Don\'t know" is fine).',

    'onboarding.language.q': 'Which language should the app use?',
    'onboarding.language.help': 'The app changes as soon as you pick. AI answers will also come in this language.',
    'onboarding.language.label': 'Language',
    'onboarding.language.partial': 'Some parts in Hindi',

    'onboarding.notify.q': 'Get important alerts on time',
    'onboarding.notify.help': 'Kisan Mitra only tells you what matters for your farm.',
    'onboarding.notify.list': 'Why turn on alerts',
    'onboarding.notify.weather': 'Weather warnings',
    'onboarding.notify.weatherBody': 'Before heavy rain, storms or frost',
    'onboarding.notify.tasks': 'Task reminders',
    'onboarding.notify.tasksBody': 'The right time to irrigate, fertilise and spray',
    'onboarding.notify.settings': 'You can turn alerts off any time in Settings.',
    'onboarding.notify.web': 'In the browser, these alerts and reminders show here while the app is open.',
    'onboarding.notify.allow': 'Allow',
    'onboarding.notify.later': 'Later',
    'onboarding.notify.granted': 'Alerts are on',
    'onboarding.notify.denied': 'Permission was not given. You can turn it on any time in phone settings.',

    'onboarding.done.title': 'Your Kisan Mitra is ready ✓',
    'onboarding.done.greet': 'Congratulations, {name}!',
    'onboarding.done.greetNoName': 'Congratulations!',
    'onboarding.done.help': 'You will now get advice for your area and your crops.',
    'onboarding.done.summary': 'Your details',
    'onboarding.done.editHint': 'Tap anything to change it.',
    'onboarding.done.name': 'Name',
    'onboarding.done.place': 'Place',
    'onboarding.done.land': 'Land',
    'onboarding.done.crops': 'Crops',
    'onboarding.done.notSet': 'Not given',
    'onboarding.done.confirmPlace': 'confirm',
    'onboarding.done.edit': 'Change {label}: {value}',
    'onboarding.done.start': 'Start',

    'onboarding.farmName': 'My farm',
  },
});
