// Strings owned by the UI kit (prefix "ui."). Shared words (retry, close, back…) come from common.*.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'ui.notifications': 'सूचनाएं',
    'ui.badge.count': '{n} नई',
    'ui.badge.new': 'नया',
    'ui.clear': 'साफ़ करें',
    'ui.more': 'और',
    'ui.selected': 'चुना गया',
    'ui.page': 'पेज {n} / {total}',
    'ui.refreshing': 'ताज़ा हो रहा है…',
    'ui.select.placeholder': 'चुनें',
    'ui.number.decrease': 'कम करें',
    'ui.number.increase': 'बढ़ाएं',
    'ui.number.range': '{min} से {max} के बीच लिखें',
    'ui.dialog.ok': 'ठीक है',
    'ui.error.title': 'जानकारी नहीं मिल पाई',
    'ui.error.offlineTitle': 'इंटरनेट नहीं है',
    'ui.voice.start': 'बोलकर लिखें',
    'ui.voice.noSpeech': 'कुछ सुनाई नहीं दिया। दोबारा बोलें।',
    'ui.voice.error': 'आवाज़ पहचानने में दिक्कत हुई। दोबारा कोशिश करें।',
    'ui.trend.up': 'बढ़त',
    'ui.trend.down': 'गिरावट',
    'ui.trend.stable': 'स्थिर',
    'ui.status.good': 'उचित',
    'ui.status.medium': 'मध्यम',
    'ui.status.low': 'कम',
    'ui.status.high': 'ज़्यादा',
    'ui.chart.lineSummary': '{title}: {from} से {to} तक। शुरुआत {first}, अभी {last}। सबसे ज़्यादा {max}, सबसे कम {min}।',
    'ui.chart.trend': 'रुझान: {first} से {last}',
    'ui.weather.clear': 'धूप खिली है',
    'ui.weather.clearNight': 'साफ़ आसमान',
    'ui.weather.partly': 'हल्के बादल',
    'ui.weather.cloudy': 'बादल छाए हैं',
    'ui.weather.fog': 'कोहरा',
    'ui.weather.drizzle': 'हल्की बूंदाबांदी',
    'ui.weather.rain': 'बारिश',
    'ui.weather.heavyRain': 'तेज़ बारिश',
    'ui.weather.showers': 'रुक-रुक कर बौछारें',
    'ui.weather.snow': 'बर्फबारी',
    'ui.weather.thunder': 'आंधी-तूफ़ान',
  },
  en: {
    'ui.notifications': 'Notifications',
    'ui.badge.count': '{n} new',
    'ui.badge.new': 'New',
    'ui.clear': 'Clear',
    'ui.more': 'More',
    'ui.selected': 'Selected',
    'ui.page': 'Page {n} of {total}',
    'ui.refreshing': 'Refreshing…',
    'ui.select.placeholder': 'Select',
    'ui.number.decrease': 'Decrease',
    'ui.number.increase': 'Increase',
    'ui.number.range': 'Enter a value between {min} and {max}',
    'ui.dialog.ok': 'OK',
    'ui.error.title': "Couldn't load this",
    'ui.error.offlineTitle': 'You are offline',
    'ui.voice.start': 'Speak to type',
    'ui.voice.noSpeech': "Didn't catch that. Please speak again.",
    'ui.voice.error': 'Could not recognise your voice. Please try again.',
    'ui.trend.up': 'Up',
    'ui.trend.down': 'Down',
    'ui.trend.stable': 'Stable',
    'ui.status.good': 'Optimal',
    'ui.status.medium': 'Medium',
    'ui.status.low': 'Low',
    'ui.status.high': 'High',
    'ui.chart.lineSummary': '{title}: {from} to {to}. Started at {first}, now {last}. High {max}, low {min}.',
    'ui.chart.trend': 'Trend: {first} to {last}',
    'ui.weather.clear': 'Sunny',
    'ui.weather.clearNight': 'Clear sky',
    'ui.weather.partly': 'Partly cloudy',
    'ui.weather.cloudy': 'Cloudy',
    'ui.weather.fog': 'Fog',
    'ui.weather.drizzle': 'Light drizzle',
    'ui.weather.rain': 'Rain',
    'ui.weather.heavyRain': 'Heavy rain',
    'ui.weather.showers': 'Passing showers',
    'ui.weather.snow': 'Snow',
    'ui.weather.thunder': 'Thunderstorm',
  },
});
