// Strings shared across modules (buttons, states, time words, AI errors, disclaimers).
// Feature modules register their own strings under their own prefix (e.g. "weather.*").
import { registerStrings } from './i18n';

registerStrings({
  hi: {
    'common.today': 'आज',
    'common.tomorrow': 'कल',
    'common.yesterday': 'बीता कल',
    'common.justNow': 'अभी',
    'common.minutesAgo': '{n} मिनट पहले',
    'common.lastUpdated': 'अपडेट: {time}',
    'common.staleData': 'पुरानी जानकारी',
    'common.offline': 'इंटरनेट नहीं है — पिछली सेव जानकारी दिखाई जा रही है',
    'common.retry': 'फिर कोशिश करें',
    'common.refresh': 'ताज़ा करें',
    'common.save': 'सेव करें',
    'common.saved': 'सेव हो गया',
    'common.unsave': 'सेव से हटाएं',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'बदलें',
    'common.add': 'जोड़ें',
    'common.done': 'हो गया',
    'common.next': 'आगे बढ़ें',
    'common.back': 'वापस',
    'common.close': 'बंद करें',
    'common.skip': 'छोड़ें',
    'common.continue': 'जारी रखें',
    'common.seeAll': 'सभी देखें',
    'common.viewDetails': 'विस्तार से देखें',
    'common.loading': 'लोड हो रहा है…',
    'common.search': 'खोजें',
    'common.share': 'शेयर करें',
    'common.copy': 'कॉपी करें',
    'common.copied': 'कॉपी हो गया',
    'common.listen': 'सुनें',
    'common.stop': 'रोकें',
    'common.optional': 'वैकल्पिक',
    'common.required': 'ज़रूरी',
    'common.confirmDelete': 'क्या आप इसे हटाना चाहते हैं?',
    'common.comingSoon': 'जल्द आ रहा है',
    'common.source': 'स्रोत',
    'common.sources': 'विश्वसनीय स्रोत',
    'common.acre': 'एकड़',
    'common.bigha': 'बीघा',
    'common.hectare': 'हेक्टेयर',
    'common.quintal': 'क्विंटल',
    'common.kg': 'किलो',
    'common.perQuintal': '/क्विंटल',
    'common.error.generic': 'कुछ गड़बड़ हो गई। कृपया दोबारा कोशिश करें।',
    'common.error.offline': 'इंटरनेट कनेक्शन नहीं है। कनेक्शन मिलने पर दोबारा कोशिश करें।',
    'common.empty': 'अभी यहां कुछ नहीं है',
    'common.voice.listening': 'सुन रहा हूँ… बोलिए',
    'common.voice.unsupported': 'इस फ़ोन पर आवाज़ से लिखना उपलब्ध नहीं है।',
    'common.voice.denied': 'माइक्रोफ़ोन की अनुमति नहीं मिली।',
    'common.disclaimer.ai': 'यह AI आधारित प्रारंभिक सुझाव है। गंभीर स्थिति में कृषि विशेषज्ञ से सलाह लें।',
    'common.disclaimer.fertilizer': 'यह सामान्य मार्गदर्शन है। मात्रा के लिए अपने मिट्टी जांच कार्ड और स्थानीय कृषि विशेषज्ञ की सलाह मानें।',
    'common.disclaimer.price': 'भाव अनुमानित हैं और इंटरनेट स्रोतों पर आधारित हैं। बेचने से पहले स्थानीय मंडी में पुष्टि करें। भविष्य के भाव की गारंटी नहीं है।',
    'ai.error.not-configured': 'AI सेवा अभी उपलब्ध नहीं है।',
    'ai.error.offline': 'AI से पूछने के लिए इंटरनेट चाहिए।',
    'ai.error.rate-limit': 'बहुत सारे सवाल एक साथ आ गए। थोड़ी देर बाद पूछें।',
    'ai.error.timeout': 'जवाब आने में बहुत देर लगी। दोबारा कोशिश करें।',
    'ai.error.blocked': 'यह सवाल AI नहीं संभाल सकता। कृपया खेती से जुड़ा सवाल पूछें।',
    'ai.error.bad-response': 'AI का जवाब समझ नहीं आया। दोबारा कोशिश करें।',
    'ai.error.network': 'AI सेवा से जुड़ नहीं पाए। दोबारा कोशिश करें।',
  },
  en: {
    'common.today': 'Today',
    'common.tomorrow': 'Tomorrow',
    'common.yesterday': 'Yesterday',
    'common.justNow': 'Just now',
    'common.minutesAgo': '{n} min ago',
    'common.lastUpdated': 'Updated: {time}',
    'common.staleData': 'Old data',
    'common.offline': 'No internet — showing last saved information',
    'common.retry': 'Try again',
    'common.refresh': 'Refresh',
    'common.save': 'Save',
    'common.saved': 'Saved',
    'common.unsave': 'Remove from saved',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.done': 'Done',
    'common.next': 'Next',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.skip': 'Skip',
    'common.continue': 'Continue',
    'common.seeAll': 'See all',
    'common.viewDetails': 'View details',
    'common.loading': 'Loading…',
    'common.search': 'Search',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.copied': 'Copied',
    'common.listen': 'Listen',
    'common.stop': 'Stop',
    'common.optional': 'Optional',
    'common.required': 'Required',
    'common.confirmDelete': 'Do you want to delete this?',
    'common.comingSoon': 'Coming soon',
    'common.source': 'Source',
    'common.sources': 'Trusted sources',
    'common.acre': 'acre',
    'common.bigha': 'bigha',
    'common.hectare': 'hectare',
    'common.quintal': 'quintal',
    'common.kg': 'kg',
    'common.perQuintal': '/quintal',
    'common.error.generic': 'Something went wrong. Please try again.',
    'common.error.offline': 'No internet connection. Try again when you are connected.',
    'common.empty': 'Nothing here yet',
    'common.voice.listening': 'Listening… please speak',
    'common.voice.unsupported': 'Voice typing is not available on this device.',
    'common.voice.denied': 'Microphone permission was not granted.',
    'common.disclaimer.ai': 'This is a preliminary AI-based suggestion. Consult an agriculture expert for serious cases.',
    'common.disclaimer.fertilizer': 'General guidance only. Follow your soil health card and local agronomist for exact doses.',
    'common.disclaimer.price': 'Prices are indicative and based on internet sources. Confirm at your local mandi before selling. Future prices are not guaranteed.',
    'ai.error.not-configured': 'AI service is not available right now.',
    'ai.error.offline': 'You need internet to ask the AI.',
    'ai.error.rate-limit': 'Too many questions at once. Please ask again in a little while.',
    'ai.error.timeout': 'The answer took too long. Please try again.',
    'ai.error.blocked': 'The AI cannot handle this question. Please ask about farming.',
    'ai.error.bad-response': 'Could not understand the AI reply. Please try again.',
    'ai.error.network': 'Could not reach the AI service. Please try again.',
  },
});
