// Strings for the AI module (chat, voice, history). Prefix: "ai." (the AI service's own
// error strings live under "ai.error.*" in lib/common-strings.ts; never reuse that prefix here).
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    // ---- Chat ----
    'ai.chat.title': 'AI किसान मित्र',
    'ai.chat.subtitle': 'आपका निजी कृषि सहायक',
    'ai.chat.history': 'पुरानी बातचीत',
    'ai.chat.new': 'नई बातचीत',
    'ai.chat.assistant': 'किसान मित्र',
    'ai.chat.welcome':
      'नमस्ते! मैं किसान मित्र हूँ, खेती में आपका साथी। फसल की बीमारी, खाद, सिंचाई, मौसम या मंडी भाव, कुछ भी पूछिए। आप फोटो भेजकर या बोलकर भी पूछ सकते हैं।',
    'ai.chat.quickTitle': 'आज क्या मदद करूं?',
    'ai.chat.photoTitle': 'फोटो से सवाल',
    'ai.chat.missing': 'यह बातचीत अब उपलब्ध नहीं है। नया सवाल पूछें।',
    'ai.chat.unanswered': 'इस सवाल का जवाब नहीं मिल पाया।',
    'ai.chat.typing': 'किसान मित्र जवाब लिख रहा है…',
    'ai.chat.errorPast': 'इस सवाल का जवाब उस समय नहीं मिल पाया था।',

    // 2×2 action cards (reference screen 5)
    'ai.card.photo': 'फोटो से पहचान',
    'ai.card.photoDesc': 'फसल का रोग पहचानें',
    'ai.card.voice': 'आवाज़ में पूछें',
    'ai.card.voiceDesc': 'बोलकर सवाल करें',
    'ai.card.advice': 'फसल सलाह',
    'ai.card.adviceDesc': 'आपकी फसलों के लिए',
    'ai.card.market': 'मंडी विश्लेषण',
    'ai.card.marketDesc': 'भाव और बेचने का समय',

    // Suggestion chips
    'ai.suggest.title': 'ये सवाल पूछ सकते हैं',
    'ai.suggest.yellow': '{crop} में पीले पत्ते क्यों?',
    'ai.suggest.fertilizer': '{crop} में खाद कब डालें?',
    'ai.suggest.pest': '{crop} में कीट से बचाव कैसे?',
    'ai.suggest.irrigation': '{crop} में सिंचाई कब करें?',
    'ai.suggest.seed': '{crop} का बीज उपचार कैसे करें?',
    'ai.suggest.sowing': '{crop} की बुवाई का सही तरीका?',
    'ai.suggest.harvest': '{crop} की कटाई कब करें?',
    'ai.suggest.price': '{crop} का मंडी भाव क्या है?',
    'ai.suggest.sowNow': '{season} में अभी क्या बोएं?',
    'ai.suggest.spray': 'इस हफ्ते छिड़काव करूं या नहीं?',

    // Starter questions sent by the action cards (shown as the farmer's own message)
    'ai.starter.advice': 'मेरी फसलें: {crops}। {season} के इस मौसम में अभी इनकी देखभाल के लिए क्या-क्या करूं?',
    'ai.starter.adviceCrop': 'मेरी {crop} की फसल अभी {stage} अवस्था में है। इस समय क्या-क्या करूं?',
    'ai.starter.adviceNoCrops': '{place} में {season} के इस मौसम में कौन सी फसल लगाऊं और अभी क्या तैयारी करूं?',
    'ai.starter.market': '{place} के आसपास की मंडियों में {crops} का भाव कैसा चल रहा है? अभी बेचूं या थोड़ा रुकूं?',
    'ai.starter.marketNoCrops': '{place} के आसपास की मंडियों में आज मुख्य फसलों के भाव क्या हैं?',

    // Crop context
    'ai.crop.note': 'जवाब इसी फसल को ध्यान में रखकर मिलेंगे',
    'ai.crop.meta': '{area} • {stage}',

    // Answer card
    'ai.answer.problem': 'समस्या',
    'ai.answer.causes': 'संभावित कारण',
    'ai.answer.do': 'क्या करें',
    'ai.answer.dont': 'क्या न करें',
    'ai.answer.recheck': 'कब दोबारा जांचें',
    'ai.answer.more': 'और पूछें',
    'ai.answer.followTitle': 'और पूछें',
    'ai.answer.unsaved': 'सेव से हटा दिया',
    'ai.answer.shareTitle': 'किसान मित्र की सलाह',
    'ai.answer.shareFooter': '— किसान मित्र ऐप से',
    'ai.answer.question': 'सवाल',
    'ai.answer.schemeNote': 'योजना की शर्तें और राशि बदलती रहती हैं। आवेदन से पहले सरकारी वेबसाइट या कृषि विभाग से पुष्टि करें।',
    'ai.answer.weatherNote': 'मौसम का अनुमान बदल सकता है। खेत का काम करने से पहले ताज़ा मौसम देख लें।',
    'ai.answer.viaVoice': 'आवाज़ से पूछा',
    'ai.answer.photoAlt': 'आपकी भेजी फोटो',
    'ai.answer.photoDropped': 'जगह बचाने के लिए पुरानी फोटो हटा दी गई',
    'ai.answer.actions': 'जवाब के विकल्प',
    'ai.answer.sources': 'जानकारी के स्रोत (इंटरनेट से)',

    // Composer
    'ai.composer.label': 'अपना सवाल लिखें',
    'ai.composer.placeholder': 'अपना सवाल लिखें…',
    'ai.composer.placeholderPhoto': 'फोटो के बारे में लिखें (ज़रूरी नहीं)…',
    'ai.composer.send': 'सवाल भेजें',
    'ai.composer.photo': 'फसल की फोटो जोड़ें',
    'ai.composer.removePhoto': 'फोटो हटाएं',
    'ai.composer.photoPreview': 'जोड़ी गई फोटो',
    'ai.composer.offline': 'इंटरनेट नहीं है। सवाल पूछने के लिए इंटरनेट चालू करें, पुरानी बातचीत पढ़ सकते हैं।',
    'ai.composer.notConfigured': 'AI सहायक अभी चालू नहीं है।',
    'ai.photo.header': 'फसल की फोटो',
    'ai.photo.camera': 'फोटो लें',
    'ai.photo.gallery': 'गैलरी से चुनें',
    'ai.photo.error': 'फोटो नहीं खुल पाई। कोई दूसरी फोटो चुनें।',

    'ai.notConfigured.title': 'AI सहायक अभी उपलब्ध नहीं है',
    'ai.notConfigured.body':
      'इस ऐप में AI सेवा अभी चालू नहीं की गई है। मौसम, फसल कैलेंडर, हिसाब और सरकारी योजनाओं की जानकारी बिना AI के भी काम करती है।',
    'ai.notConfigured.help': 'सहायता केंद्र',

    // ---- Voice ----
    'ai.voice.title': 'आवाज़ से पूछें',
    'ai.voice.subtitle': 'बोलिए, किसान मित्र सुनकर जवाब देगा',
    'ai.voice.micLabel': 'बोलकर सवाल पूछें',
    'ai.voice.idle': 'बोलने के लिए दबाएं',
    'ai.voice.idleHint': 'जैसे: "धान के पत्ते पीले क्यों हो रहे हैं?"',
    'ai.voice.listening': 'सुन रहा हूँ…',
    'ai.voice.listeningHint': 'अपना सवाल बोलिए, फिर रुक जाइए',
    'ai.voice.thinking': 'सोच रहा हूँ…',
    'ai.voice.thinkingHint': 'आपका जवाब तैयार हो रहा है',
    'ai.voice.answered': 'जवाब सुनिए',
    'ai.voice.answeredHint': 'नया सवाल पूछने के लिए माइक दबाएं',
    'ai.voice.errorTitle': 'जवाब नहीं मिल पाया',
    'ai.voice.stop': 'बोलना रोकें',
    'ai.voice.replay': 'फिर से सुनें',
    'ai.voice.askAgain': 'फिर से पूछें',
    'ai.voice.viewChat': 'पूरी बातचीत देखें',
    'ai.voice.typeInstead': 'लिखकर पूछें',
    'ai.voice.trouble': 'बोलने में दिक्कत हो रही है? आप लिखकर भी पूछ सकते हैं।',
    'ai.voice.unsupported': 'इस फ़ोन पर आवाज़ से पूछना उपलब्ध नहीं है। नीचे लिखकर पूछें, जवाब बोलकर सुनाया जाएगा।',
    'ai.voice.inputLabel': 'आपका सवाल',
    'ai.voice.inputPlaceholder': 'जैसे: गेहूं में खाद कब डालें?',
    'ai.voice.ask': 'पूछें',
    'ai.voice.offline': 'आवाज़ से पूछने के लिए इंटरनेट चाहिए। इंटरनेट चालू करके फिर कोशिश करें।',

    // ---- History ----
    'ai.history.title': 'पुरानी बातचीत',
    'ai.history.subtitle': '{n} बातचीत सेव हैं',
    'ai.history.subtitleOne': '{n} बातचीत सेव है',
    'ai.history.search': 'बातचीत में खोजें',
    'ai.history.today': 'आज',
    'ai.history.week': 'पिछले 7 दिन',
    'ai.history.older': 'इससे पुरानी',
    'ai.history.messages': '{n} संदेश',
    'ai.history.messagesOne': '{n} संदेश',
    'ai.history.pending': 'जवाब आ रहा है…',
    'ai.history.hasSaved': 'जवाब सेव है',
    'ai.history.you': 'आप: {text}',
    'ai.history.photo': 'फोटो भेजी',
    'ai.history.noAnswer': 'जवाब नहीं मिला',
    'ai.history.options': 'बातचीत के विकल्प',
    'ai.history.open': 'बातचीत खोलें',
    'ai.history.delete': 'बातचीत हटाएं',
    'ai.history.deleteBody': 'यह बातचीत इस फ़ोन से हट जाएगी।',
    'ai.history.deleteBodySaved': 'यह बातचीत इस फ़ोन से हट जाएगी। इसके सेव किए गए जवाब भी "मेरी सेव की गई जानकारी" से हट जाएंगे।',
    'ai.history.deleted': 'बातचीत हटा दी गई',
    'ai.history.deleteAll': 'सारी बातचीत हटाएं',
    'ai.history.deleteAllTitle': 'सारी बातचीत हटाएं?',
    'ai.history.deleteAllBody': 'सभी {n} बातचीत इस फ़ोन से हट जाएंगी।',
    'ai.history.deleteAllBodyKeep': '{n} बातचीत इस फ़ोन से हट जाएंगी। जिन {k} बातचीत में आपने कोई जवाब सेव किया है, वे बनी रहेंगी।',
    'ai.history.deletedAll': 'सारी बातचीत हटा दी गई',
    'ai.history.undo': 'वापस लाएं',
    'ai.history.emptyTitle': 'अभी कोई बातचीत नहीं',
    'ai.history.emptyBody': 'AI किसान मित्र से खेती का कोई भी सवाल पूछें। आपकी बातचीत यहां सेव रहेगी।',
    'ai.history.ask': 'सवाल पूछें',
    'ai.history.noResults': 'कोई बातचीत नहीं मिली',
    'ai.history.noResultsBody': 'दूसरे शब्दों से खोजकर देखें।',
    'ai.history.clearSearch': 'खोज साफ़ करें',
    'ai.history.hint': 'बातचीत हटाने के लिए उसे देर तक दबाएं या ⋮ बटन दबाएं।',
  },
  en: {
    'ai.chat.title': 'AI Kisan Mitra',
    'ai.chat.subtitle': 'Your personal farming assistant',
    'ai.chat.history': 'Past chats',
    'ai.chat.new': 'New chat',
    'ai.chat.assistant': 'Kisan Mitra',
    'ai.chat.welcome':
      "Namaste! I'm Kisan Mitra, your farming companion. Ask me anything about crop diseases, fertilizer, irrigation, weather or mandi prices. You can also send a photo or ask by voice.",
    'ai.chat.quickTitle': 'How can I help today?',
    'ai.chat.photoTitle': 'Photo question',
    'ai.chat.missing': 'This chat is no longer available. Ask a new question.',
    'ai.chat.unanswered': 'This question did not get an answer.',
    'ai.chat.typing': 'Kisan Mitra is writing an answer…',
    'ai.chat.errorPast': 'This question could not be answered at the time.',

    'ai.card.photo': 'Identify by photo',
    'ai.card.photoDesc': 'Find crop diseases',
    'ai.card.voice': 'Ask by voice',
    'ai.card.voiceDesc': 'Speak your question',
    'ai.card.advice': 'Crop advice',
    'ai.card.adviceDesc': 'For your crops',
    'ai.card.market': 'Mandi analysis',
    'ai.card.marketDesc': 'Prices and when to sell',

    'ai.suggest.title': 'You can ask',
    'ai.suggest.yellow': 'Why are {crop} leaves yellow?',
    'ai.suggest.fertilizer': 'When to apply fertilizer to {crop}?',
    'ai.suggest.pest': 'How to protect {crop} from pests?',
    'ai.suggest.irrigation': 'When to irrigate {crop}?',
    'ai.suggest.seed': 'How to treat {crop} seed?',
    'ai.suggest.sowing': 'Right way to sow {crop}?',
    'ai.suggest.harvest': 'When to harvest {crop}?',
    'ai.suggest.price': 'What is the mandi price of {crop}?',
    'ai.suggest.sowNow': 'What to sow now in {season}?',
    'ai.suggest.spray': 'Should I spray this week?',

    'ai.starter.advice': 'My crops: {crops}. What should I do now to care for them this {season} season?',
    'ai.starter.adviceCrop': 'My {crop} crop is at the {stage} stage now. What should I do at this time?',
    'ai.starter.adviceNoCrops': 'Which crop should I grow in {place} this {season} season, and what should I prepare now?',
    'ai.starter.market': 'How are {crops} prices moving in mandis around {place}? Should I sell now or wait?',
    'ai.starter.marketNoCrops': 'What are today\'s prices of major crops in mandis around {place}?',

    'ai.crop.note': 'Answers will keep this crop in mind',
    'ai.crop.meta': '{area} • {stage}',

    'ai.answer.problem': 'Problem',
    'ai.answer.causes': 'Likely causes',
    'ai.answer.do': 'What to do',
    'ai.answer.dont': 'What not to do',
    'ai.answer.recheck': 'When to check again',
    'ai.answer.more': 'Ask more',
    'ai.answer.followTitle': 'Ask more',
    'ai.answer.unsaved': 'Removed from saved',
    'ai.answer.shareTitle': 'Advice from Kisan Mitra',
    'ai.answer.shareFooter': '— from the Kisan Mitra app',
    'ai.answer.question': 'Question',
    'ai.answer.schemeNote': 'Scheme rules and amounts change. Confirm on the official website or with the agriculture department before applying.',
    'ai.answer.weatherNote': 'Forecasts can change. Check the latest weather before field work.',
    'ai.answer.viaVoice': 'Asked by voice',
    'ai.answer.photoAlt': 'Photo you sent',
    'ai.answer.photoDropped': 'Old photo removed to save space',
    'ai.answer.actions': 'Answer options',
    'ai.answer.sources': 'Sources (from the web)',

    'ai.composer.label': 'Type your question',
    'ai.composer.placeholder': 'Type your question…',
    'ai.composer.placeholderPhoto': 'Say something about the photo (optional)…',
    'ai.composer.send': 'Send question',
    'ai.composer.photo': 'Add a crop photo',
    'ai.composer.removePhoto': 'Remove photo',
    'ai.composer.photoPreview': 'Attached photo',
    'ai.composer.offline': 'No internet. Turn on internet to ask; you can still read past chats.',
    'ai.composer.notConfigured': 'The AI assistant is not switched on yet.',
    'ai.photo.header': 'Crop photo',
    'ai.photo.camera': 'Take photo',
    'ai.photo.gallery': 'Choose from gallery',
    'ai.photo.error': 'Could not open the photo. Please choose another one.',

    'ai.notConfigured.title': 'AI assistant is not available',
    'ai.notConfigured.body':
      'The AI service has not been set up in this app yet. Weather, the crop calendar, accounts and government schemes work without AI.',
    'ai.notConfigured.help': 'Help centre',

    'ai.voice.title': 'Ask by voice',
    'ai.voice.subtitle': 'Speak, and Kisan Mitra will answer aloud',
    'ai.voice.micLabel': 'Ask your question by voice',
    'ai.voice.idle': 'Tap to speak',
    'ai.voice.idleHint': 'For example: "Why are my paddy leaves turning yellow?"',
    'ai.voice.listening': 'Listening…',
    'ai.voice.listeningHint': 'Say your question, then pause',
    'ai.voice.thinking': 'Thinking…',
    'ai.voice.thinkingHint': 'Preparing your answer',
    'ai.voice.answered': 'Listen to the answer',
    'ai.voice.answeredHint': 'Tap the mic to ask a new question',
    'ai.voice.errorTitle': 'Could not get an answer',
    'ai.voice.stop': 'Stop speaking',
    'ai.voice.replay': 'Listen again',
    'ai.voice.askAgain': 'Ask again',
    'ai.voice.viewChat': 'See full conversation',
    'ai.voice.typeInstead': 'Type instead',
    'ai.voice.trouble': 'Trouble speaking? You can type your question too.',
    'ai.voice.unsupported': 'Voice questions are not available on this phone. Type below and the answer will be read aloud.',
    'ai.voice.inputLabel': 'Your question',
    'ai.voice.inputPlaceholder': 'e.g. When to apply fertilizer to wheat?',
    'ai.voice.ask': 'Ask',
    'ai.voice.offline': 'You need internet to ask by voice. Turn it on and try again.',

    'ai.history.title': 'Past chats',
    'ai.history.subtitle': '{n} chats saved',
    'ai.history.subtitleOne': '{n} chat saved',
    'ai.history.search': 'Search chats',
    'ai.history.today': 'Today',
    'ai.history.week': 'Last 7 days',
    'ai.history.older': 'Older',
    'ai.history.messages': '{n} messages',
    'ai.history.messagesOne': '{n} message',
    'ai.history.pending': 'Answer on its way…',
    'ai.history.hasSaved': 'Answer saved',
    'ai.history.you': 'You: {text}',
    'ai.history.photo': 'Sent a photo',
    'ai.history.noAnswer': 'No answer',
    'ai.history.options': 'Chat options',
    'ai.history.open': 'Open chat',
    'ai.history.delete': 'Delete chat',
    'ai.history.deleteBody': 'This chat will be removed from this phone.',
    'ai.history.deleteBodySaved': 'This chat will be removed from this phone. Its saved answers will also be removed from "My saved items".',
    'ai.history.deleted': 'Chat deleted',
    'ai.history.deleteAll': 'Delete all chats',
    'ai.history.deleteAllTitle': 'Delete all chats?',
    'ai.history.deleteAllBody': 'All {n} chats will be removed from this phone.',
    'ai.history.deleteAllBodyKeep': '{n} chats will be removed from this phone. The {k} chats with a saved answer will stay.',
    'ai.history.deletedAll': 'All chats deleted',
    'ai.history.undo': 'Undo',
    'ai.history.emptyTitle': 'No chats yet',
    'ai.history.emptyBody': 'Ask AI Kisan Mitra any farming question. Your chats will be saved here.',
    'ai.history.ask': 'Ask a question',
    'ai.history.noResults': 'No chats found',
    'ai.history.noResultsBody': 'Try different words.',
    'ai.history.clearSearch': 'Clear search',
    'ai.history.hint': 'To delete a chat, long-press it or tap the ⋮ button.',
  },
});
