// Calendar module strings ("calendar.*"). Hindi first: short, plain words a farmer uses.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'calendar.title': 'खेती कैलेंडर',
    'calendar.subtitle': 'फसल के काम, सही समय पर',
    'calendar.filterCrops': 'फसल के हिसाब से काम देखें',
    'calendar.all': 'सभी',
    'calendar.period': 'समय चुनें',
    'calendar.tab.today': 'आज',
    'calendar.tab.tomorrow': 'कल',
    'calendar.tab.week': 'इस सप्ताह',
    'calendar.tab.month': 'इस महीने',
    'calendar.months': 'महीना चुनें',

    'calendar.section.today': 'आज के काम',
    'calendar.section.tomorrow': 'कल के काम',
    'calendar.section.week': 'अगले 7 दिन के काम',
    'calendar.section.month': '{month} के काम',
    'calendar.summary': '{open} करने हैं • {done} पूरे',
    'calendar.summaryOpen': '{open} काम करने हैं',
    'calendar.count': '{n} काम',
    'calendar.count1': '1 काम',

    'calendar.overdue.title': 'बाकी काम',
    'calendar.overdue.subtitle': 'ये काम पिछले दिनों में होने थे। हो गए हों तो निशान लगा दें।',
    'calendar.overdue.late': '{n} दिन की देरी',
    'calendar.overdue.late1': '1 दिन की देरी',
    'calendar.overdue.showAll': 'सभी {n} बाकी काम देखें',
    'calendar.overdue.showLess': 'कम दिखाएं',

    'calendar.done.title': 'पूरे हुए काम',
    'calendar.history.title': 'फसल जोड़ने से पहले के काम',
    'calendar.history.hint': 'ये काम ऐप में फसल जोड़ने से पहले के थे, इसलिए इन्हें देरी में नहीं गिना। हो गए हों तो निशान लगा दें।',
    'calendar.guidance.chemical': 'दवा का नाम और मात्रा नज़दीकी KVK या कृषि विशेषज्ञ से पूछकर ही डालें। छिड़काव के समय दस्ताने और मास्क पहनें।',
    'calendar.doneLabel': '{task} — पूरा हुआ',
    'calendar.toast.done': 'शाबाश! काम पूरा हुआ',
    'calendar.toast.reopened': 'काम फिर से बाकी में आ गया',
    'calendar.undo': 'वापस लें',
    'calendar.myTask': 'मेरा काम',
    'calendar.inDays': '{n} दिन बाद',

    'calendar.empty.today': 'आज कोई काम नहीं है। बस खेत पर एक नज़र डाल लें।',
    'calendar.empty.tomorrow': 'कल के लिए कोई काम तय नहीं है।',
    'calendar.empty.week': 'अगले 7 दिन में कोई काम नहीं है।',
    'calendar.empty.month': '{month} में कोई काम नहीं है।',
    'calendar.empty.allDone': 'सारे काम पूरे हो गए। बहुत बढ़िया!',
    'calendar.empty.next': 'अगला काम: {task}',
    'calendar.empty.nextWhen': '{date} को',
    'calendar.empty.viewNext': 'देखें',

    'calendar.noCrops.title': 'अभी कोई फसल नहीं जोड़ी',
    'calendar.noCrops.body': 'फसल और बुवाई की तारीख जोड़ें। सिंचाई, खाद, निराई और कटाई के काम अपने-आप यहां आ जाएंगे।',
    'calendar.noCrops.action': 'फसल जोड़ें',
    'calendar.noCrops.secondary': 'अपना काम जोड़ें',
    'calendar.noCrops.hint': 'फसल जोड़ेंगे तो उसके सारे काम अपने-आप बन जाएंगे।',

    'calendar.noSowing.title': '{crop} की बुवाई की तारीख नहीं है',
    'calendar.noSowing.titleMany': 'इन फसलों की बुवाई की तारीख नहीं है',
    'calendar.noSowing.body': 'बुवाई की तारीख डालते ही सिंचाई, खाद और कटाई के काम अपने-आप कैलेंडर में आ जाएंगे।',
    'calendar.noSowing.allTitle': 'बुवाई की तारीख डालें',
    'calendar.noSowing.action': 'तारीख जोड़ें',
    'calendar.noSowing.rowAction': '{crop} की तारीख जोड़ें',

    'calendar.syncError.title': 'फसल के काम नहीं बन पाए',
    'calendar.syncError.body': 'कुछ गड़बड़ हो गई। दोबारा कोशिश करें, आपके जोड़े काम सुरक्षित हैं।',

    'calendar.reminder.set': '{task} — याद दिलाएं',
    'calendar.reminder.change': '{task} — रिमाइंडर {when} पर लगा है, बदलें',
    'calendar.reminder.title': 'याद कब दिलाएं?',
    'calendar.reminder.choice': 'रिमाइंडर का समय',
    'calendar.reminder.sameDay': 'उसी दिन सुबह 7 बजे',
    'calendar.reminder.dayBefore': 'एक दिन पहले शाम 6 बजे',
    'calendar.reminder.custom': 'अपनी तारीख और समय चुनें',
    'calendar.reminder.passed': 'यह समय निकल चुका है',
    'calendar.reminder.date': 'तारीख',
    'calendar.reminder.time': 'समय',
    'calendar.reminder.save': 'रिमाइंडर लगाएं',
    'calendar.reminder.remove': 'रिमाइंडर हटाएं',
    'calendar.reminder.current': 'अभी लगा है: {when}',
    'calendar.reminder.setToast': 'रिमाइंडर लग गया: {when}',
    'calendar.reminder.removedToast': 'रिमाइंडर हटा दिया',
    'calendar.reminder.denied': 'सूचना की अनुमति नहीं मिली। फ़ोन की सेटिंग में किसान मित्र के लिए "सूचनाएं" चालू करें, फिर दोबारा कोशिश करें।',
    'calendar.reminder.pastError': 'यह समय निकल चुका है। आगे का कोई समय चुनें।',
    'calendar.reminder.invalid': 'सही तारीख और समय चुनें',
    'calendar.reminder.failed': 'रिमाइंडर नहीं लग पाया। दोबारा कोशिश करें।',
    'calendar.reminder.offTitle': 'सेटिंग में रिमाइंडर बंद हैं',
    'calendar.reminder.offBody': 'रिमाइंडर लगाने के लिए पहले सेटिंग में सूचनाएं और रिमाइंडर चालू करें।',
    'calendar.reminder.offAction': 'सेटिंग खोलें',
    'calendar.reminder.webNote': 'वेब पर रिमाइंडर तभी दिखेगा जब आप किसान मित्र खोलेंगे। फ़ोन ऐप में समय पर सूचना आती है।',
    'calendar.reminder.lostOnEdit': 'तारीख बदल गई है। रिमाइंडर फिर से लगाएं।',
    'calendar.reminder.lostOnUpdate': 'काम बदलने के बाद रिमाइंडर नहीं लग पाया, इसलिए हटा दिया। काम खोलकर फिर से लगाएं।',

    'calendar.add.fab': 'काम जोड़ें',
    'calendar.add.title': 'नया काम जोड़ें',
    'calendar.edit.title': 'काम बदलें',
    'calendar.form.name': 'काम का नाम',
    'calendar.form.namePlaceholder': 'जैसे: खेत में पानी लगाना',
    'calendar.form.nameError': 'काम का नाम लिखें या बोलकर बताएं',
    'calendar.form.type': 'काम किस तरह का है',
    'calendar.form.date': 'कब करना है',
    'calendar.form.dateError': 'तारीख चुनें',
    'calendar.form.crop': 'किस फसल का काम है',
    'calendar.form.noCrop': 'कोई फसल नहीं',
    'calendar.form.note': 'नोट',
    'calendar.form.notePlaceholder': 'जैसे: पंप वाले को फ़ोन करना है',
    'calendar.form.save': 'काम जोड़ें',
    'calendar.form.update': 'बदलाव सेव करें',
    'calendar.toast.added': 'काम जुड़ गया — {date}',
    'calendar.toast.addReminder': 'याद दिलाएं',
    'calendar.toast.updated': 'काम बदल दिया',
    'calendar.toast.deleted': 'काम हटा दिया',
    'calendar.delete.title': 'यह काम हटाएं?',
    'calendar.delete.body': '"{task}" कैलेंडर से हट जाएगा।',

    'calendar.detail.when': 'कब',
    'calendar.detail.crop': 'फसल',
    'calendar.detail.type': 'काम का प्रकार',
    'calendar.detail.reminder': 'रिमाइंडर',
    'calendar.detail.noReminder': 'कोई रिमाइंडर नहीं',
    'calendar.detail.auto': 'यह काम आपकी फसल की बुवाई की तारीख के हिसाब से अपने-आप बना है। मौसम और खेत की हालत देखकर एक-दो दिन आगे-पीछे कर सकते हैं।',
    'calendar.detail.markDone': 'काम पूरा हुआ',
    'calendar.detail.reopen': 'फिर से बाकी करें',
    'calendar.detail.setReminder': 'रिमाइंडर लगाएं',
    'calendar.detail.changeReminder': 'बदलें',
    'calendar.detail.askAi': 'AI से पूछें, कैसे करें',
    'calendar.detail.askAiPrompt': 'मेरी {crop} की फसल में "{task}" का काम कैसे करूं? सही समय, तरीका और ज़रूरी सावधानियां आसान शब्दों में बताएं।',
    'calendar.detail.askAiPromptNoCrop': '"{task}" का काम कैसे करूं? सही समय, तरीका और ज़रूरी सावधानियां आसान शब्दों में बताएं।',
    'calendar.detail.viewCrop': 'फसल देखें',
    'calendar.detail.protection': 'दवा का नाम और मात्रा के लिए नज़दीकी KVK या कृषि विशेषज्ञ से पूछें। लेबल पर लिखी मात्रा से ज़्यादा न डालें, और छिड़काव के समय दस्ताने और मास्क पहनें।',
    'calendar.detail.editTask': 'काम बदलें',
    'calendar.detail.deleteTask': 'काम हटाएं',

    'calendar.type.seed-treatment': 'बीज उपचार',
    'calendar.type.sowing': 'बुवाई',
    'calendar.type.irrigation': 'सिंचाई',
    'calendar.type.fertilizer': 'खाद',
    'calendar.type.pest-scouting': 'कीट निरीक्षण',
    'calendar.type.crop-protection': 'फसल सुरक्षा',
    'calendar.type.weeding': 'निराई',
    'calendar.type.harvest': 'कटाई',
    'calendar.type.other': 'अन्य',
  },
  en: {
    'calendar.title': 'Farming calendar',
    'calendar.subtitle': 'Crop tasks, on time',
    'calendar.filterCrops': 'Filter tasks by crop',
    'calendar.all': 'All',
    'calendar.period': 'Choose period',
    'calendar.tab.today': 'Today',
    'calendar.tab.tomorrow': 'Tomorrow',
    'calendar.tab.week': 'This week',
    'calendar.tab.month': 'This month',
    'calendar.months': 'Choose month',

    'calendar.section.today': "Today's tasks",
    'calendar.section.tomorrow': "Tomorrow's tasks",
    'calendar.section.week': 'Tasks for the next 7 days',
    'calendar.section.month': 'Tasks in {month}',
    'calendar.summary': '{open} to do • {done} done',
    'calendar.summaryOpen': '{open} to do',
    'calendar.count': '{n} tasks',
    'calendar.count1': '1 task',

    'calendar.overdue.title': 'Overdue tasks',
    'calendar.overdue.subtitle': 'These were due in the last few days. Tick them if they are done.',
    'calendar.overdue.late': '{n} days late',
    'calendar.overdue.late1': '1 day late',
    'calendar.overdue.showAll': 'See all {n} overdue tasks',
    'calendar.overdue.showLess': 'Show less',

    'calendar.done.title': 'Completed tasks',
    'calendar.history.title': 'Before you added the crop',
    'calendar.history.hint': 'These were due before you added the crop to the app, so they are not counted as late. Tick them if they are done.',
    'calendar.guidance.chemical': 'Ask your nearest KVK or agriculture expert for the product and dose before using any chemical. Wear gloves and a mask while spraying.',
    'calendar.doneLabel': '{task} — done',
    'calendar.toast.done': 'Well done! Task completed',
    'calendar.toast.reopened': 'Task marked as not done',
    'calendar.undo': 'Undo',
    'calendar.myTask': 'My task',
    'calendar.inDays': 'in {n} days',

    'calendar.empty.today': 'No tasks today. Just keep an eye on the field.',
    'calendar.empty.tomorrow': 'Nothing planned for tomorrow.',
    'calendar.empty.week': 'No tasks in the next 7 days.',
    'calendar.empty.month': 'No tasks in {month}.',
    'calendar.empty.allDone': 'All tasks done. Great work!',
    'calendar.empty.next': 'Next task: {task}',
    'calendar.empty.nextWhen': 'on {date}',
    'calendar.empty.viewNext': 'View',

    'calendar.noCrops.title': 'No crops added yet',
    'calendar.noCrops.body': 'Add your crop and sowing date. Irrigation, fertilizer, weeding and harvest tasks will appear here automatically.',
    'calendar.noCrops.action': 'Add crop',
    'calendar.noCrops.secondary': 'Add your own task',
    'calendar.noCrops.hint': 'Add a crop and all its tasks are created automatically.',

    'calendar.noSowing.title': 'No sowing date for {crop}',
    'calendar.noSowing.titleMany': 'These crops have no sowing date',
    'calendar.noSowing.body': 'Once you add the sowing date, irrigation, fertilizer and harvest tasks appear in the calendar automatically.',
    'calendar.noSowing.allTitle': 'Add your sowing dates',
    'calendar.noSowing.action': 'Add date',
    'calendar.noSowing.rowAction': 'Add date for {crop}',

    'calendar.syncError.title': 'Could not create crop tasks',
    'calendar.syncError.body': 'Something went wrong. Please try again — your own tasks are safe.',

    'calendar.reminder.set': '{task} — remind me',
    'calendar.reminder.change': '{task} — reminder set for {when}, change',
    'calendar.reminder.title': 'When should we remind you?',
    'calendar.reminder.choice': 'Reminder time',
    'calendar.reminder.sameDay': 'Same day, 7 AM',
    'calendar.reminder.dayBefore': 'Day before, 6 PM',
    'calendar.reminder.custom': 'Choose your own date and time',
    'calendar.reminder.passed': 'This time has passed',
    'calendar.reminder.date': 'Date',
    'calendar.reminder.time': 'Time',
    'calendar.reminder.save': 'Set reminder',
    'calendar.reminder.remove': 'Remove reminder',
    'calendar.reminder.current': 'Currently set: {when}',
    'calendar.reminder.setToast': 'Reminder set: {when}',
    'calendar.reminder.removedToast': 'Reminder removed',
    'calendar.reminder.denied': 'Notification permission was not given. Turn on notifications for Kisan Mitra in your phone settings, then try again.',
    'calendar.reminder.pastError': 'That time has already passed. Pick a later time.',
    'calendar.reminder.invalid': 'Choose a valid date and time',
    'calendar.reminder.failed': 'Could not set the reminder. Please try again.',
    'calendar.reminder.offTitle': 'Reminders are off in settings',
    'calendar.reminder.offBody': 'To set a reminder, first turn on notifications and reminders in Settings.',
    'calendar.reminder.offAction': 'Open settings',
    'calendar.reminder.webNote': 'On the web, the reminder shows when you next open Kisan Mitra. The phone app notifies you on time.',
    'calendar.reminder.lostOnEdit': 'The date changed. Please set the reminder again.',
    'calendar.reminder.lostOnUpdate': 'The reminder could not be updated, so it was removed. Open the task to set it again.',

    'calendar.add.fab': 'Add task',
    'calendar.add.title': 'Add a task',
    'calendar.edit.title': 'Edit task',
    'calendar.form.name': 'Task name',
    'calendar.form.namePlaceholder': 'e.g. Water the field',
    'calendar.form.nameError': 'Write or speak the task name',
    'calendar.form.type': 'Type of task',
    'calendar.form.date': 'When',
    'calendar.form.dateError': 'Choose a date',
    'calendar.form.crop': 'For which crop',
    'calendar.form.noCrop': 'No crop',
    'calendar.form.note': 'Note',
    'calendar.form.notePlaceholder': 'e.g. Call the pump mechanic',
    'calendar.form.save': 'Add task',
    'calendar.form.update': 'Save changes',
    'calendar.toast.added': 'Task added — {date}',
    'calendar.toast.addReminder': 'Remind me',
    'calendar.toast.updated': 'Task updated',
    'calendar.toast.deleted': 'Task deleted',
    'calendar.delete.title': 'Delete this task?',
    'calendar.delete.body': '"{task}" will be removed from the calendar.',

    'calendar.detail.when': 'When',
    'calendar.detail.crop': 'Crop',
    'calendar.detail.type': 'Type of task',
    'calendar.detail.reminder': 'Reminder',
    'calendar.detail.noReminder': 'No reminder',
    'calendar.detail.auto': 'This task was created from your sowing date. You can move it a day or two depending on the weather and field condition.',
    'calendar.detail.markDone': 'Mark as done',
    'calendar.detail.reopen': 'Mark as not done',
    'calendar.detail.setReminder': 'Set reminder',
    'calendar.detail.changeReminder': 'Change',
    'calendar.detail.askAi': 'Ask AI how to do it',
    'calendar.detail.askAiPrompt': 'How do I do "{task}" for my {crop} crop? Explain the right timing, method and precautions in simple words.',
    'calendar.detail.askAiPromptNoCrop': 'How do I do "{task}"? Explain the right timing, method and precautions in simple words.',
    'calendar.detail.viewCrop': 'View crop',
    'calendar.detail.protection': 'Ask your nearest KVK or agriculture expert for the product and dose. Never use more than the label says, and wear gloves and a mask while spraying.',
    'calendar.detail.editTask': 'Edit task',
    'calendar.detail.deleteTask': 'Delete task',

    'calendar.type.seed-treatment': 'Seed treatment',
    'calendar.type.sowing': 'Sowing',
    'calendar.type.irrigation': 'Irrigation',
    'calendar.type.fertilizer': 'Fertilizer',
    'calendar.type.pest-scouting': 'Pest check',
    'calendar.type.crop-protection': 'Crop protection',
    'calendar.type.weeding': 'Weeding',
    'calendar.type.harvest': 'Harvest',
    'calendar.type.other': 'Other',
  },
});
