// Strings for the Mandi module (screens/mandi). The data service registers its own keys in
// services/mandi-strings.ts (mandi.signal.*, mandi.priceDate, mandi.error.*, mandi.history.*,
// mandi.notif.*, mandi.nearbyMarket); the keys below never reuse those names.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';
import '../../services/mandi-strings';

registerStrings({
  hi: {
    // App bar
    'mandi.title': 'मंडी भाव',
    'mandi.placeA11y': 'जगह बदलें। अभी की जगह: {place}',

    // Tabs
    'mandi.tabs.label': 'क्या देखना है',
    'mandi.tabs.prices': 'फसल भाव',
    'mandi.tabs.nearby': 'नज़दीकी मंडी',

    // Watchlist chips and editor
    'mandi.watch.label': 'मेरी भाव सूची की फसलें',
    'mandi.watch.all': 'सभी',
    'mandi.watch.add': 'फसल',
    'mandi.watch.addA11y': 'भाव सूची में फसल जोड़ें या हटाएं',
    'mandi.watch.sheetTitle': 'किन फसलों के भाव देखने हैं?',
    'mandi.watch.sheetDesc': 'चुनी गई फसलों के भाव मंडी भाव पेज पर दिखेंगे। भाव में बड़ा बदलाव होने पर सूचना भी मिल सकती है।',
    'mandi.watch.pickerLabel': 'फसलें चुनें',
    'mandi.watch.count': 'चुनी गई फसलें: {n}',
    'mandi.watch.max': 'एक बार में ज़्यादा से ज़्यादा {n} फसलें चुन सकते हैं',
    'mandi.watch.min': 'कम से कम एक फसल चुनें',
    'mandi.watch.saved': 'आपकी भाव सूची बदल गई',

    // Price list
    'mandi.list.title': 'हाल के मंडी भाव',
    'mandi.list.a11y': 'फसलों के मंडी भाव',
    'mandi.price.perQuintal': '{price} / क्विंटल',
    'mandi.price.range': '{min} – {max}',
    'mandi.price.today': 'आज का भाव',
    'mandi.row.a11y': '{crop}, {price} प्रति क्विंटल, {date}। पूरा भाव देखें',
    'mandi.list.missing': 'इनके ताज़ा भाव नहीं मिले: {crops}',
    'mandi.list.noneForCrop': 'इस इलाके में {crop} का ताज़ा भाव नहीं मिला',
    'mandi.list.noneForCropBody': 'आसपास की मंडियों में इसका हाल का भाव नहीं मिला। थोड़ी देर बाद देखें या नज़दीकी बड़ा शहर चुनें।',

    // States
    'mandi.empty.title': 'इस इलाके के ताज़ा भाव नहीं मिले',
    'mandi.empty.changePlace': 'दूसरी जगह चुनें',
    'mandi.emptyList.title': 'भाव देखने के लिए फसल चुनें',
    'mandi.emptyList.body': 'जिन फसलों के भाव रोज़ देखने हैं, उन्हें अपनी भाव सूची में जोड़ें।',
    'mandi.emptyList.action': 'फसल जोड़ें',
    'mandi.unverified.title': 'भाव पक्के नहीं हो पाए',
    'mandi.refreshFailed.title': 'सभी भाव ताज़ा नहीं हो पाए',
    'mandi.refreshFailed.body': 'जो भाव दिख रहे हैं, उनकी तारीख ज़रूर देखें।',

    // AI बाज़ार संकेत card
    'mandi.ai.titleFor': '{title} · {crop}',
    'mandi.ai.loading': 'बाज़ार संकेत तैयार हो रहा है…',
    'mandi.ai.details': 'पूरा भाव देखें',

    // Sources and portals
    'mandi.sources.title': 'भाव कहाँ से लिए गए',
    'mandi.sources.note': 'ये भाव इंटरनेट पर मौजूद सार्वजनिक स्रोतों (जैसे सरकारी पोर्टल, समाचार) से लिए गए हैं।',
    'mandi.opensBrowser': '(ब्राउज़र में खुलेगा)',
    'mandi.portals.title': 'सरकारी मंडी पोर्टल',
    'mandi.portals.subtitle': 'सरकारी भाव खुद देखने के लिए',
    'mandi.portals.enam': 'e-NAM — राष्ट्रीय कृषि बाज़ार',
    'mandi.portals.enamDesc': 'ऑनलाइन मंडी व्यापार और भाव',
    'mandi.portals.agmarknet': 'AGMARKNET — एगमार्कनेट',
    'mandi.portals.agmarknetDesc': 'देश भर की मंडियों के रोज़ के भाव',

    // Nearby mandis tab
    'mandi.nearby.title': 'आसपास की मंडियाँ',
    'mandi.nearby.note':
      'यह सूची इंटरनेट खोज से बनी है और पूरी या सही होने की गारंटी नहीं है। मंडी जाने से पहले नाम, दूरी और खुलने का समय पक्का कर लें।',
    'mandi.nearby.aiNote': 'मंडियों के नाम AI ने इंटरनेट खोज से निकाले हैं, इनमें गलती हो सकती है।',
    'mandi.nearby.pricesFrom': 'यहाँ के भाव: {crops}',
    'mandi.nearby.empty.title': 'आसपास की मंडियों की जानकारी नहीं मिली',
    'mandi.nearby.empty.body': 'थोड़ी देर बाद फिर देखें या नज़दीकी बड़ा शहर चुनें।',

    // Detail screen
    'mandi.detail.title': '{crop} का भाव',
    'mandi.detail.invalid.title': 'यह फसल नहीं मिली',
    'mandi.detail.invalid.body': 'मंडी भाव की सूची पर जाकर फसल चुनें।',
    'mandi.detail.invalid.action': 'मंडी भाव देखें',
    'mandi.detail.priceA11y': 'मंडी भाव {price} प्रति क्विंटल',
    'mandi.detail.max': 'सबसे ऊंचा',
    'mandi.detail.min': 'सबसे कम',
    'mandi.detail.dayRange': 'उस दिन मंडी में भाव',
    'mandi.detail.yesterday': 'कल का भाव',
    'mandi.detail.previous': 'पिछला भाव',
    'mandi.detail.prevFromSource': 'स्रोत में दर्ज पिछला भाव',
    'mandi.detail.prevFromHistory': 'इसी मंडी का पिछला दर्ज भाव',
    'mandi.detail.diffUp': 'पिछले भाव से {amount} ज़्यादा',
    'mandi.detail.diffDown': 'पिछले भाव से {amount} कम',
    'mandi.detail.diffSame': 'पिछले भाव के बराबर',
    'mandi.detail.noPrevious': 'पिछला भाव उपलब्ध नहीं है, इसलिए बदलाव नहीं दिखा सकते।',
    'mandi.detail.trendTitle': '7 दिन का रुझान',
    'mandi.detail.trendNotEnough': 'रुझान देखने के लिए कुछ दिन भाव देखते रहें',
    'mandi.detail.trendNotEnoughBody': 'आप जो भाव यहाँ देखते हैं, वे फ़ोन में दर्ज होते जाते हैं। 2 दिन के भाव मिलते ही रुझान यहाँ दिखेगा।',
    'mandi.detail.trendNote': 'यह रुझान {market} मंडी के उन भावों से बना है जो इस ऐप में पिछले दिनों दर्ज हुए।',
    'mandi.detail.chartTitle': '{crop} का भाव, पिछले 7 दिन',
    'mandi.detail.weekHigh': '7 दिन में सबसे ऊंचा',
    'mandi.detail.weekLow': '7 दिन में सबसे कम',
    'mandi.detail.compareTitle': 'आसपास की मंडियाँ',
    'mandi.detail.compareBody': 'बेचने से पहले इन मंडियों के भाव भी पूछकर मिला लें।',
    'mandi.detail.thisPrice': 'ऊपर का भाव यहीं का',
    'mandi.detail.saved': 'सेव किया हुआ',
    'mandi.detail.unsaved': 'सेव से हटा दिया',
    'mandi.detail.watch': 'मेरी भाव सूची में रखें',
    'mandi.detail.watchDesc': 'मंडी भाव वाले पेज पर यह फसल हमेशा दिखेगी',
    'mandi.detail.watchAdded': '{crop} को आपकी भाव सूची में जोड़ दिया',
    'mandi.detail.watchRemoved': '{crop} को भाव सूची से हटा दिया',
    'mandi.detail.watchFull': 'भाव सूची में {n} से ज़्यादा फसलें नहीं रख सकते',
    'mandi.detail.watchLast': 'भाव सूची में कम से कम एक फसल रहनी चाहिए',
    'mandi.detail.ask': 'मंडी विश्लेषण पूछें',
    'mandi.detail.askPrompt':
      '{crop} का ताज़ा मंडी भाव {market} मंडी में {date} को {price} प्रति क्विंटल था। इस भाव का आसान विश्लेषण बताइए और बेचने से पहले मुझे किन बातों का ध्यान रखना चाहिए?',
    'mandi.detail.askPromptNoPrice': '{crop} के मंडी भाव के बारे में बताइए। बेचने से पहले मुझे किन बातों का ध्यान रखना चाहिए?',
    'mandi.detail.sourceTitle': 'भाव का स्रोत',

    // Share and save
    'mandi.share.title': '{crop} का मंडी भाव',
    'mandi.share.text':
      '{crop} का मंडी भाव: {price} प्रति क्विंटल\nमंडी: {market}\nभाव की तारीख: {date}\nयह अनुमानित भाव है, बेचने से पहले मंडी में पक्का कर लें।\n— किसान मित्र',
    'mandi.save.title': '{crop} का मंडी भाव',
    'mandi.save.snippet': '{price}/क्विंटल • {market} • {date}',
  },
  en: {
    'mandi.title': 'Mandi prices',
    'mandi.placeA11y': 'Change place. Current place: {place}',

    'mandi.tabs.label': 'What to see',
    'mandi.tabs.prices': 'Crop prices',
    'mandi.tabs.nearby': 'Nearby mandis',

    'mandi.watch.label': 'Crops in my price list',
    'mandi.watch.all': 'All',
    'mandi.watch.add': 'Crop',
    'mandi.watch.addA11y': 'Add or remove crops in the price list',
    'mandi.watch.sheetTitle': 'Which crop prices do you want?',
    'mandi.watch.sheetDesc': 'Prices of the chosen crops show on the mandi prices page. You may also get an alert when a price moves a lot.',
    'mandi.watch.pickerLabel': 'Choose crops',
    'mandi.watch.count': 'Crops chosen: {n}',
    'mandi.watch.max': 'You can choose at most {n} crops',
    'mandi.watch.min': 'Choose at least one crop',
    'mandi.watch.saved': 'Your price list was updated',

    'mandi.list.title': 'Recent mandi prices',
    'mandi.list.a11y': 'Mandi prices of crops',
    'mandi.price.perQuintal': '{price} / quintal',
    'mandi.price.range': '{min} – {max}',
    'mandi.price.today': "Today's price",
    'mandi.row.a11y': '{crop}, {price} per quintal, {date}. See full price',
    'mandi.list.missing': 'No recent price found for: {crops}',
    'mandi.list.noneForCrop': 'No recent {crop} price found for this area',
    'mandi.list.noneForCropBody': 'No recent price was found at nearby mandis. Check later or pick a nearby big town.',

    'mandi.empty.title': 'No recent prices found for this area',
    'mandi.empty.changePlace': 'Choose another place',
    'mandi.emptyList.title': 'Choose crops to see prices',
    'mandi.emptyList.body': 'Add the crops whose prices you want to follow to your price list.',
    'mandi.emptyList.action': 'Add crops',
    'mandi.unverified.title': 'Prices could not be confirmed',
    'mandi.refreshFailed.title': 'Some prices could not be refreshed',
    'mandi.refreshFailed.body': 'Check the date shown with each price.',

    'mandi.ai.titleFor': '{title} · {crop}',
    'mandi.ai.loading': 'Preparing the market signal…',
    'mandi.ai.details': 'See full price',

    'mandi.sources.title': 'Where these prices come from',
    'mandi.sources.note': 'These prices are taken from public sources on the internet (such as government portals and news).',
    'mandi.opensBrowser': '(opens in browser)',
    'mandi.portals.title': 'Government mandi portals',
    'mandi.portals.subtitle': 'Check official prices yourself',
    'mandi.portals.enam': 'e-NAM — National Agriculture Market',
    'mandi.portals.enamDesc': 'Online mandi trade and prices',
    'mandi.portals.agmarknet': 'AGMARKNET',
    'mandi.portals.agmarknetDesc': 'Daily prices from mandis across India',

    'mandi.nearby.title': 'Nearby mandis',
    'mandi.nearby.note':
      'This list is built from an internet search and may be incomplete or wrong. Confirm the name, distance and opening hours before you go.',
    'mandi.nearby.aiNote': 'These mandi names were found by AI in an internet search and may contain mistakes.',
    'mandi.nearby.pricesFrom': 'Prices from here: {crops}',
    'mandi.nearby.empty.title': 'No nearby mandi information found',
    'mandi.nearby.empty.body': 'Check again later or pick a nearby big town.',

    'mandi.detail.title': '{crop} price',
    'mandi.detail.invalid.title': 'Crop not found',
    'mandi.detail.invalid.body': 'Go to the mandi price list and choose a crop.',
    'mandi.detail.invalid.action': 'See mandi prices',
    'mandi.detail.priceA11y': 'Mandi price {price} per quintal',
    'mandi.detail.max': 'Highest',
    'mandi.detail.min': 'Lowest',
    'mandi.detail.dayRange': 'Prices at the mandi that day',
    'mandi.detail.yesterday': "Yesterday's price",
    'mandi.detail.previous': 'Previous price',
    'mandi.detail.prevFromSource': 'Previous price shown by the source',
    'mandi.detail.prevFromHistory': 'Earlier price recorded for this mandi',
    'mandi.detail.diffUp': '{amount} more than the previous price',
    'mandi.detail.diffDown': '{amount} less than the previous price',
    'mandi.detail.diffSame': 'Same as the previous price',
    'mandi.detail.noPrevious': 'No previous price is available, so no change can be shown.',
    'mandi.detail.trendTitle': '7-day trend',
    'mandi.detail.trendNotEnough': 'Keep checking prices for a few days to see the trend',
    'mandi.detail.trendNotEnoughBody': 'Prices you view here are recorded on your phone. The trend appears once 2 days of prices are available.',
    'mandi.detail.trendNote': 'This trend is built from {market} mandi prices recorded in this app over the last days.',
    'mandi.detail.chartTitle': '{crop} price, last 7 days',
    'mandi.detail.weekHigh': '7-day high',
    'mandi.detail.weekLow': '7-day low',
    'mandi.detail.compareTitle': 'Nearby mandis',
    'mandi.detail.compareBody': 'Before selling, ask these mandis for their prices too and compare.',
    'mandi.detail.thisPrice': 'Price above is from here',
    'mandi.detail.saved': 'Saved',
    'mandi.detail.unsaved': 'Removed from saved',
    'mandi.detail.watch': 'Keep in my price list',
    'mandi.detail.watchDesc': 'This crop will always show on the mandi prices page',
    'mandi.detail.watchAdded': '{crop} added to your price list',
    'mandi.detail.watchRemoved': '{crop} removed from your price list',
    'mandi.detail.watchFull': 'Your price list can hold at most {n} crops',
    'mandi.detail.watchLast': 'Your price list needs at least one crop',
    'mandi.detail.ask': 'Ask for a mandi analysis',
    'mandi.detail.askPrompt':
      'The latest {crop} mandi price at {market} on {date} was {price} per quintal. Please explain this price simply and tell me what to keep in mind before selling.',
    'mandi.detail.askPromptNoPrice': 'Tell me about {crop} mandi prices. What should I keep in mind before selling?',
    'mandi.detail.sourceTitle': 'Price source',

    'mandi.share.title': '{crop} mandi price',
    'mandi.share.text':
      '{crop} mandi price: {price} per quintal\nMandi: {market}\nPrice date: {date}\nThis is an indicative price; confirm at the mandi before selling.\n— Kisan Mitra',
    'mandi.save.title': '{crop} mandi price',
    'mandi.save.snippet': '{price}/quintal • {market} • {date}',
  },
});
