// Strings for the Weather screens (06 Weather, 07 Weather Details). Conditions, AQI bands,
// spray reasons and alert texts come from services/weather-strings (weather.cond.*, weather.aqi.*,
// weather.spray.*, weather.alert.*); keys here use sub-prefixes that service does not.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';
import '../../services/weather-strings';

registerStrings({
  hi: {
    'weather.title': 'मौसम',
    'weather.place.change': 'स्थान बदलें — अभी: {place}',
    'weather.place.action': 'स्थान बदलें',

    // Hero
    'weather.hero.feelsLike': 'महसूस होता है {temp}°C',
    'weather.hero.todayRange': 'आज {min}° से {max}°',
    'weather.hero.stale': '{time} की जानकारी',
    'weather.hero.forecastNow': 'इस घंटे का अनुमान',
    'weather.hero.todayForecast': 'आज का अनुमान',
    'weather.chip.humidity': '{n}% नमी',
    'weather.chip.wind': 'हवा {n} km/h',
    'weather.chip.windGust': 'हवा {n} km/h, झोंके {g} km/h तक',
    'weather.chip.gust': 'झोंके {g} km/h तक',
    'weather.chip.rain': 'बारिश {n}%',
    'weather.chip.rainToday': 'आज बारिश की संभावना {n}%',
    'weather.chip.rainMm': '{mm} मिमी बारिश',
    'weather.chip.aqi': 'AQI {value} · {level}',
    'weather.chip.uv': 'UV {n} · {level}',
    'weather.refreshFailed.title': 'ताज़ा मौसम नहीं मिल पाया',
    'weather.refreshFailed.body': 'अभी {time} की जानकारी दिख रही है।',

    // Next 24 hours
    'weather.hourly.title': 'अगले 24 घंटे',
    'weather.hourly.now': 'अभी',
    'weather.hourly.item': '{time}: {temp}°C, {cond}, बारिश की संभावना {pct}%',
    'weather.hourly.empty': 'घंटेवार अनुमान अभी नहीं है। ताज़ा करके देखें।',

    // 7 days
    'weather.daily.title': 'अगले 7 दिन का अनुमान',
    'weather.daily.hint': 'किसी दिन पर टैप करें — घंटेवार मौसम और स्प्रे का समय देखें',
    'weather.daily.row': '{day}: {cond}। बारिश की संभावना {pct}%। न्यूनतम {min}°, अधिकतम {max}°।',
    'weather.daily.empty.title': 'मौसम का अनुमान पुराना हो गया है',
    'weather.daily.empty.body': 'नया अनुमान देखने के लिए इंटरनेट चालू करके ताज़ा करें।',

    // Spray card
    'weather.sprayCard.yes': 'हाँ, आज स्प्रे कर सकते हैं',
    'weather.sprayCard.no': 'आज स्प्रे न करें',
    'weather.sprayCard.unsure': 'अभी पक्का नहीं कह सकते',
    'weather.sprayCard.best': 'सबसे अच्छा समय: {window}',
    'weather.sprayCard.next': 'अगला अच्छा समय: {window}',
    'weather.sprayCard.label': 'दवा के पैकेट पर लिखे निर्देश ज़रूर पढ़ें और स्प्रे से पहले आसमान देख लें।',
    'weather.sprayCard.seeToday': 'आज के सभी अच्छे समय देखें',
    'weather.sprayCard.seeTomorrow': 'कल के अच्छे समय देखें',
    'weather.sprayCard.hourlyToday': 'आज का घंटेवार मौसम देखें',
    'weather.sprayCard.hourlyTomorrow': 'कल का घंटेवार मौसम देखें',

    // Alerts
    'weather.alerts.title': 'मौसम चेतावनी',
    'weather.alerts.none': 'अनुमान के हिसाब से अभी कोई बड़ी मौसम चेतावनी नहीं है।',
    'weather.alerts.urgent': 'बहुत ज़रूरी',
    'weather.alerts.important': 'ध्यान दें',
    'weather.alerts.action': 'क्या करें:',

    // Farm tips
    'weather.tips.title': 'मौसम के हिसाब से खेती सलाह',
    'weather.tips.subtitle': 'मौसम के अनुमान पर आधारित सामान्य सलाह',
    'weather.tip.thisDay': 'इस दिन',
    'weather.tip.rain.title': '{when} बारिश के आसार ({pct}%)',
    'weather.tip.rain.body': 'सिंचाई और दवा का स्प्रे अभी टाल दें। खेत से पानी निकलने का रास्ता खुला रखें।',
    'weather.tip.wind.title': '{when} तेज़ हवा — {speed} km/h तक',
    'weather.tip.wind.body': 'स्प्रे न करें, दवा उड़कर बेकार जाएगी। ऊंची फसल और बेलों को सहारा दें।',
    'weather.tip.heat.title': '{when} तेज़ गर्मी — {temp}°C तक',
    'weather.tip.heat.body':
      'सिंचाई शाम को करें ताकि पानी कम उड़े। मिट्टी पर पुआल या सूखी पत्तियां बिछाएं (मल्चिंग), इससे नमी बनी रहती है।',
    'weather.tip.humidity.title': 'हवा में नमी ज़्यादा ({pct}%)',
    'weather.tip.humidity.body':
      'फफूंद वाले रोग (झुलसा, रतुआ, पत्ती के धब्बे) बढ़ सकते हैं। पत्तियां रोज़ देखें, धब्बे दिखें तो फसल डॉक्टर से जांच करें।',
    'weather.tip.fog.title': 'कोहरा रहेगा',
    'weather.tip.fog.body': 'कोहरे में पत्तियां गीली रहती हैं — धूप निकलने के बाद ही स्प्रे करें। आलू-टमाटर में झुलसा रोग पर नज़र रखें।',
    'weather.tip.cold.title': '{when} सुबह ठंड — {temp}°C तक',
    'weather.tip.cold.body': 'नर्सरी और छोटे पौधों को रात में ढककर रखें, शाम को हल्की सिंचाई करें। पशुओं को ठंड से बचाएं।',
    'weather.tip.dry.title': 'इस हफ्ते बारिश के आसार कम',
    'weather.tip.dry.body': 'मिट्टी की नमी देखकर सिंचाई की योजना बनाएं। सिंचाई सुबह या शाम करें।',
    'weather.tip.normal.title': 'मौसम खेती के कामों के लिए ठीक है',
    'weather.tip.normal.body': 'निराई-गुड़ाई, सिंचाई और खाद जैसे ज़रूरी काम योजना से कर लें।',
    'weather.tip.scout.title': 'खेत की नियमित जांच करें',
    'weather.tip.scout.body': 'हफ्ते में दो बार खेत घूमकर कीट और रोग देखें। जल्दी पकड़ने से नुकसान कम होता है।',

    // Sun, UV, air
    'weather.sun.title': 'सूरज और हवा',
    'weather.sun.sunrise': 'सूर्योदय',
    'weather.sun.sunset': 'सूर्यास्त',
    'weather.sun.uv': 'UV सूचकांक',
    'weather.sun.aqi': 'हवा (AQI)',
    'weather.uv.low': 'कम',
    'weather.uv.moderate': 'मध्यम',
    'weather.uv.high': 'ज़्यादा',
    'weather.uv.veryHigh': 'बहुत ज़्यादा',
    'weather.uv.extreme': 'अत्यधिक',
    'weather.uvHint.safe': 'धूप से खास खतरा नहीं',
    'weather.uvHint.moderate': 'दोपहर में सिर ढककर काम करें',
    'weather.uvHint.high': 'दोपहर 11 से 3 बजे तक धूप में काम कम करें',
    'weather.aqiHint.good': 'खेत में काम के लिए हवा ठीक है',
    'weather.aqiHint.warn': 'सांस के मरीज़ ज़्यादा देर बाहर न रहें',
    'weather.aqiHint.bad': 'मुंह-नाक ढककर काम करें, पराली न जलाएं',

    // Spoken summaries ("सुनें")
    'weather.speak.stale': 'यह {time} की जानकारी है।',
    'weather.speak.now': '{place} में अभी {temp} डिग्री तापमान है, मौसम: {cond}।',
    'weather.speak.hour': '{place} में इस घंटे लगभग {temp} डिग्री तापमान रहने का अनुमान है, मौसम: {cond}।',
    'weather.speak.place': '{place} का मौसम।',
    'weather.speak.today': 'आज अधिकतम {max} और न्यूनतम {min} डिग्री रहेगा। बारिश की संभावना {pct} प्रतिशत है।',
    'weather.speak.alerts': 'चेतावनी: {titles}।',
    'weather.speak.spray': 'स्प्रे के बारे में: {reason}',
    'weather.speak.day': '{day} {place} का मौसम: {cond}। अधिकतम {max} और न्यूनतम {min} डिग्री, बारिश की संभावना {pct} प्रतिशत।',
    'weather.speak.dayWindows': 'स्प्रे के लिए अच्छा समय: {windows}।',
    'weather.speak.dayBest': 'इनमें सबसे अच्छा: {window}।',
    'weather.speak.kmh': 'किलोमीटर प्रति घंटा',
    'weather.speak.deg': 'डिग्री',
    'weather.speak.mm': 'मिलीमीटर',
    'weather.speak.to': 'से',

    // Weather Details (one day)
    'weather.day.subtitle': '{place} का मौसम',
    'weather.day.pick': 'दिन चुनें',
    'weather.day.maxMin': 'अधिकतम {max}°, न्यूनतम {min}°',
    'weather.day.sunTimes': 'सूर्योदय {rise} · सूर्यास्त {set}',
    'weather.day.alerts': 'इस दिन की चेतावनी',
    'weather.day.spray.title': 'स्प्रे के लिए अच्छा समय',
    'weather.day.spray.ideal': 'सबसे अच्छा',
    'weather.day.spray.good': 'अच्छा',
    'weather.day.spray.ok': 'ठीक',
    'weather.day.spray.facts': 'हवा {wind} km/h · {temp}°C तक · बारिश {pct}%',
    'weather.day.spray.calm': 'हवा लगभग शांत है — मोटी बूंदों वाला नोज़ल लगाएं।',
    'weather.day.spray.breezy': 'हवा थोड़ी तेज़ है — नोज़ल फसल के पास रखकर स्प्रे करें।',
    'weather.day.spray.none': 'इस दिन स्प्रे के लिए अच्छा समय नहीं दिख रहा — {why}।',
    'weather.day.spray.passed': 'आज स्प्रे का अच्छा समय निकल चुका है।',
    'weather.day.spray.noData': 'इस दिन का घंटेवार अनुमान अभी नहीं आया है। स्प्रे का सही समय 1–2 दिन पहले यहां दिखेगा।',
    'weather.day.spray.partial': 'दिन के बाकी समय का घंटेवार अनुमान अभी नहीं आया है, इसलिए वह समय यहां नहीं जांचा गया।',
    'weather.day.spray.noDataOld': 'पुराने अनुमान में आगे के घंटे नहीं हैं, इसलिए स्प्रे का सही समय नहीं बता सकते।',
    'weather.day.spray.partialOld': 'पुराने अनुमान में दिन के बाकी घंटे नहीं हैं, इसलिए वह समय नहीं जांचा गया।',
    'weather.day.oldData': 'यह अनुमान पुराना है, इसलिए इस दिन के सभी घंटों का मौसम नहीं दिख रहा। इंटरनेट चालू करके ताज़ा करें।',
    'weather.day.spray.rules':
      'अच्छा समय: अगले {hours} घंटे बारिश न हो, हवा {min}–{max} km/h हो (ज़्यादा से ज़्यादा {limit}) और तापमान {temp}°C से ज़्यादा न हो।',
    'weather.day.tips.title': 'इस दिन के लिए खेती सलाह',
    'weather.day.hourly.title': 'घंटेवार मौसम',
    'weather.day.hourly.remaining': 'आज के बाकी घंटे',
    'weather.day.hourly.rain': 'बारिश {pct}%',
    'weather.day.hourly.mm': '{mm} मिमी',
    'weather.day.hourly.wind': 'हवा {n} km/h',
    'weather.day.hourly.humidity': 'नमी {n}%',
    'weather.day.hourly.sprayOk': 'स्प्रे ठीक',
    'weather.day.hourly.none': 'घंटेवार अनुमान अगले 2 दिन का ही मिलता है। यह दिन करीब आने पर यहां दिखेगा।',
    'weather.day.hourly.noneOld': 'पुराने अनुमान में इस दिन के घंटे नहीं हैं। ताज़ा करने पर यहां दिखेंगे।',
    'weather.day.empty.title': 'इस दिन का अनुमान नहीं है',
    'weather.day.empty.body': 'मौसम का अनुमान आज समेत 7 दिन का ही मिलता है।',
    'weather.day.past.title': 'यह दिन बीत चुका है',
    'weather.day.empty.today': 'आज का मौसम देखें',
    'weather.day.empty.overview': '7 दिन का मौसम देखें',
  },
  en: {
    'weather.title': 'Weather',
    'weather.place.change': 'Change location — now: {place}',
    'weather.place.action': 'Change location',

    'weather.hero.feelsLike': 'Feels like {temp}°C',
    'weather.hero.todayRange': 'Today {min}° to {max}°',
    'weather.hero.stale': 'As of {time}',
    'weather.hero.forecastNow': 'Forecast for this hour',
    'weather.hero.todayForecast': "Today's forecast",
    'weather.chip.humidity': '{n}% humidity',
    'weather.chip.wind': 'Wind {n} km/h',
    'weather.chip.windGust': 'Wind {n} km/h, gusts up to {g} km/h',
    'weather.chip.gust': 'Gusts up to {g} km/h',
    'weather.chip.rain': 'Rain {n}%',
    'weather.chip.rainToday': 'Chance of rain today {n}%',
    'weather.chip.rainMm': '{mm} mm rain',
    'weather.chip.aqi': 'AQI {value} · {level}',
    'weather.chip.uv': 'UV {n} · {level}',
    'weather.refreshFailed.title': 'Could not get fresh weather',
    'weather.refreshFailed.body': 'Showing information from {time}.',

    'weather.hourly.title': 'Next 24 hours',
    'weather.hourly.now': 'Now',
    'weather.hourly.item': '{time}: {temp}°C, {cond}, {pct}% chance of rain',
    'weather.hourly.empty': 'No hourly forecast right now. Try refreshing.',

    'weather.daily.title': '7-day forecast',
    'weather.daily.hint': 'Tap a day to see hourly weather and spraying times',
    'weather.daily.row': '{day}: {cond}. {pct}% chance of rain. Low {min}°, high {max}°.',
    'weather.daily.empty.title': 'The forecast is out of date',
    'weather.daily.empty.body': 'Turn on the internet and refresh to get a new forecast.',

    'weather.sprayCard.yes': 'Yes, you can spray today',
    'weather.sprayCard.no': 'Do not spray today',
    'weather.sprayCard.unsure': 'Cannot say for sure right now',
    'weather.sprayCard.best': 'Best time: {window}',
    'weather.sprayCard.next': 'Next good time: {window}',
    'weather.sprayCard.label': 'Always read the instructions on the pack and check the sky before spraying.',
    'weather.sprayCard.seeToday': "See all of today's good times",
    'weather.sprayCard.seeTomorrow': "See tomorrow's good times",
    'weather.sprayCard.hourlyToday': "See today's hourly weather",
    'weather.sprayCard.hourlyTomorrow': "See tomorrow's hourly weather",

    'weather.alerts.title': 'Weather warnings',
    'weather.alerts.none': 'No major weather warnings in the forecast right now.',
    'weather.alerts.urgent': 'Urgent',
    'weather.alerts.important': 'Take care',
    'weather.alerts.action': 'What to do:',

    'weather.tips.title': 'Farm advice for this weather',
    'weather.tips.subtitle': 'General advice based on the forecast',
    'weather.tip.thisDay': 'This day',
    'weather.tip.rain.title': '{when}: rain likely ({pct}%)',
    'weather.tip.rain.body': 'Hold off irrigation and spraying for now. Keep the field drainage open.',
    'weather.tip.wind.title': '{when}: strong wind — up to {speed} km/h',
    'weather.tip.wind.body': 'Do not spray, the spray will drift away. Support tall crops and climbers.',
    'weather.tip.heat.title': '{when}: hot — up to {temp}°C',
    'weather.tip.heat.body': 'Irrigate in the evening so less water evaporates. Spread straw or dry leaves on the soil (mulching) to keep moisture in.',
    'weather.tip.humidity.title': 'High humidity ({pct}%)',
    'weather.tip.humidity.body':
      'Fungal diseases (blight, rust, leaf spots) can spread. Check the leaves daily and use Crop Doctor if you see spots.',
    'weather.tip.fog.title': 'Fog expected',
    'weather.tip.fog.body': 'Leaves stay wet in fog — spray only after the sun is out. Watch potato and tomato for blight.',
    'weather.tip.cold.title': '{when}: cold morning — down to {temp}°C',
    'weather.tip.cold.body': 'Cover nurseries and young plants at night, irrigate lightly in the evening. Protect animals from the cold.',
    'weather.tip.dry.title': 'Little rain expected this week',
    'weather.tip.dry.body': 'Plan irrigation by checking soil moisture. Irrigate in the morning or evening.',
    'weather.tip.normal.title': 'The weather is fine for farm work',
    'weather.tip.normal.body': 'Plan essential work like weeding, irrigation and fertiliser.',
    'weather.tip.scout.title': 'Check your field regularly',
    'weather.tip.scout.body': 'Walk the field twice a week to look for pests and disease. Catching them early limits the damage.',

    'weather.sun.title': 'Sun and air',
    'weather.sun.sunrise': 'Sunrise',
    'weather.sun.sunset': 'Sunset',
    'weather.sun.uv': 'UV index',
    'weather.sun.aqi': 'Air (AQI)',
    'weather.uv.low': 'Low',
    'weather.uv.moderate': 'Moderate',
    'weather.uv.high': 'High',
    'weather.uv.veryHigh': 'Very high',
    'weather.uv.extreme': 'Extreme',
    'weather.uvHint.safe': 'Little risk from the sun',
    'weather.uvHint.moderate': 'Cover your head at midday',
    'weather.uvHint.high': 'Limit work in the sun from 11 AM to 3 PM',
    'weather.aqiHint.good': 'Air is fine for field work',
    'weather.aqiHint.warn': 'People with breathing problems should limit time outdoors',
    'weather.aqiHint.bad': 'Cover nose and mouth while working; do not burn stubble',

    'weather.speak.stale': 'This information is from {time}.',
    'weather.speak.now': 'In {place} it is now {temp} degrees, {cond}.',
    'weather.speak.hour': 'In {place} this hour is forecast at about {temp} degrees, {cond}.',
    'weather.speak.place': 'Weather in {place}.',
    'weather.speak.today': 'Today the high will be {max} and the low {min} degrees. Chance of rain is {pct} percent.',
    'weather.speak.alerts': 'Warnings: {titles}.',
    'weather.speak.spray': 'About spraying: {reason}',
    'weather.speak.day': '{day} in {place}: {cond}. High {max} and low {min} degrees, {pct} percent chance of rain.',
    'weather.speak.dayWindows': 'Good times to spray: {windows}.',
    'weather.speak.dayBest': 'The best of these: {window}.',
    'weather.speak.kmh': 'kilometres per hour',
    'weather.speak.deg': 'degrees',
    'weather.speak.mm': 'millimetres',
    'weather.speak.to': 'to',

    'weather.day.subtitle': 'Weather in {place}',
    'weather.day.pick': 'Choose a day',
    'weather.day.maxMin': 'High {max}°, low {min}°',
    'weather.day.sunTimes': 'Sunrise {rise} · Sunset {set}',
    'weather.day.alerts': 'Warnings for this day',
    'weather.day.spray.title': 'Good times to spray',
    'weather.day.spray.ideal': 'Best',
    'weather.day.spray.good': 'Good',
    'weather.day.spray.ok': 'OK',
    'weather.day.spray.facts': 'Wind {wind} km/h · up to {temp}°C · rain {pct}%',
    'weather.day.spray.calm': 'The air is almost still — use a coarse-droplet nozzle.',
    'weather.day.spray.breezy': 'A bit breezy — keep the nozzle close to the crop.',
    'weather.day.spray.none': 'No good time to spray on this day — {why}.',
    'weather.day.spray.passed': "Today's good spraying time has passed.",
    'weather.day.spray.noData': 'The hourly forecast for this day is not out yet. Spraying times appear here 1–2 days ahead.',
    'weather.day.spray.partial': 'The hourly forecast for the rest of this day is not out yet, so those hours were not checked.',
    'weather.day.spray.noDataOld': 'The old forecast does not cover the coming hours, so spraying times cannot be checked.',
    'weather.day.spray.partialOld': 'The old forecast does not cover the rest of this day, so those hours were not checked.',
    'weather.day.oldData': 'This forecast is old, so not all hours of this day are shown. Turn on the internet and refresh.',
    'weather.day.spray.rules':
      'A good time has no rain for the next {hours} hours, wind of {min}–{max} km/h (at most {limit}) and temperature no higher than {temp}°C.',
    'weather.day.tips.title': 'Farm advice for this day',
    'weather.day.hourly.title': 'Hourly weather',
    'weather.day.hourly.remaining': "Today's remaining hours",
    'weather.day.hourly.rain': 'Rain {pct}%',
    'weather.day.hourly.mm': '{mm} mm',
    'weather.day.hourly.wind': 'Wind {n} km/h',
    'weather.day.hourly.humidity': 'Humidity {n}%',
    'weather.day.hourly.sprayOk': 'OK to spray',
    'weather.day.hourly.none': 'The hourly forecast covers the next 2 days only. It will show here as this day gets closer.',
    'weather.day.hourly.noneOld': 'The old forecast has no hours for this day. They will show here after a refresh.',
    'weather.day.empty.title': 'No forecast for this day',
    'weather.day.empty.body': 'The forecast covers 7 days, starting today.',
    'weather.day.past.title': 'This day has passed',
    'weather.day.empty.today': "See today's weather",
    'weather.day.empty.overview': 'See the 7-day forecast',
  },
});
