// Strings for the soil health screens (prefix "soil."). Nutrient, status, pH-class, score and
// soil-type words are registered by services/soil.ts, so its label keys work anywhere.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';
import '../../services/soil';

registerStrings({
  hi: {
    'soil.title': 'मिट्टी जांच',
    'soil.subtitle': 'अपनी मिट्टी की सेहत जानें',

    // Form
    'soil.form.title': 'मिट्टी जांच कार्ड के मान',
    'soil.form.intro': 'अपने मृदा स्वास्थ्य कार्ड या लैब रिपोर्ट से मान भरें। कार्ड पर जितनी जांचें हैं, उतनी भरें — कम से कम 3।',
    'soil.form.farm': 'किस खेत की जांच है?',
    'soil.form.farmNone': 'कोई खास खेत नहीं',
    'soil.form.farmHint': 'खेत चुनने से रिपोर्ट उसी खेत के साथ सेव होगी',
    'soil.form.addFarm': 'अपना खेत जोड़ें',
    'soil.form.date': 'जांच की तारीख',
    'soil.form.dateHint': 'कार्ड पर लिखी नमूना या रिपोर्ट की तारीख',
    'soil.form.unit': 'कार्ड पर N, P, K किस इकाई में लिखे हैं?',
    'soil.form.hint': '{range} · अपने मिट्टी जांच कार्ड से भरें',
    'soil.form.rangePh': 'सामान्य: {low}–{high}',
    'soil.form.rangeMedium': 'मध्यम: {low}–{high} {unit}',
    'soil.form.soilType': 'मिट्टी का प्रकार',
    'soil.form.soilTypeHint': 'पता न हो तो "पता नहीं" चुनें',
    'soil.form.submit': 'स्कोर देखें',
    'soil.form.needMore': 'कम से कम 3 जांच के मान भरें (जैसे pH, नाइट्रोजन, फॉस्फोरस)।',
    'soil.form.fixErrors': 'कुछ मान ठीक नहीं लगते। लाल लिखे मान अपने कार्ड से दोबारा मिलाएं।',
    'soil.form.phRange': 'pH {min} से {max} के बीच होता है — कहीं दशमलव (.) तो नहीं छूटा? जैसे 6.5',
    'soil.form.ocRange': 'जैविक कार्बन {max}% से कम होता है — कहीं दशमलव (.) तो नहीं छूटा? जैसे 0.45',
    'soil.form.tooHigh': 'यह मान बहुत ज़्यादा लगता है — आमतौर पर {max} {unit} से कम होता है। कार्ड से दोबारा मिलाएं।',
    'soil.form.oldDate': 'यह जांच 2 साल से ज़्यादा पुरानी है। मिट्टी बदलती रहती है — नई जांच कराना अच्छा रहेगा।',
    'soil.form.clear': 'नई रिपोर्ट भरें',
    'soil.unit.ha': 'किलो/हेक्टेयर',
    'soil.unit.acre': 'किलो/एकड़',
    'soil.unit.haShort': 'किलो/हे.',
    'soil.unit.acreShort': 'किलो/एकड़',

    // Result
    'soil.result.title': 'मिट्टी स्वास्थ्य स्कोर',
    'soil.result.basis': '{total} में से {n} जांचों के आधार पर',
    'soil.result.how': 'स्कोर कैसे बनता है?',
    'soil.result.nutrients': 'पोषक तत्वों की स्थिति',
    'soil.result.changed': 'आपने मान बदले हैं। नया स्कोर देखने के लिए "स्कोर देखें" दबाएं।',
    'soil.result.reading': '{value} · {cls}',

    // AI
    'soil.ai.crop': 'किस फसल के लिए सुझाव चाहिए?',
    'soil.ai.cropHint': 'फसल चुनने से खाद के सुझाव ज़्यादा काम के होंगे',
    'soil.ai.general': 'सामान्य सुझाव (कोई खास फसल नहीं)',
    'soil.ai.button': 'AI सुझाव देखें',
    'soil.ai.saveOnly': 'सिर्फ रिपोर्ट सेव करें',
    'soil.ai.title': 'AI सुझाव',
    'soil.ai.actions': 'क्या करें',
    'soil.ai.organic': 'जैविक और सस्ते उपाय',
    'soil.ai.cautions': 'सावधानियां',
    'soil.ai.forCrops': 'इन फसलों के लिए: {crops}',
    'soil.ai.forGeneral': 'सामान्य सुझाव — कोई फसल नहीं चुनी',
    'soil.ai.regenerate': 'चुनी फसल के लिए नए सुझाव लें',
    'soil.ai.retryCrop': 'सुझाव दोबारा बनाएं',
    'soil.ai.loading': 'आपकी मिट्टी के हिसाब से सुझाव तैयार हो रहे हैं…',
    'soil.ai.previous': 'पिछली बार के सुझाव',
    'soil.ai.ctaTitle': 'इस रिपोर्ट पर AI सुझाव',
    'soil.ai.ctaBody': 'आपकी मिट्टी की जांच के हिसाब से खाद, खाद की बचत और मिट्टी सुधार के आम सुझाव।',
    'soil.ai.speechIntro': 'मिट्टी के लिए सुझाव।',
    'soil.ai.outdated': 'पुराने मानों वाले AI सुझाव छिपा दिए गए हैं — नया स्कोर देखकर फिर से सुझाव लें।',
    'soil.ai.offline': 'इंटरनेट चालू करके सुझाव देखें — रिपोर्ट फिर भी सेव हो जाएगी।',
    'soil.ai.unavailable': 'AI सुझाव अभी इस ऐप में चालू नहीं हैं — रिपोर्ट फिर भी सेव हो जाएगी।',
    'soil.ai.offlineShort': 'सुझाव देखने के लिए इंटरनेट चालू करें।',
    'soil.ai.unavailableShort': 'AI सुझाव अभी इस ऐप में चालू नहीं हैं।',

    // Saving
    'soil.saved': 'रिपोर्ट सेव हो गई',
    'soil.savedBody': 'यह रिपोर्ट नीचे "पिछली रिपोर्ट" में हमेशा मिलेगी।',
    'soil.savedView': 'रिपोर्ट देखें',

    // Past reports
    'soil.past.title': 'पिछली रिपोर्ट',
    'soil.past.score': 'स्कोर {score}/100 · {label}',
    'soil.past.list': 'सेव की गई मिट्टी रिपोर्ट',
    'soil.past.emptyTitle': 'अभी कोई रिपोर्ट सेव नहीं है',
    'soil.past.noScore': 'स्कोर नहीं बना — 3 से कम जांच के मान',
    'soil.past.emptyBody': 'ऊपर अपने कार्ड के मान भरें और स्कोर देखें। रिपोर्ट यहां सेव रहेगी।',
    'soil.past.emptyAction': 'मान भरना शुरू करें',

    // Where to test
    'soil.where.title': 'मिट्टी जांच कहाँ कराएं',
    'soil.where.body': 'नज़दीकी कृषि विभाग कार्यालय, मृदा परीक्षण प्रयोगशाला या कृषि विज्ञान केंद्र (KVK) में नमूना दें। सरकारी जांच आमतौर पर निःशुल्क या बहुत कम शुल्क पर होती है।',
    'soil.where.portal': 'मृदा स्वास्थ्य कार्ड पोर्टल',
    'soil.where.portalSub': 'अपना कार्ड देखें — soilhealth.dac.gov.in',
    'soil.where.kvk': 'नज़दीकी कृषि विज्ञान केंद्र (KVK)',
    'soil.where.kvkSub': 'राज्य और ज़िला चुनकर पता देखें — kvk.icar.gov.in',
    'soil.where.howTo': 'मिट्टी का नमूना कैसे लें',
    'soil.where.howToSub': 'आसान तरीका, चरण-दर-चरण',
    'soil.where.scheme': 'मृदा स्वास्थ्य कार्ड योजना',
    'soil.where.schemeSub': 'योजना की पूरी जानकारी',

    // "How the score works" sheet
    'soil.info.title': 'स्कोर कैसे बनता है?',
    'soil.info.weights': 'pH, जैविक कार्बन, नाइट्रोजन, फॉस्फोरस और पोटाश — पांचों को बराबर महत्व मिलता है।',
    'soil.info.points': 'नाइट्रोजन, फॉस्फोरस, पोटाश और जैविक कार्बन के नंबर: उचित (कार्ड पर "उच्च") = {high}, मध्यम = {medium}, कम = {low}।',
    'soil.info.phPoints': 'pH के नंबर, हर दायरे के लिए:',
    'soil.info.phBelow': '{v} से कम',
    'soil.info.phAbove': '{v} से ज़्यादा',
    'soil.info.phLine': '{range}: {cls} = {points}',
    'soil.info.missing': 'जो जांच नहीं भरीं, वे गिनती में नहीं आतीं। इसलिए कम से कम {min} जांच के मान ज़रूरी हैं।',
    'soil.info.bands': '{good} या उससे ज़्यादा = अच्छा, {medium} से {goodMinus} = मध्यम, {medium} से कम = कमज़ोर।',
    'soil.info.rangesTitle': 'मध्यम (ठीक-ठाक) दायरा',
    'soil.info.source': 'ये दायरे मृदा स्वास्थ्य कार्ड में इस्तेमाल होने वाले राष्ट्रीय मानकों पर आधारित हैं। आपके राज्य की प्रयोगशाला के दायरे थोड़े अलग हो सकते हैं — कार्ड पर लिखी रेटिंग को ही सही मानें।',
    'soil.info.micro': 'सल्फ़र, ज़िंक, बोरॉन जैसे सूक्ष्म तत्व और EC इस स्कोर में शामिल नहीं हैं — उनके लिए अपना कार्ड देखें।',
    'soil.info.units': 'कार्ड पर फॉस्फोरस P₂O₅ और पोटाश K₂O के रूप में लिखा होता है। अगर कार्ड पर किलो/एकड़ लिखा है तो ऊपर इकाई "किलो/एकड़" चुनें।',

    // Saved report
    'soil.report.title': 'मिट्टी रिपोर्ट',
    'soil.report.notFoundTitle': 'रिपोर्ट नहीं मिली',
    'soil.report.notFoundBody': 'हो सकता है यह रिपोर्ट हटा दी गई हो।',
    'soil.report.open': 'मिट्टी जांच खोलें',
    'soil.report.delete': 'यह रिपोर्ट हटाएं',
    'soil.report.deleteBody': 'यह रिपोर्ट और इसके AI सुझाव इस फ़ोन से हट जाएंगे।',
    'soil.report.deleted': 'रिपोर्ट हटा दी गई',
    'soil.report.soilType': 'मिट्टी का प्रकार',
    'soil.report.details': 'रिपोर्ट की जानकारी',
    'soil.report.farm': 'खेत',
    'soil.report.date': 'जांच की तारीख',
    'soil.report.newTest': 'नई जांच के मान भरें',
    'soil.report.savedTitle': 'मिट्टी रिपोर्ट — {date}',
    'soil.report.removedSaved': 'सेव से हटा दिया',

    // Share
    'soil.share.title': 'मिट्टी जांच रिपोर्ट ({date})',
    'soil.share.score': 'मिट्टी स्वास्थ्य स्कोर: {score}/100 ({label})',
    'soil.share.footer': '— किसान मित्र ऐप से',
  },
  en: {
    'soil.title': 'Soil test',
    'soil.subtitle': 'Know the health of your soil',
    'soil.form.title': 'Soil health card readings',
    'soil.form.intro': 'Enter the readings from your Soil Health Card or lab report. Fill in what the card shows — at least 3.',
    'soil.form.farm': 'Which field was tested?',
    'soil.form.farmNone': 'No particular field',
    'soil.form.farmHint': 'The report is saved with the chosen field',
    'soil.form.addFarm': 'Add your field',
    'soil.form.date': 'Test date',
    'soil.form.dateHint': 'The sample or report date printed on the card',
    'soil.form.unit': 'Which unit does the card use for N, P, K?',
    'soil.form.hint': '{range} · fill in from your soil health card',
    'soil.form.rangePh': 'Normal: {low}–{high}',
    'soil.form.rangeMedium': 'Medium: {low}–{high} {unit}',
    'soil.form.soilType': 'Soil type',
    'soil.form.soilTypeHint': 'Choose "Not sure" if you don\'t know',
    'soil.form.submit': 'See score',
    'soil.form.needMore': 'Enter at least 3 readings (for example pH, nitrogen and phosphorus).',
    'soil.form.fixErrors': 'Some values look wrong. Check the ones marked in red against your card.',
    'soil.form.phRange': 'pH is between {min} and {max} — did the decimal point get missed? For example 6.5',
    'soil.form.ocRange': 'Organic carbon is below {max}% — did the decimal point get missed? For example 0.45',
    'soil.form.tooHigh': 'This looks too high — it is usually below {max} {unit}. Check it against your card.',
    'soil.form.oldDate': 'This test is more than 2 years old. Soil changes over time — a new test is a good idea.',
    'soil.form.clear': 'Fill a new report',
    'soil.unit.ha': 'kg/hectare',
    'soil.unit.acre': 'kg/acre',
    'soil.unit.haShort': 'kg/ha',
    'soil.unit.acreShort': 'kg/acre',
    'soil.result.title': 'Soil health score',
    'soil.result.basis': 'Based on {n} of {total} readings',
    'soil.result.how': 'How is the score worked out?',
    'soil.result.nutrients': 'Nutrient status',
    'soil.result.changed': 'You changed the readings. Tap "See score" for the new score.',
    'soil.result.reading': '{value} · {cls}',
    'soil.ai.crop': 'Which crop do you want advice for?',
    'soil.ai.cropHint': 'Choosing a crop makes the fertilizer advice more useful',
    'soil.ai.general': 'General advice (no particular crop)',
    'soil.ai.button': 'See AI advice',
    'soil.ai.saveOnly': 'Only save the report',
    'soil.ai.title': 'AI advice',
    'soil.ai.actions': 'What to do',
    'soil.ai.organic': 'Organic and low-cost options',
    'soil.ai.cautions': 'Precautions',
    'soil.ai.forCrops': 'For these crops: {crops}',
    'soil.ai.forGeneral': 'General advice — no crop chosen',
    'soil.ai.regenerate': 'Get new advice for the chosen crop',
    'soil.ai.retryCrop': 'Make the advice again',
    'soil.ai.loading': 'Preparing advice for your soil…',
    'soil.ai.previous': 'Advice from last time',
    'soil.ai.ctaTitle': 'AI advice on this report',
    'soil.ai.ctaBody': 'General advice on fertilizer, savings and soil improvement based on your readings.',
    'soil.ai.speechIntro': 'Advice for your soil.',
    'soil.ai.outdated': 'The AI advice for the old values is hidden — see the new score, then ask again.',
    'soil.ai.offline': 'Turn on the internet to see advice — the report is saved anyway.',
    'soil.ai.unavailable': 'AI advice is not switched on in this app yet — the report is saved anyway.',
    'soil.ai.offlineShort': 'Turn on the internet to see advice.',
    'soil.ai.unavailableShort': 'AI advice is not switched on in this app yet.',
    'soil.saved': 'Report saved',
    'soil.savedBody': 'You will always find it below under "Past reports".',
    'soil.savedView': 'View report',
    'soil.past.title': 'Past reports',
    'soil.past.score': 'Score {score}/100 · {label}',
    'soil.past.list': 'Saved soil reports',
    'soil.past.noScore': 'No score — fewer than 3 readings',
    'soil.past.emptyTitle': 'No reports saved yet',
    'soil.past.emptyBody': 'Enter your card readings above and see the score. The report will be kept here.',
    'soil.past.emptyAction': 'Start entering readings',
    'soil.where.title': 'Where to get the soil tested',
    'soil.where.body': 'Give a sample at the nearest agriculture office, soil testing lab or Krishi Vigyan Kendra (KVK). Government tests are usually free or very cheap.',
    'soil.where.portal': 'Soil Health Card portal',
    'soil.where.portalSub': 'See your card — soilhealth.dac.gov.in',
    'soil.where.kvk': 'Nearest Krishi Vigyan Kendra (KVK)',
    'soil.where.kvkSub': 'Pick your state and district — kvk.icar.gov.in',
    'soil.where.howTo': 'How to take a soil sample',
    'soil.where.howToSub': 'Simple, step by step',
    'soil.where.scheme': 'Soil Health Card scheme',
    'soil.where.schemeSub': 'Full scheme details',
    'soil.info.title': 'How is the score worked out?',
    'soil.info.weights': 'pH, organic carbon, nitrogen, phosphorus and potash count equally.',
    'soil.info.points': 'Points for nitrogen, phosphorus, potash and organic carbon: sufficient (card says "High") = {high}, medium = {medium}, low = {low}.',
    'soil.info.phPoints': 'pH points for each range:',
    'soil.info.phBelow': 'below {v}',
    'soil.info.phAbove': 'above {v}',
    'soil.info.phLine': '{range}: {cls} = {points}',
    'soil.info.missing': 'Readings you leave empty are not counted, so at least {min} are needed.',
    'soil.info.bands': '{good} or more = good, {medium} to {goodMinus} = medium, below {medium} = weak.',
    'soil.info.rangesTitle': 'Medium (adequate) range',
    'soil.info.source': 'These ranges follow the national ratings used on Soil Health Cards. Your state lab may use slightly different limits — trust the rating printed on your card.',
    'soil.info.micro': 'Sulphur, zinc, boron and other micronutrients and EC are not part of this score — check your card for them.',
    'soil.info.units': 'Cards give phosphorus as P₂O₅ and potash as K₂O. If your card says kg/acre, choose "kg/acre" above.',
    'soil.report.title': 'Soil report',
    'soil.report.notFoundTitle': 'Report not found',
    'soil.report.notFoundBody': 'This report may have been deleted.',
    'soil.report.open': 'Open soil test',
    'soil.report.delete': 'Delete this report',
    'soil.report.deleteBody': 'This report and its AI advice will be removed from this phone.',
    'soil.report.deleted': 'Report deleted',
    'soil.report.soilType': 'Soil type',
    'soil.report.details': 'Report details',
    'soil.report.farm': 'Field',
    'soil.report.date': 'Test date',
    'soil.report.newTest': 'Enter a new test',
    'soil.report.savedTitle': 'Soil report — {date}',
    'soil.report.removedSaved': 'Removed from saved',
    'soil.share.title': 'Soil test report ({date})',
    'soil.share.score': 'Soil health score: {score}/100 ({label})',
    'soil.share.footer': '— from the Kisan Mitra app',
  },
});
