// Strings for the Profile tab: profile, my farms and settings (prefix "profile.").
// Help, privacy and terms live in help-strings.ts / legal-strings.ts so they load only with those screens.
// Shared words (save, cancel, acre…) come from common.*.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    // ---------- Profile ----------
    'profile.title': 'प्रोफाइल',
    'profile.farmer': 'किसान साथी',
    'profile.verified': 'Google खाते से जुड़ा',
    'profile.edit': 'प्रोफाइल बदलें',
    'profile.addPlace': 'गांव और ज़िला जोड़ें',
    'profile.settingsAria': 'सेटिंग्स खोलें',
    'profile.stats.aria': 'आपकी खेती एक नज़र में',
    'profile.stats.farms': 'खेत',
    'profile.stats.crops': 'फसलें',
    'profile.stats.land': 'कुल ज़मीन',
    'profile.group.farming': 'मेरी खेती',
    'profile.group.app': 'ऐप और सहायता',
    'profile.group.legal': 'नीतियां',
    'profile.menu.farms': 'मेरे खेत',
    'profile.menu.farmsSub': 'खेत जोड़ें, जगह और ज़मीन बदलें',
    'profile.menu.crops': 'मेरी फसलें',
    'profile.menu.cropsSub': 'बुवाई, अवस्था और रोज़ की सलाह',
    'profile.menu.saved': 'सेव की गई जानकारी',
    'profile.menu.savedSub': 'AI जवाब, योजनाएं और भाव',
    'profile.menu.hisab': 'खेती हिसाब',
    'profile.menu.hisabSub': 'खर्च, आय और मुनाफ़ा',
    'profile.menu.notifications': 'सूचनाएं',
    'profile.menu.notificationsSub': 'मौसम, मंडी और काम की याद',
    'profile.menu.unread': '{n} नई',
    'profile.menu.settings': 'सेटिंग्स',
    'profile.menu.settingsSub': 'आवाज़, अक्षर का आकार, सूचनाएं',
    'profile.menu.language': 'भाषा',
    'profile.menu.help': 'सहायता केंद्र',
    'profile.menu.helpSub': 'सवाल-जवाब और किसान कॉल सेंटर',
    'profile.menu.privacy': 'निजता नीति',
    'profile.menu.terms': 'नियम व शर्तें',
    'profile.version': 'संस्करण {v}',
    'profile.logout': 'लॉगआउट करें',
    'profile.logout.title': 'लॉगआउट करें?',
    'profile.logout.body':
      'लॉगआउट करने पर इस फ़ोन से आपकी सारी जानकारी हट जाएगी — खेत, फसलें, हिसाब और AI बातचीत भी। चाहें तो पहले सेटिंग्स में "मेरा डेटा डाउनलोड करें" से अपनी कॉपी रख लें।',
    'profile.logout.confirm': 'हाँ, लॉगआउट करें',

    // Edit sheet
    'profile.editSheet.desc': 'यह जानकारी सिर्फ़ इसी फ़ोन में रहती है',
    'profile.field.name': 'नाम',
    'profile.field.namePlaceholder': 'जैसे: रामेश्वर यादव',
    'profile.field.phone': 'मोबाइल नंबर',
    'profile.field.phoneError': 'सही 10 अंकों का मोबाइल नंबर लिखें',
    'profile.field.email': 'ईमेल',
    'profile.field.village': 'गांव',
    'profile.field.villagePlaceholder': 'जैसे: चोलापुर',
    'profile.field.district': 'ज़िला',
    'profile.field.districtPlaceholder': 'जैसे: वाराणसी',
    'profile.field.state': 'राज्य',
    'profile.field.stateNone': 'राज्य नहीं चुना',
    'profile.field.farmingType': 'खेती का तरीका',
    'profile.field.land': 'कुल ज़मीन',
    'profile.field.landFarms': 'कुल ज़मीन (सभी खेत मिलाकर)',
    'profile.field.landFarmsHint': 'ज़मीन हर खेत में अलग लिखी जाती है ({n} खेत)। बदलने के लिए "मेरे खेत" खोलें।',
    'profile.field.landFarmsEdit': 'मेरे खेत में बदलें',
    'profile.field.unit': 'ज़मीन की इकाई',
    'profile.error.name': 'अपना नाम लिखें',
    'profile.saved': 'प्रोफाइल सेव हो गई',

    'profile.farmingType.conventional': 'पारंपरिक',
    'profile.farmingType.conventionalDesc': 'रासायनिक खाद और दवा के साथ',
    'profile.farmingType.organic': 'जैविक',
    'profile.farmingType.organicDesc': 'गोबर खाद, वर्मी कम्पोस्ट',
    'profile.farmingType.natural': 'प्राकृतिक',
    'profile.farmingType.naturalDesc': 'जीवामृत, बीजामृत',
    'profile.farmingType.mixed': 'मिश्रित',
    'profile.farmingType.mixedDesc': 'दोनों तरीके साथ में',
    'profile.farmingType.badge': '{type} खेती',

    // Soil & irrigation labels (farms)
    'profile.soil.alluvial': 'जलोढ़ (कछारी)',
    'profile.soil.black': 'काली मिट्टी',
    'profile.soil.red': 'लाल मिट्टी',
    'profile.soil.laterite': 'लैटेराइट',
    'profile.soil.sandy': 'बलुई (रेतीली)',
    'profile.soil.clay': 'चिकनी (मटियार)',
    'profile.soil.loamy': 'दोमट',
    'profile.soil.unknown': 'पता नहीं',
    'profile.irrigation.canal': 'नहर',
    'profile.irrigation.tubewell': 'ट्यूबवेल / बोरवेल',
    'profile.irrigation.drip': 'ड्रिप',
    'profile.irrigation.sprinkler': 'स्प्रिंकलर (फव्वारा)',
    'profile.irrigation.rainfed': 'बारिश पर निर्भर',
    'profile.irrigation.pond': 'तालाब / कुआं',
    'profile.irrigation.other': 'अन्य',

    // ---------- My farms ----------
    'profile.farms.title': 'मेरे खेत',
    'profile.farms.subtitle': '{n} खेत • कुल {area}',
    'profile.farms.subtitleCount': '{n} खेत',
    'profile.farms.noArea': 'ज़मीन नहीं लिखी',
    'profile.farms.add': 'नया खेत जोड़ें',
    'profile.farms.listAria': 'आपके खेत',
    'profile.farms.empty.title': 'अभी कोई खेत नहीं जोड़ा',
    'profile.farms.empty.body': 'अपना खेत जोड़ें। फिर हर फसल को उसके खेत से जोड़ सकेंगे और सलाह व हिसाब ज़्यादा सही मिलेगा।',
    'profile.farms.cropsNone': 'अभी कोई फसल नहीं',
    'profile.farms.cropsOne': '1 फसल',
    'profile.farms.cropsMany': '{n} फसलें',
    'profile.farms.noPlace': 'जगह नहीं चुनी',
    'profile.farms.defaultName': 'खेत {n}',
    'profile.farms.tip': 'हर खेत की जगह और मिट्टी अलग लिखने से मौसम और खाद की सलाह ज़्यादा सटीक मिलती है।',
    'profile.farms.newTitle': 'नया खेत',
    'profile.farms.editTitle': 'खेत बदलें',
    'profile.farms.field.name': 'खेत का नाम',
    'profile.farms.field.namePlaceholder': 'जैसे: नहर वाला खेत',
    'profile.farms.field.place': 'खेत की जगह',
    'profile.farms.field.placeChoose': 'जगह चुनें',
    'profile.farms.field.placeHint': 'गांव या ज़िला चुनें — मौसम इसी जगह का दिखेगा',
    'profile.farms.field.placeAria': 'खेत की जगह बदलें, अभी: {place}',
    'profile.farms.placeSheet': 'खेत की जगह चुनें',
    'profile.farms.field.area': 'ज़मीन (क्षेत्रफल)',
    'profile.farms.field.soil': 'मिट्टी का प्रकार',
    'profile.farms.field.irrigation': 'सिंचाई का साधन',
    'profile.farms.bighaHint': 'आपका 1 बीघा = {sqm} वर्ग मीटर (सेटिंग्स में बदल सकते हैं)',
    'profile.farms.error.name': 'खेत का नाम लिखें',
    'profile.farms.error.area': 'ज़मीन कितनी है, लिखें',
    'profile.farms.prefilled': 'शुरुआत में दी गई जानकारी पहले से भर दी है। चाहें तो बदलें।',
    'profile.farms.saved': 'खेत सेव हो गया',
    'profile.farms.deleted': 'खेत हटा दिया गया',
    'profile.farms.delete': 'यह खेत हटाएं',
    'profile.farms.deleteBody': '"{name}" आपकी खेतों की सूची से हट जाएगा।',
    'profile.farms.blockedTitle': 'यह खेत अभी नहीं हट सकता',
    'profile.farms.blockedBody':
      'इस खेत से {n} फसल जुड़ी है। पहले "मेरी फसलें" में जाकर उस फसल का खेत बदलें या फसल हटाएं, फिर खेत हटाएं।',
    'profile.farms.blockedBodyMany':
      'इस खेत से {n} फसलें जुड़ी हैं। पहले "मेरी फसलें" में जाकर उन फसलों का खेत बदलें या उन्हें हटाएं, फिर खेत हटाएं।',
    'profile.farms.notFound': 'यह खेत नहीं मिला',
    'profile.farms.notFoundBody': 'हो सकता है यह पहले ही हटा दिया गया हो।',
    'profile.farms.backToList': 'मेरे खेत देखें',

    // ---------- Settings ----------
    'profile.settings.title': 'सेटिंग्स',
    'profile.settings.section.language': 'भाषा',
    'profile.settings.section.appearance': 'दिखावट',
    'profile.settings.section.voice': 'आवाज़',
    'profile.settings.section.notifications': 'सूचनाएं',
    'profile.settings.section.units': 'इकाई',
    'profile.settings.section.data': 'डेटा और निजता',
    'profile.settings.section.about': 'ऐप के बारे में',
    'profile.settings.language.row': 'ऐप की भाषा',
    'profile.settings.language.sub': 'AI के जवाब भी इसी भाषा में आएंगे',
    'profile.settings.darkMode': 'डार्क मोड',
    'profile.settings.darkModeDesc': 'रात में आंखों को आराम',
    'profile.settings.textSize': 'अक्षर का आकार',
    'profile.settings.textSize.normal': 'सामान्य',
    'profile.settings.textSize.large': 'बड़ा',
    'profile.settings.textSize.xlarge': 'बहुत बड़ा',
    'profile.settings.textSize.preview': 'नमूना: आज शाम 4–6 बजे स्प्रे के लिए अच्छा समय है।',
    'profile.settings.highContrast': 'हाई कंट्रास्ट',
    'profile.settings.highContrastDesc': 'धूप में पढ़ना आसान — अक्षर और लाइनें गहरी',
    'profile.settings.voice.row': 'पढ़कर सुनाने की आवाज़',
    'profile.settings.voice.default': 'अपने-आप (फ़ोन की आवाज़)',
    'profile.settings.voice.defaultDesc': 'फ़ोन में चुनी हुई आवाज़ इस्तेमाल होगी',
    'profile.settings.voice.sheet': 'आवाज़ चुनें',
    'profile.settings.voice.sheetDesc': '{lang} में पढ़कर सुनाने के लिए',
    'profile.settings.voice.numbered': 'आवाज़ {n}',
    'profile.settings.voice.offline': 'बिना इंटरनेट चलेगी',
    'profile.settings.voice.online': 'इंटरनेट चाहिए',
    'profile.settings.voice.loading': 'आवाज़ें खोज रहे हैं…',
    'profile.settings.voice.none':
      'इस फ़ोन में {lang} की कोई आवाज़ नहीं मिली। फ़ोन की सेटिंग → "Text-to-speech" में जाकर यह भाषा डाउनलोड करें।',
    'profile.settings.voice.test': 'आवाज़ सुनकर देखें',
    'profile.settings.voice.sample': 'नमस्ते! मैं किसान मित्र हूँ। आज शाम चार से छह बजे स्प्रे के लिए अच्छा समय है।',
    'profile.settings.voice.changed': 'आवाज़ बदल दी गई',
    'profile.settings.notif.master': 'सूचनाएं चालू रखें',
    'profile.settings.notif.masterDesc': 'ज़रूरी अलर्ट और काम की याद',
    'profile.settings.notif.weather': 'मौसम',
    'profile.settings.notif.weatherDesc': 'तेज़ बारिश, आंधी, पाला और लू की चेतावनी',
    'profile.settings.notif.crop': 'फसल',
    'profile.settings.notif.cropDesc': 'फसल की देखभाल और रोग से जुड़ी सलाह',
    'profile.settings.notif.mandi': 'मंडी',
    'profile.settings.notif.mandiDesc': 'आपकी फसलों के भाव में बड़ा बदलाव',
    'profile.settings.notif.government': 'सरकारी योजना',
    'profile.settings.notif.governmentDesc': 'नई योजना और आवेदन की आखिरी तारीख',
    'profile.settings.notif.reminders': 'काम की याद',
    'profile.settings.notif.remindersDesc': 'सिंचाई, खाद, स्प्रे जैसे कामों का रिमाइंडर',
    'profile.settings.notif.denied':
      'फ़ोन पर सूचना दिखाने की अनुमति नहीं मिली। ऐप के अंदर सूचनाएं मिलती रहेंगी; फ़ोन की सेटिंग से अनुमति दे सकते हैं।',
    'profile.settings.notif.offNote': 'सूचनाएं बंद हैं — मौसम की चेतावनी और काम की याद भी नहीं मिलेगी।',
    'profile.settings.units.bigha': 'आपके इलाके का बीघा',
    'profile.settings.units.bighaHint':
      'हर राज्य में बीघा का नाप अलग होता है। अपने इलाके का बीघा चुनें — खेत, कैलकुलेटर और हिसाब इसी से बनेंगे।',
    'profile.settings.units.custom': '1 बीघा = कितने वर्ग मीटर',
    'profile.settings.units.sqm': 'वर्ग मीटर',
    'profile.settings.units.customError': 'बीघा का नाप 100 से 10,000 वर्ग मीटर के बीच लिखें',
    'profile.settings.units.equals': '1 बीघा = {sqm} वर्ग मीटर ≈ {acre} एकड़',
    'profile.settings.data.explainer':
      'आपकी सारी जानकारी — प्रोफाइल, खेत, फसलें और हिसाब — इसी फ़ोन में सेव रहती है। AI से पूछने, मौसम और मंडी भाव के लिए सिर्फ़ ज़रूरी जानकारी इंटरनेट पर भेजी जाती है। हम आपका डेटा नहीं बेचते और ऐप में कोई विज्ञापन नहीं है।',
    'profile.settings.data.export': 'मेरा डेटा डाउनलोड करें',
    'profile.settings.data.exportDesc': 'सारी जानकारी एक फ़ाइल में (फोटो छोड़कर)',
    'profile.settings.data.shareTitle': 'किसान मित्र — मेरा डेटा',
    'profile.settings.data.exported': 'आपका डेटा तैयार है',
    'profile.settings.data.copied': 'डेटा कॉपी हो गया — इसे कहीं सुरक्षित जगह पेस्ट कर लें',
    'profile.settings.data.exportFailed': 'डेटा नहीं निकल पाया। दोबारा कोशिश करें।',
    'profile.settings.data.tooLarge': 'डेटा बहुत बड़ा है, इसलिए फ़ोन के शेयर से एक बार में नहीं भेजा जा सकता। आपकी जानकारी इस फ़ोन में सुरक्षित है।',
    'profile.settings.data.omitted': 'फ़ोन की शेयर सीमा के कारण इस कॉपी में ये शामिल नहीं हैं: {list}।',
    'profile.settings.data.omit.chatsTrimmed': 'AI बातचीत के पुराने संदेश',
    'profile.settings.data.omit.chats': 'AI बातचीत और फसल डॉक्टर की जांच',
    'profile.settings.data.omit.history': 'पुरानी सूचनाएं, भाव का इतिहास और खोजें',
    'profile.settings.data.delete': 'सारा डेटा हटाएं',
    'profile.settings.data.deleteDesc': 'इस फ़ोन से सब कुछ हमेशा के लिए हटाएं',
    'profile.settings.data.delete1Title': 'सारा डेटा हटाएं?',
    'profile.settings.data.delete1Body':
      'इस फ़ोन से आपकी प्रोफाइल, खेत, फसलें, हिसाब, मिट्टी रिपोर्ट, सेव की गई जानकारी और AI बातचीत हमेशा के लिए हट जाएगी।',
    'profile.settings.data.delete2Title': 'पक्का हटाना है?',
    'profile.settings.data.delete2Body': 'हटाया गया डेटा वापस नहीं आएगा। इसके बाद ऐप शुरू से खुलेगा।',
    'profile.settings.data.delete2Confirm': 'हाँ, सब हटाएं',
    'profile.settings.data.policy': 'पूरी निजता नीति पढ़ें',
    'profile.settings.about.name': 'किसान मित्र',
    'profile.settings.about.tagline': 'खेती की हर समस्या का समाधान',
    'profile.settings.about.madeFor': 'भारत के किसानों के लिए, हिंदी में',
  },
  en: {
    // ---------- Profile ----------
    'profile.title': 'Profile',
    'profile.farmer': 'Farmer',
    'profile.verified': 'Linked to Google account',
    'profile.edit': 'Edit profile',
    'profile.addPlace': 'Add village and district',
    'profile.settingsAria': 'Open settings',
    'profile.stats.aria': 'Your farming at a glance',
    'profile.stats.farms': 'Farms',
    'profile.stats.crops': 'Crops',
    'profile.stats.land': 'Total land',
    'profile.group.farming': 'My farming',
    'profile.group.app': 'App & help',
    'profile.group.legal': 'Policies',
    'profile.menu.farms': 'My farms',
    'profile.menu.farmsSub': 'Add farms, change place and area',
    'profile.menu.crops': 'My crops',
    'profile.menu.cropsSub': 'Sowing, stage and daily advice',
    'profile.menu.saved': 'Saved information',
    'profile.menu.savedSub': 'AI answers, schemes and prices',
    'profile.menu.hisab': 'Farm accounts',
    'profile.menu.hisabSub': 'Expenses, income and profit',
    'profile.menu.notifications': 'Notifications',
    'profile.menu.notificationsSub': 'Weather, mandi and task reminders',
    'profile.menu.unread': '{n} new',
    'profile.menu.settings': 'Settings',
    'profile.menu.settingsSub': 'Voice, text size, notifications',
    'profile.menu.language': 'Language',
    'profile.menu.help': 'Help centre',
    'profile.menu.helpSub': 'FAQs and Kisan Call Centre',
    'profile.menu.privacy': 'Privacy policy',
    'profile.menu.terms': 'Terms & conditions',
    'profile.version': 'Version {v}',
    'profile.logout': 'Log out',
    'profile.logout.title': 'Log out?',
    'profile.logout.body':
      'Logging out removes all your information from this phone — farms, crops, accounts and AI chats too. If you like, first keep a copy with "Download my data" in Settings.',
    'profile.logout.confirm': 'Yes, log out',

    'profile.editSheet.desc': 'This information stays only on this phone',
    'profile.field.name': 'Name',
    'profile.field.namePlaceholder': 'e.g. Rameshwar Yadav',
    'profile.field.phone': 'Mobile number',
    'profile.field.phoneError': 'Enter a valid 10-digit mobile number',
    'profile.field.email': 'Email',
    'profile.field.village': 'Village',
    'profile.field.villagePlaceholder': 'e.g. Cholapur',
    'profile.field.district': 'District',
    'profile.field.districtPlaceholder': 'e.g. Varanasi',
    'profile.field.state': 'State',
    'profile.field.stateNone': 'No state chosen',
    'profile.field.farmingType': 'Farming method',
    'profile.field.land': 'Total land',
    'profile.field.landFarms': 'Total land (all farms)',
    'profile.field.landFarmsHint': 'Land is recorded for each farm ({n} farms). Open "My farms" to change it.',
    'profile.field.landFarmsEdit': 'Change in My farms',
    'profile.field.unit': 'Land unit',
    'profile.error.name': 'Enter your name',
    'profile.saved': 'Profile saved',

    'profile.farmingType.conventional': 'Conventional',
    'profile.farmingType.conventionalDesc': 'With chemical fertilisers and sprays',
    'profile.farmingType.organic': 'Organic',
    'profile.farmingType.organicDesc': 'Farmyard manure, vermicompost',
    'profile.farmingType.natural': 'Natural',
    'profile.farmingType.naturalDesc': 'Jeevamrit, beejamrit',
    'profile.farmingType.mixed': 'Mixed',
    'profile.farmingType.mixedDesc': 'Both methods together',
    'profile.farmingType.badge': '{type} farming',

    'profile.soil.alluvial': 'Alluvial',
    'profile.soil.black': 'Black soil',
    'profile.soil.red': 'Red soil',
    'profile.soil.laterite': 'Laterite',
    'profile.soil.sandy': 'Sandy',
    'profile.soil.clay': 'Clay',
    'profile.soil.loamy': 'Loamy',
    'profile.soil.unknown': 'Not sure',
    'profile.irrigation.canal': 'Canal',
    'profile.irrigation.tubewell': 'Tubewell / borewell',
    'profile.irrigation.drip': 'Drip',
    'profile.irrigation.sprinkler': 'Sprinkler',
    'profile.irrigation.rainfed': 'Rain-fed',
    'profile.irrigation.pond': 'Pond / well',
    'profile.irrigation.other': 'Other',

    // ---------- My farms ----------
    'profile.farms.title': 'My farms',
    'profile.farms.subtitle': '{n} farms • {area} in total',
    'profile.farms.subtitleCount': '{n} farms',
    'profile.farms.noArea': 'Land not entered',
    'profile.farms.add': 'Add a farm',
    'profile.farms.listAria': 'Your farms',
    'profile.farms.empty.title': 'No farm added yet',
    'profile.farms.empty.body': 'Add your farm. Then you can link each crop to its farm and get more accurate advice and accounts.',
    'profile.farms.cropsNone': 'No crops yet',
    'profile.farms.cropsOne': '1 crop',
    'profile.farms.cropsMany': '{n} crops',
    'profile.farms.noPlace': 'Place not chosen',
    'profile.farms.defaultName': 'Farm {n}',
    'profile.farms.tip': 'Recording the place and soil of each farm makes weather and fertiliser advice more accurate.',
    'profile.farms.newTitle': 'New farm',
    'profile.farms.editTitle': 'Edit farm',
    'profile.farms.field.name': 'Farm name',
    'profile.farms.field.namePlaceholder': 'e.g. Canal-side field',
    'profile.farms.field.place': 'Farm location',
    'profile.farms.field.placeChoose': 'Choose place',
    'profile.farms.field.placeHint': 'Choose the village or district — weather will be shown for this place',
    'profile.farms.field.placeAria': 'Change farm location, now: {place}',
    'profile.farms.placeSheet': 'Choose farm location',
    'profile.farms.field.area': 'Land (area)',
    'profile.farms.field.soil': 'Soil type',
    'profile.farms.field.irrigation': 'Irrigation source',
    'profile.farms.bighaHint': 'Your 1 bigha = {sqm} m² (you can change this in Settings)',
    'profile.farms.error.name': 'Enter the farm name',
    'profile.farms.error.area': 'Enter how much land it is',
    'profile.farms.prefilled': 'Details you gave at the start are filled in. Change them if needed.',
    'profile.farms.saved': 'Farm saved',
    'profile.farms.deleted': 'Farm deleted',
    'profile.farms.delete': 'Delete this farm',
    'profile.farms.deleteBody': '"{name}" will be removed from your list of farms.',
    'profile.farms.blockedTitle': 'This farm cannot be deleted yet',
    'profile.farms.blockedBody':
      '{n} crop is linked to this farm. First open "My crops" and move that crop to another farm or delete it, then delete the farm.',
    'profile.farms.blockedBodyMany':
      '{n} crops are linked to this farm. First open "My crops" and move those crops to another farm or delete them, then delete the farm.',
    'profile.farms.notFound': 'Farm not found',
    'profile.farms.notFoundBody': 'It may already have been deleted.',
    'profile.farms.backToList': 'See my farms',

    // ---------- Settings ----------
    'profile.settings.title': 'Settings',
    'profile.settings.section.language': 'Language',
    'profile.settings.section.appearance': 'Appearance',
    'profile.settings.section.voice': 'Voice',
    'profile.settings.section.notifications': 'Notifications',
    'profile.settings.section.units': 'Units',
    'profile.settings.section.data': 'Data & privacy',
    'profile.settings.section.about': 'About the app',
    'profile.settings.language.row': 'App language',
    'profile.settings.language.sub': 'AI answers will also come in this language',
    'profile.settings.darkMode': 'Dark mode',
    'profile.settings.darkModeDesc': 'Easier on the eyes at night',
    'profile.settings.textSize': 'Text size',
    'profile.settings.textSize.normal': 'Normal',
    'profile.settings.textSize.large': 'Large',
    'profile.settings.textSize.xlarge': 'Extra large',
    'profile.settings.textSize.preview': 'Sample: this evening, 4–6 PM is a good time to spray.',
    'profile.settings.highContrast': 'High contrast',
    'profile.settings.highContrastDesc': 'Easier to read in sunlight — darker text and lines',
    'profile.settings.voice.row': 'Read-aloud voice',
    'profile.settings.voice.default': 'Automatic (phone voice)',
    'profile.settings.voice.defaultDesc': 'Uses the voice chosen on your phone',
    'profile.settings.voice.sheet': 'Choose a voice',
    'profile.settings.voice.sheetDesc': 'For reading aloud in {lang}',
    'profile.settings.voice.numbered': 'Voice {n}',
    'profile.settings.voice.offline': 'Works without internet',
    'profile.settings.voice.online': 'Needs internet',
    'profile.settings.voice.loading': 'Looking for voices…',
    'profile.settings.voice.none':
      'No {lang} voice was found on this phone. Download the language in your phone settings → "Text-to-speech".',
    'profile.settings.voice.test': 'Test the voice',
    'profile.settings.voice.sample': 'Hello! I am Kisan Mitra. This evening, four to six PM is a good time to spray.',
    'profile.settings.voice.changed': 'Voice changed',
    'profile.settings.notif.master': 'Keep notifications on',
    'profile.settings.notif.masterDesc': 'Important alerts and task reminders',
    'profile.settings.notif.weather': 'Weather',
    'profile.settings.notif.weatherDesc': 'Heavy rain, storm, frost and heatwave warnings',
    'profile.settings.notif.crop': 'Crops',
    'profile.settings.notif.cropDesc': 'Crop care and disease advice',
    'profile.settings.notif.mandi': 'Mandi',
    'profile.settings.notif.mandiDesc': 'Big price changes for your crops',
    'profile.settings.notif.government': 'Government schemes',
    'profile.settings.notif.governmentDesc': 'New schemes and last dates to apply',
    'profile.settings.notif.reminders': 'Task reminders',
    'profile.settings.notif.remindersDesc': 'Reminders for irrigation, fertiliser, spraying',
    'profile.settings.notif.denied':
      'Permission to show notifications on the phone was not given. In-app notifications will continue; you can allow it in phone settings.',
    'profile.settings.notif.offNote': 'Notifications are off — you will not get weather warnings or task reminders.',
    'profile.settings.units.bigha': 'Bigha in your area',
    'profile.settings.units.bighaHint':
      'The size of a bigha differs from state to state. Choose the bigha used in your area — farms, calculators and accounts will use it.',
    'profile.settings.units.custom': '1 bigha = how many square metres',
    'profile.settings.units.sqm': 'm²',
    'profile.settings.units.customError': 'Enter a bigha size between 100 and 10,000 m²',
    'profile.settings.units.equals': '1 bigha = {sqm} m² ≈ {acre} acre',
    'profile.settings.data.explainer':
      'All your information — profile, farms, crops and accounts — is saved on this phone. Only what is needed is sent over the internet to ask the AI and to get weather and mandi prices. We do not sell your data and there are no ads in the app.',
    'profile.settings.data.export': 'Download my data',
    'profile.settings.data.exportDesc': 'All your information in one file (without photos)',
    'profile.settings.data.shareTitle': 'Kisan Mitra — my data',
    'profile.settings.data.exported': 'Your data is ready',
    'profile.settings.data.copied': 'Data copied — paste it somewhere safe',
    'profile.settings.data.exportFailed': 'Could not export the data. Please try again.',
    'profile.settings.data.tooLarge': 'Your data is too large to share from the phone in one go. Your information is safe on this phone.',
    'profile.settings.data.omitted': 'Because of the phone’s share limit, this copy leaves out: {list}.',
    'profile.settings.data.omit.chatsTrimmed': 'older AI chat messages',
    'profile.settings.data.omit.chats': 'AI chats and Crop Doctor checks',
    'profile.settings.data.omit.history': 'old notifications, price history and searches',
    'profile.settings.data.delete': 'Delete all data',
    'profile.settings.data.deleteDesc': 'Permanently remove everything from this phone',
    'profile.settings.data.delete1Title': 'Delete all data?',
    'profile.settings.data.delete1Body':
      'Your profile, farms, crops, accounts, soil reports, saved information and AI chats will be permanently removed from this phone.',
    'profile.settings.data.delete2Title': 'Are you sure?',
    'profile.settings.data.delete2Body': 'Deleted data cannot be brought back. The app will start again from the beginning.',
    'profile.settings.data.delete2Confirm': 'Yes, delete everything',
    'profile.settings.data.policy': 'Read the full privacy policy',
    'profile.settings.about.name': 'Kisan Mitra',
    'profile.settings.about.tagline': 'A solution for every farming problem',
    'profile.settings.about.madeFor': "For India's farmers, in Hindi first",
  },
});
