// Strings for the farmer community (prefix "community."). Error messages (community.error.*)
// are registered by services/community.ts. Shared words come from common.*.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'community.title': 'किसान समुदाय',
    'community.subtitle': 'सवाल पूछें, अनुभव बांटें',
    'community.verified': 'विशेषज्ञ द्वारा सत्यापित',
    'community.expert': 'विशेषज्ञ',
    'community.farmer': 'किसान साथी',

    // Coming-soon preview
    'community.soon.title': 'किसान समुदाय जल्द आ रहा है',
    'community.soon.body':
      'यहां आप दूसरे किसानों से सवाल पूछ सकेंगे, अपना अनुभव बांट सकेंगे और विशेषज्ञों के जांचे हुए जवाब पा सकेंगे।',
    'community.soon.features': 'क्या-क्या कर पाएंगे',
    'community.soon.f.ask': 'सवाल पूछें',
    'community.soon.f.askDesc': 'लिखकर या बोलकर, अपनी भाषा में',
    'community.soon.f.photo': 'फसल की फोटो डालें',
    'community.soon.f.photoDesc': 'रोग या कीट दिखाकर राय लें',
    'community.soon.f.cropGroups': 'फसल समूह',
    'community.soon.f.cropGroupsDesc': 'गेहूं, धान, सब्ज़ी — हर फसल का अलग समूह',
    'community.soon.f.localGroups': 'अपने इलाके का समूह',
    'community.soon.f.localGroupsDesc': 'आसपास के किसानों से मौसम और भाव की बात',
    'community.soon.f.verified': 'विशेषज्ञ के जवाब',
    'community.soon.f.verifiedDesc': 'जांचे हुए जवाब पर साफ़ निशान लगा होगा',
    'community.soon.f.actions': 'पसंद, सेव और रिपोर्ट',
    'community.soon.f.actionsDesc': 'काम की पोस्ट सेव करें, गलत सलाह की रिपोर्ट करें',
    'community.soon.whyTitle': 'अभी शुरू क्यों नहीं?',
    'community.soon.whyBody':
      'गलत सलाह से फसल और पैसे दोनों का नुकसान हो सकता है। इसलिए समुदाय तभी शुरू होगा जब हर पोस्ट की निगरानी और विशेषज्ञ जवाबों की जांच की पूरी व्यवस्था तैयार हो जाएगी।',
    'community.help.title': 'अभी मदद चाहिए?',
    'community.help.ai': 'AI किसान मित्र से पूछें',
    'community.help.aiDesc': 'अभी, किसी भी समय — लिखकर, बोलकर या फोटो भेजकर',
    'community.help.aiButton': 'AI से पूछें',

    // Full UI (behind FEATURES.community)
    'community.tabs': 'पोस्ट दिखाएं',
    'community.tab.all': 'सभी पोस्ट',
    'community.tab.groups': 'मेरे समूह',
    'community.tab.experts': 'विशेषज्ञ',
    'community.filter': 'फसल के हिसाब से',
    'community.filter.all': 'सभी फसलें',
    'community.note': 'समुदाय के जवाब किसानों के अपने अनुभव हैं। सिर्फ़ "विशेषज्ञ द्वारा सत्यापित" जवाब जांचे हुए हैं।',
    'community.ask': 'सवाल पूछें',
    'community.empty.all': 'अभी कोई पोस्ट नहीं',
    'community.empty.allBody': 'पहला सवाल आप पूछें — दूसरे किसान और विशेषज्ञ जवाब देंगे।',
    'community.empty.groups': 'आपके समूहों में अभी कोई पोस्ट नहीं',
    'community.empty.groupsBody': 'अपनी फसल या इलाके के समूह से जुड़ें और आसपास के किसानों की पोस्ट देखें।',
    'community.empty.experts': 'अभी कोई सत्यापित जवाब नहीं',
    'community.empty.expertsBody': 'विशेषज्ञ के जांचे हुए जवाब यहां दिखेंगे।',
    'community.loadMore': 'और पोस्ट देखें',
    'community.like': 'पसंद करें',
    'community.likes': '{n} पसंद',
    'community.likeAria': 'पसंद करें, अभी {n} पसंद',
    'community.unlikeAria': 'पसंद हटाएं, अभी {n} पसंद',
    'community.save': 'सेव करें',
    'community.savedLabel': 'सेव है',
    'community.saveAria': 'पोस्ट सेव करें',
    'community.unsaveAria': 'पोस्ट सेव से हटाएं',
    'community.report': 'रिपोर्ट करें',
    'community.reportAria': 'इस पोस्ट की रिपोर्ट करें',
    'community.reportReplyAria': 'इस जवाब की रिपोर्ट करें',
    'community.report.title': 'रिपोर्ट क्यों कर रहे हैं?',
    'community.report.desc': 'आपकी रिपोर्ट गुमनाम रहेगी',
    'community.report.reason.wrong-advice': 'गलत या खतरनाक सलाह',
    'community.report.reason.spam': 'विज्ञापन या फालतू पोस्ट',
    'community.report.reason.abusive': 'गाली या बुरा बर्ताव',
    'community.report.reason.personal-info': 'किसी की निजी जानकारी',
    'community.report.reason.other': 'कुछ और',
    'community.report.send': 'रिपोर्ट भेजें',
    'community.report.done': 'धन्यवाद! हमारी टीम इसकी जांच करेगी।',
    'community.openPost': '{name} की पोस्ट खोलें',
    'community.photoAlt': 'किसान की भेजी फसल की फोटो',
    'community.answeredBy': 'जवाब: {name}',

    // Post detail
    'community.post.title': 'पोस्ट',
    'community.replies': 'जवाब ({n})',
    'community.noReplies': 'अभी कोई जवाब नहीं आया',
    'community.noRepliesBody': 'जवाब आने पर यहां दिखेंगे। आप भी अपना अनुभव लिख सकते हैं।',
    'community.reply.label': 'आपका जवाब',
    'community.reply.placeholder': 'अपना अनुभव या सलाह लिखें…',
    'community.reply.send': 'जवाब भेजें',
    'community.reply.sent': 'जवाब भेज दिया गया',
    'community.reply.short': 'जवाब थोड़ा और लिखें',
    'community.backToList': 'सभी पोस्ट देखें',

    // Compose
    'community.compose.title': 'सवाल पूछें',
    'community.compose.desc': 'साफ़ लिखें कि कौन-सी फसल है और क्या दिक्कत दिख रही है',
    'community.compose.text': 'आपका सवाल',
    'community.compose.placeholder': 'जैसे: गेहूं की पत्तियां पीली हो रही हैं, क्या करें?',
    'community.compose.crop': 'फसल',
    'community.compose.photo': 'फोटो जोड़ें',
    'community.compose.photoChange': 'फोटो बदलें',
    'community.compose.photoRemove': 'फोटो हटाएं',
    'community.compose.photoHeader': 'फसल की फोटो',
    'community.compose.camera': 'कैमरा',
    'community.compose.gallery': 'गैलरी',
    'community.compose.photoError': 'फोटो नहीं ले पाए। दोबारा कोशिश करें।',
    'community.compose.rules': 'अपना फ़ोन नंबर, पता, आधार या बैंक जानकारी न लिखें। सबसे इज़्ज़त से बात करें।',
    'community.compose.post': 'पोस्ट करें',
    'community.compose.posted': 'आपका सवाल पोस्ट हो गया',
    'community.compose.tooShort': 'सवाल कम से कम 10 अक्षर का लिखें',
  },
  en: {
    'community.title': 'Farmer community',
    'community.subtitle': 'Ask questions, share experience',
    'community.verified': 'Verified by expert',
    'community.expert': 'Expert',
    'community.farmer': 'Farmer',

    'community.soon.title': 'Farmer community is coming soon',
    'community.soon.body':
      'Here you will be able to ask other farmers questions, share your experience and get answers checked by experts.',
    'community.soon.features': 'What you will be able to do',
    'community.soon.f.ask': 'Ask questions',
    'community.soon.f.askDesc': 'Type or speak, in your own language',
    'community.soon.f.photo': 'Add a crop photo',
    'community.soon.f.photoDesc': 'Show the disease or pest and get opinions',
    'community.soon.f.cropGroups': 'Crop groups',
    'community.soon.f.cropGroupsDesc': 'Wheat, paddy, vegetables — a group for each crop',
    'community.soon.f.localGroups': 'Your local group',
    'community.soon.f.localGroupsDesc': 'Talk weather and prices with nearby farmers',
    'community.soon.f.verified': 'Expert answers',
    'community.soon.f.verifiedDesc': 'Checked answers will carry a clear mark',
    'community.soon.f.actions': 'Like, save and report',
    'community.soon.f.actionsDesc': 'Save useful posts, report wrong advice',
    'community.soon.whyTitle': 'Why not now?',
    'community.soon.whyBody':
      'Wrong advice can cost both crops and money. So the community will start only when moderation of every post and checking of expert answers is fully in place.',
    'community.help.title': 'Need help now?',
    'community.help.ai': 'Ask AI Kisan Mitra',
    'community.help.aiDesc': 'Now, any time — type, speak or send a photo',
    'community.help.aiButton': 'Ask the AI',

    'community.tabs': 'Show posts',
    'community.tab.all': 'All posts',
    'community.tab.groups': 'My groups',
    'community.tab.experts': 'Experts',
    'community.filter': 'By crop',
    'community.filter.all': 'All crops',
    'community.note': 'Community answers are farmers’ own experience. Only answers marked "Verified by expert" have been checked.',
    'community.ask': 'Ask a question',
    'community.empty.all': 'No posts yet',
    'community.empty.allBody': 'Ask the first question — other farmers and experts will answer.',
    'community.empty.groups': 'No posts in your groups yet',
    'community.empty.groupsBody': 'Join your crop or area group to see posts from nearby farmers.',
    'community.empty.experts': 'No verified answers yet',
    'community.empty.expertsBody': 'Answers checked by experts will appear here.',
    'community.loadMore': 'See more posts',
    'community.like': 'Like',
    'community.likes': '{n} likes',
    'community.likeAria': 'Like, {n} likes so far',
    'community.unlikeAria': 'Remove like, {n} likes so far',
    'community.save': 'Save',
    'community.savedLabel': 'Saved',
    'community.saveAria': 'Save post',
    'community.unsaveAria': 'Remove post from saved',
    'community.report': 'Report',
    'community.reportAria': 'Report this post',
    'community.reportReplyAria': 'Report this answer',
    'community.report.title': 'Why are you reporting this?',
    'community.report.desc': 'Your report stays anonymous',
    'community.report.reason.wrong-advice': 'Wrong or dangerous advice',
    'community.report.reason.spam': 'Advertising or spam',
    'community.report.reason.abusive': 'Abuse or bad behaviour',
    'community.report.reason.personal-info': "Someone's private information",
    'community.report.reason.other': 'Something else',
    'community.report.send': 'Send report',
    'community.report.done': 'Thank you! Our team will check it.',
    'community.openPost': 'Open post by {name}',
    'community.photoAlt': 'Crop photo sent by a farmer',
    'community.answeredBy': 'Answer: {name}',

    'community.post.title': 'Post',
    'community.replies': 'Answers ({n})',
    'community.noReplies': 'No answers yet',
    'community.noRepliesBody': 'Answers will appear here. You can also share your experience.',
    'community.reply.label': 'Your answer',
    'community.reply.placeholder': 'Write your experience or advice…',
    'community.reply.send': 'Send answer',
    'community.reply.sent': 'Answer sent',
    'community.reply.short': 'Please write a little more',
    'community.backToList': 'See all posts',

    'community.compose.title': 'Ask a question',
    'community.compose.desc': 'Say clearly which crop it is and what problem you see',
    'community.compose.text': 'Your question',
    'community.compose.placeholder': 'e.g. Wheat leaves are turning yellow, what should I do?',
    'community.compose.crop': 'Crop',
    'community.compose.photo': 'Add photo',
    'community.compose.photoChange': 'Change photo',
    'community.compose.photoRemove': 'Remove photo',
    'community.compose.photoHeader': 'Crop photo',
    'community.compose.camera': 'Camera',
    'community.compose.gallery': 'Gallery',
    'community.compose.photoError': 'Could not get the photo. Please try again.',
    'community.compose.rules': 'Do not write your phone number, address, Aadhaar or bank details. Be respectful to everyone.',
    'community.compose.post': 'Post',
    'community.compose.posted': 'Your question has been posted',
    'community.compose.tooShort': 'Write at least 10 characters',
  },
});
