// Strings for the "My crops" module (prefix "crops."). Hindi first; English mirrors it.
// Shared words (save, retry, today, units, disclaimers) come from common.* in lib/common-strings.ts.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    // ---- My crops (list) ----
    'crops.title': 'मेरी फसलें',
    'crops.count.one': '1 फसल',
    'crops.count': '{n} फसलें',
    'crops.add': 'नई फसल जोड़ें',
    'crops.totalArea': 'कुल ज़मीन: {area}',
    'crops.totalAreaApprox': 'कुल ज़मीन: लगभग {area}',
    'crops.listLabel': 'फसलों की सूची',
    'crops.noFarm': 'बिना खेत वाली फसलें',
    'crops.sown': 'बुवाई: {date}',
    'crops.transplanted': 'रोपाई: {date}',
    'crops.nurserySown': 'नर्सरी बुवाई: {date}',
    'crops.noSowingDate': 'बुवाई की तारीख नहीं डाली',
    'crops.noTransplantDate': 'रोपाई की तारीख नहीं डाली',
    'crops.currentStage': 'वर्तमान अवस्था: {stage}',
    'crops.stageWithSuffix': '{stage} अवस्था',
    'crops.empty.title': 'अभी कोई फसल नहीं जोड़ी',
    'crops.empty.body': 'अपनी फसल जोड़ें। बुवाई की तारीख से हम रोज़ की सलाह, काम का कैलेंडर और मौसम की चेतावनी देंगे।',

    // Area in each unit (Hindi has no plural change)
    'crops.area.acre': '{n} एकड़',
    'crops.area.one.acre': '{n} एकड़',
    'crops.area.bigha': '{n} बीघा',
    'crops.area.one.bigha': '{n} बीघा',
    'crops.area.hectare': '{n} हेक्टेयर',
    'crops.area.one.hectare': '{n} हेक्टेयर',
    'crops.area.notSet': 'रकबा नहीं डाला',
    // Joins sentences for read-aloud and sharing
    'crops.sep': '। ',

    // Day words used in weather risk lines
    'crops.when.today': 'आज',
    'crops.when.tomorrow': 'कल',
    'crops.when.on': '{date} को',

    // ---- Add / edit form ----
    'crops.add.title': 'नई फसल जोड़ें',
    'crops.add.subtitle': 'फसल, ज़मीन और बुवाई की तारीख',
    'crops.edit.title': 'फसल की जानकारी बदलें',
    'crops.form.whichCrop': 'कौन सी फसल लगाई है?',
    'crops.form.whichCropHint': 'फसल की तस्वीर पर टैप करें',
    'crops.form.other': 'अन्य फसल',
    'crops.form.otherHint': 'सूची में नहीं है? नाम लिखकर जोड़ें',
    'crops.form.change': 'बदलें',
    'crops.form.changeCrop': 'फसल बदलें',
    'crops.form.keepCrop': 'यही फसल रखें',
    'crops.form.otherName': 'फसल का नाम',
    'crops.form.otherNamePh': 'जैसे: मटर, हल्दी, धनिया',
    'crops.form.section.basic': 'फसल और ज़मीन',
    'crops.form.section.dates': 'तारीखें',
    'crops.form.section.field': 'खेत की जानकारी',
    'crops.form.variety': 'किस्म',
    'crops.form.varietyPh': 'जैसे: HD 2967',
    'crops.form.varietyHint': 'किस्म का नाम बीज के पैकेट या बिल पर लिखा होता है',
    'crops.form.varietyChips': 'जानी-मानी किस्में (केवल उदाहरण)',
    'crops.form.area': 'ज़मीन (रकबा)',
    'crops.form.unit': 'इकाई',
    'crops.form.bighaHint': 'आपकी सेटिंग में 1 बीघा ≈ {n} एकड़',
    'crops.form.farm': 'खेत',
    'crops.form.noFarm': 'कोई खेत नहीं',
    'crops.form.newFarm': 'नया खेत जोड़ें',
    'crops.form.farmHint': 'खेत चुनने पर मिट्टी, सिंचाई और स्थान अपने-आप भर जाएंगे',
    'crops.form.noFarmsYet': 'अभी कोई खेत नहीं जोड़ा। खेत जोड़ने से फसलें खेत के हिसाब से दिखेंगी।',
    'crops.form.sowingDate': 'बुवाई की तारीख',
    'crops.form.sowingHint': 'अभी बुवाई नहीं हुई? खाली छोड़ दें या आगे की तारीख चुनें',
    'crops.form.nurseryDate': 'नर्सरी बुवाई की तारीख',
    'crops.form.nurseryHint': 'जिस दिन नर्सरी में बीज डाला',
    'crops.form.transplantDate': 'रोपाई की तारीख',
    'crops.form.transplantHint': 'रोपाई अभी नहीं हुई तो खाली छोड़ें — नर्सरी की तारीख से अनुमान लगा लेंगे',
    'crops.form.season': 'सीजन',
    'crops.form.seasonAuto': 'तारीख के हिसाब से अपने-आप चुना गया। ज़रूरत हो तो बदलें।',
    'crops.form.seasonManual': 'आपका चुना सीजन',
    'crops.form.seasonNoDate': 'बुवाई की तारीख डालने पर सीजन अपने-आप चुना जाएगा। चाहें तो अभी चुन लें।',
    'crops.form.harvest': 'अनुमानित कटाई',
    'crops.form.harvestAuto': 'औसत अवधि के हिसाब से अनुमान। अपनी किस्म के अनुसार बदल सकते हैं।',
    'crops.form.harvestReset': 'अनुमान वापस लाएं ({date})',
    'crops.form.harvestNeedsDate': 'बुवाई की तारीख डालने पर कटाई का अनुमान अपने-आप दिखेगा',
    'crops.form.soil': 'मिट्टी',
    'crops.form.irrigation': 'सिंचाई का साधन',
    'crops.form.location': 'स्थान',
    'crops.form.locationHint': 'मौसम की चेतावनी और सलाह इसी जगह के हिसाब से मिलेगी',
    'crops.form.locationApp': 'ऐप में चुना स्थान',
    'crops.form.locationTitle': 'फसल का स्थान चुनें',
    'crops.form.changeLocation': 'स्थान बदलें',
    'crops.form.notes': 'नोट्स',
    'crops.form.notesPh': 'जैसे: बीज कहां से लिया, पिछली फसल कौन सी थी',
    'crops.form.save': 'फसल सेव करें',
    'crops.form.saveChanges': 'बदलाव सेव करें',
    'crops.form.saved': 'फसल सेव हो गई। काम का कैलेंडर तैयार है।',
    'crops.form.savedNoDate': 'फसल सेव हो गई',
    'crops.form.updated': 'बदलाव सेव हो गए',
    'crops.form.fixErrors': 'कुछ जानकारी ठीक करनी है',
    'crops.form.error.crop': 'पहले फसल चुनें',
    'crops.form.error.name': 'फसल का नाम लिखें',
    'crops.form.error.area': 'ज़मीन 0 से ज़्यादा लिखें',
    'crops.form.error.areaMax': 'ज़मीन बहुत ज़्यादा लिखी है, एक बार जांच लें',
    'crops.form.error.dateInvalid': 'सही तारीख चुनें',
    'crops.form.error.dateOld': 'तारीख 3 साल से ज़्यादा पुरानी नहीं हो सकती',
    'crops.form.error.dateFuture': 'तारीख 6 महीने से ज़्यादा आगे की नहीं हो सकती',
    'crops.form.error.transplantBefore': 'रोपाई की तारीख नर्सरी बुवाई के बाद की होनी चाहिए',
    'crops.form.error.transplantGap': 'नर्सरी और रोपाई में 5 महीने से ज़्यादा का अंतर है, जांच लें',
    'crops.form.error.harvestBefore': 'कटाई की तारीख बुवाई/रोपाई के बाद की होनी चाहिए',
    'crops.form.error.harvestFar': 'कटाई की तारीख बहुत दूर है, जांच लें',
    'crops.form.delete': 'यह फसल हटाएं',
    'crops.form.deleteTitle': 'क्या यह फसल हटानी है?',
    'crops.form.deleteBody': 'इसके कैलेंडर के सभी काम और रिमाइंडर भी हट जाएंगे। यह वापस नहीं होगा।',
    'crops.form.deleted': 'फसल हटा दी गई',
    'crops.form.discardTitle': 'बदलाव सेव नहीं हुए',
    'crops.form.discardBody': 'बिना सेव किए वापस जाना है?',
    'crops.form.discard': 'हां, वापस जाएं',
    'crops.form.keep': 'नहीं, यहीं रहें',

    'crops.notFound.title': 'यह फसल नहीं मिली',
    'crops.notFound.body': 'शायद इसे हटा दिया गया है। अपनी फसलों की सूची देखें।',
    'crops.notFound.action': 'मेरी फसलें देखें',

    // Soil and irrigation labels
    'crops.soil.alluvial': 'जलोढ़ (कछारी) मिट्टी',
    'crops.soil.black': 'काली मिट्टी',
    'crops.soil.red': 'लाल मिट्टी',
    'crops.soil.laterite': 'लैटेराइट (मुरम वाली) मिट्टी',
    'crops.soil.sandy': 'बलुई (रेतीली) मिट्टी',
    'crops.soil.clay': 'चिकनी मिट्टी',
    'crops.soil.loamy': 'दोमट मिट्टी',
    'crops.soil.unknown': 'पता नहीं',
    'crops.irrigation.canal': 'नहर',
    'crops.irrigation.tubewell': 'ट्यूबवेल / बोरवेल',
    'crops.irrigation.drip': 'ड्रिप',
    'crops.irrigation.sprinkler': 'स्प्रिंकलर (फव्वारा)',
    'crops.irrigation.rainfed': 'बारिश पर निर्भर',
    'crops.irrigation.pond': 'तालाब / कुआं',
    'crops.irrigation.other': 'अन्य',

    // ---- Crop details ----
    'crops.detail.edit': 'फसल की जानकारी बदलें',
    'crops.detail.actions': 'इस फसल के लिए',
    'crops.detail.stage.title': 'फसल की अवस्था',
    'crops.detail.dayFromSowing': 'बुवाई से दिन {n}',
    'crops.detail.dayFromTransplant': 'रोपाई से दिन {n}',
    'crops.detail.progress': '{pct}% पूरा',
    'crops.detail.nextStage': 'अगली अवस्था: {stage} — {n} दिन में',
    'crops.detail.fromDay': 'दिन {n} से',
    'crops.detail.inDays': '{n} दिन में',
    'crops.detail.now': 'अभी',
    'crops.detail.harvestStep': 'कटाई',
    'crops.detail.harvestStepDay': 'लगभग दिन {n}',
    'crops.detail.plannedNote': 'बुवाई की तारीख डालें — फिर हम अवस्था, काम और कटाई का समय बताएंगे।',
    'crops.detail.plannedNoteTransplant': 'रोपाई या नर्सरी की तारीख डालें — फिर हम अवस्था, काम और कटाई का समय बताएंगे।',
    'crops.detail.addDate': 'तारीख डालें',
    'crops.detail.beforeSowing': 'बुवाई में {n} दिन बाकी',
    'crops.detail.beforeTransplant': 'रोपाई में {n} दिन बाकी',
    'crops.detail.harvestedNote': 'इस फसल की कटाई का समय निकल चुका है। अगली फसल जोड़ना न भूलें।',
    'crops.detail.estimateNote': 'अवस्थाएं मध्यम अवधि की किस्म के औसत पर आधारित अनुमान हैं।',
    'crops.detail.farmLine': 'खेत: {farm}',

    // Health
    'crops.health.title': 'फसल की सेहत',
    'crops.health.healthy': 'पिछली जांच में फसल स्वस्थ दिखी',
    'crops.health.issue': 'संभावित समस्या: {issue}',
    'crops.health.checkedOn': '{date} की फोटो जांच • {pct}% अनुमान',
    'crops.health.old': 'जांच पुरानी है — नई फोटो से दोबारा जांचें',
    'crops.health.none': 'अभी कोई जांच नहीं हुई',
    'crops.health.noneBody': 'पत्ती या पौधे की फोटो लेकर रोग और कीट की जांच करें।',
    'crops.health.check': 'फसल डॉक्टर से जांचें',
    'crops.health.status.good': 'फसल ठीक दिख रही है',
    'crops.health.status.watch': 'नज़र रखें',
    'crops.health.status.risk': 'खतरा — जल्दी ध्यान दें',
    'crops.health.aiNote': 'AI का अनुमान, आज की सलाह से',

    // Weather risk
    'crops.risk.title': 'मौसम से खतरा',
    'crops.risk.none': 'अगले 3 दिन मौसम से कोई बड़ा खतरा नहीं दिखता',
    'crops.risk.noneAdvisory': 'अभी कोई बड़ा खतरा नहीं दिखता',
    'crops.risk.noForecast': 'मौसम की ताज़ा जानकारी नहीं है — इंटरनेट से जोड़कर दोबारा देखें',
    'crops.risk.seeWeather': 'मौसम',
    'crops.risk.level.high': 'ज़्यादा खतरा',
    'crops.risk.level.medium': 'ध्यान दें',
    'crops.risk.level.low': 'हल्का खतरा',
    'crops.risk.germRain.title': 'अंकुरण के समय तेज़ बारिश',
    'crops.risk.germRain.text': '{day} बारिश के आसार हैं। खेत में पानी न रुकने दें, नहीं तो बीज सड़ सकता है।',
    'crops.risk.flowerRain.title': 'फूल आने के समय बारिश',
    'crops.risk.flowerRain.text': '{day} बारिश के आसार हैं। फूल झड़ सकते हैं और फफूंद रोग बढ़ सकते हैं। इस दौरान छिड़काव टालें और खेत से पानी निकालें।',
    'crops.risk.heat.title': 'दाना/फल बनते समय तेज़ गर्मी',
    'crops.risk.heat.text': '{day} तापमान {temp}°C तक जा सकता है। नमी बनाए रखने के लिए शाम को हल्की सिंचाई करें।',
    'crops.risk.frost.title': 'फूल और दाने पर पाले का खतरा',
    'crops.risk.frost.text': '{day} न्यूनतम तापमान {temp}°C तक गिर सकता है। शाम को हल्की सिंचाई करें और रात में मेड़ों पर धुआं करें।',
    'crops.risk.matureRain.title': 'पकी फसल पर बारिश या आंधी',
    'crops.risk.matureRain.text': '{day} बारिश या तेज़ हवा के आसार हैं। कटाई मौसम देखकर करें और कटी फसल को ढककर रखें।',
    'crops.risk.wind.title': 'तेज़ हवा से फसल गिरने का खतरा',
    'crops.risk.wind.text': '{day} हवा {kmh} km/h तक तेज़ हो सकती है। इस दौरान सिंचाई न करें, ताकि फसल न गिरे।',
    'crops.risk.humid.title': 'लगातार नमी से रोग का खतरा',
    'crops.risk.humid.text': 'अगले कुछ दिन बादल और बारिश के आसार हैं। पत्तियों पर धब्बे या फफूंद दिखे तो फसल डॉक्टर से जांचें।',

    // Next task
    'crops.task.title': 'अगला काम',
    'crops.task.markDone': 'काम पूरा हुआ',
    'crops.task.doneToast': 'बढ़िया! काम पूरा हो गया',
    'crops.task.undo': 'वापस करें',
    'crops.task.due.today': 'आज करना है',
    'crops.task.due.tomorrow': 'कल करना है',
    'crops.task.due.inDays': '{n} दिन बाद',
    'crops.task.due.overdue': '{n} दिन से बाकी',
    'crops.task.none': 'अभी कोई काम बाकी नहीं है',
    'crops.task.noDate': 'बुवाई की तारीख डालने पर काम का पूरा कैलेंडर बन जाएगा',
    'crops.task.calendar': 'कैलेंडर',

    // Harvest
    'crops.harvest.title': 'अनुमानित कटाई',
    'crops.harvest.daysLeft': '{n} दिन बाकी',
    'crops.harvest.due': 'कटाई का समय आ गया है',
    'crops.harvest.past': 'कटाई का अनुमानित समय निकल चुका है',
    'crops.harvest.picking': 'तुड़ाई लगभग {n} दिन तक चलती है',
    'crops.harvest.note': 'औसत अवधि पर आधारित अनुमान। किस्म और मौसम के हिसाब से 1–2 हफ्ते आगे-पीछे हो सकता है।',
    'crops.harvest.custom': 'आपकी डाली हुई तारीख',
    'crops.harvest.noDate': 'तारीख डालने पर अनुमान दिखेगा',
    'crops.harvest.noDateShort': 'तारीख नहीं',
    'crops.harvest.calendarNote': 'कैलेंडर में कटाई का काम औसत अवधि के हिसाब से {date} को है।',

    // Advice (preview + advisory screen)
    'crops.advice.screenTitle': 'फसल सलाह',
    'crops.advice.title': 'आज की सलाह',
    'crops.advice.seeAll': 'पूरी सलाह देखें',
    'crops.advice.source.ai': 'AI सलाह',
    'crops.advice.source.rules': 'कैलेंडर के अनुसार',
    'crops.advice.preparing': 'AI सलाह तैयार हो रही है…',
    'crops.advice.rulesBasis': 'आपकी फसल के कैलेंडर और मौसम के आधार पर',
    'crops.advice.offlineNote': 'इंटरनेट नहीं है, इसलिए कैलेंडर और मौसम के आधार पर सलाह दिखाई जा रही है।',
    'crops.advice.unavailableNote': 'AI सलाह अभी चालू नहीं है, इसलिए कैलेंडर और मौसम के आधार पर सलाह दिखाई जा रही है।',
    'crops.advice.errorNote': '{error} तब तक कैलेंडर और मौसम के आधार पर सलाह दिखाई जा रही है।',
    'crops.advice.tabs': 'समय चुनें',
    'crops.advice.tab.today': 'आज',
    'crops.advice.tab.week': 'इस सप्ताह',
    'crops.advice.tab.month': 'इस महीने',
    'crops.advice.heading.today': 'आज क्या करें',
    'crops.advice.heading.week': 'इस सप्ताह क्या करें',
    'crops.advice.heading.month': 'इस महीने क्या करें',
    'crops.advice.empty.today': 'आज के लिए कोई खास काम नहीं है',
    'crops.advice.empty.week': 'इस सप्ताह के लिए कोई खास काम नहीं है',
    'crops.advice.empty.month': 'इस महीने के लिए अलग से कोई सलाह नहीं है',
    'crops.advice.emptyNoDate': 'बुवाई की तारीख डालें, तो हम हर दिन और हर हफ्ते की सलाह बना देंगे।',
    'crops.advice.nextTask': 'अगला महत्वपूर्ण काम',
    'crops.advice.noNextTask': 'अभी कोई ज़रूरी काम बाकी नहीं है',
    'crops.advice.openCalendar': 'कैलेंडर देखें',
    'crops.advice.risks': 'किन बातों का ध्यान रखें',
    'crops.advice.save': 'सलाह सेव करें',
    'crops.advice.unsaved': 'सेव से हटा दिया',
    'crops.advice.saveTitle': '{crop} — {period} की सलाह ({date})',
    'crops.advice.shareTitle': '{crop} — {period} की सलाह',
    'crops.advice.shareFooter': '— किसान मित्र ऐप से',
    'crops.advice.askAi': 'AI से विस्तार से पूछें',
    'crops.advice.askMore': 'अपनी फसल के बारे में AI से पूछें',
    'crops.advice.askPrompt': 'मेरी {crop} की फसल ({stage}) के लिए यह सलाह मिली है: "{line}"। इसे आसान भाषा में विस्तार से समझाइए — क्या, कब और कैसे करना है?',
    'crops.advice.askCrop': 'मेरी {crop} की फसल ({stage}) के बारे में सलाह चाहिए।',
    'crops.advice.openLine': '{title}: पूरी जानकारी खोलें',
    'crops.advice.savedTitle': 'सेव की गई सलाह',
    'crops.advice.savedNote': 'यह {date} की सलाह है। आज की सलाह नीचे है।',
    'crops.advice.savedRemove': 'सेव से हटाएं',
    'crops.advice.nextTaskAi': 'कैलेंडर में अभी कोई काम नहीं है। AI का सुझाव:',

    // Topics (coloured round icons in advice rows)
    'crops.topic.irrigation': 'सिंचाई',
    'crops.topic.pest': 'कीट निगरानी',
    'crops.topic.protection': 'फसल सुरक्षा',
    'crops.topic.fertilizer': 'खाद',
    'crops.topic.weather': 'मौसम चेतावनी',
    'crops.topic.weatherInfo': 'मौसम',
    'crops.topic.weeding': 'निराई',
    'crops.topic.spray': 'छिड़काव',
    'crops.topic.sowing': 'बुवाई / रोपाई',
    'crops.topic.seed': 'बीज उपचार',
    'crops.topic.harvest': 'कटाई',
    'crops.topic.general': 'सलाह',

    // Quick actions on crop details
    'crops.action.doctor': 'फसल डॉक्टर',
    'crops.action.expense': 'खर्च जोड़ें',
    'crops.action.ai': 'AI से पूछें',
    'crops.action.calendar': 'कैलेंडर',
    'crops.action.edit': 'बदलें',

    // Catalog information
    'crops.info.title': 'फसल की जानकारी',
    'crops.info.subtitle': 'सामान्य मार्गदर्शन — स्थानीय KVK की सलाह और मिट्टी जांच को प्राथमिकता दें',
    'crops.info.mine': 'आपकी दर्ज जानकारी',
    'crops.info.sowing': 'बुवाई का समय',
    'crops.info.seasons': 'सीजन: {list}',
    'crops.info.duration': 'अवधि: लगभग {min}–{max} दिन',
    'crops.info.seed': 'बीज की मात्रा',
    'crops.info.seedRate': '{min}–{max} किलो प्रति एकड़',
    'crops.info.seedRateOne': '{min} किलो प्रति एकड़',
    'crops.info.spacing': 'दूरी और गहराई',
    'crops.info.irrigation': 'सिंचाई के ज़रूरी समय',
    'crops.info.npk': 'खाद (NPK)',
    'crops.info.npkLine': 'नाइट्रोजन {n} • फॉस्फोरस {p} • पोटाश {k} किलो प्रति एकड़',
    'crops.info.npkHint': 'मध्यम उपजाऊ मिट्टी के लिए सामान्य सिफ़ारिश। ये शुद्ध पोषक तत्व हैं, खाद की बोरियां नहीं।',
    'crops.info.soil': 'उपयुक्त मिट्टी',
    'crops.info.varieties': 'प्रमुख किस्में',
    'crops.info.varietiesNote': 'केवल उदाहरण। अपने इलाके के लिए सिफ़ारिश की गई किस्म KVK से पूछें।',
    'crops.info.diseases': 'प्रमुख रोग और कीट',
    'crops.info.diseasesNote': 'लक्षण दिखें तो फसल डॉक्टर से फोटो जांच करें।',
    'crops.info.notAvailable': 'इस फसल की विस्तृत जानकारी अभी ऐप में नहीं है। आप AI से पूछ सकते हैं।',
    'crops.info.variety': 'किस्म',
    'crops.info.season': 'सीजन',
    'crops.info.farm': 'खेत',
    'crops.info.place': 'स्थान',
    'crops.info.soilMine': 'मिट्टी',
    'crops.info.irrigationMine': 'सिंचाई',
    'crops.info.notes': 'नोट्स',
    'crops.info.notSet': 'नहीं डाला',
  },
  en: {
    'crops.title': 'My crops',
    'crops.count.one': '1 crop',
    'crops.count': '{n} crops',
    'crops.add': 'Add new crop',
    'crops.totalArea': 'Total land: {area}',
    'crops.totalAreaApprox': 'Total land: about {area}',
    'crops.listLabel': 'Crop list',
    'crops.noFarm': 'Crops without a farm',
    'crops.sown': 'Sown: {date}',
    'crops.transplanted': 'Transplanted: {date}',
    'crops.nurserySown': 'Nursery sown: {date}',
    'crops.noSowingDate': 'Sowing date not added',
    'crops.noTransplantDate': 'Transplanting date not added',
    'crops.currentStage': 'Current stage: {stage}',
    'crops.stageWithSuffix': '{stage} stage',
    'crops.empty.title': 'No crops added yet',
    'crops.empty.body': 'Add your crop. From the sowing date we give daily advice, a task calendar and weather alerts.',

    'crops.area.acre': '{n} acres',
    'crops.area.one.acre': '{n} acre',
    'crops.area.bigha': '{n} bigha',
    'crops.area.one.bigha': '{n} bigha',
    'crops.area.hectare': '{n} hectares',
    'crops.area.one.hectare': '{n} hectare',
    'crops.area.notSet': 'Area not added',
    'crops.sep': '. ',

    'crops.when.today': 'today',
    'crops.when.tomorrow': 'tomorrow',
    'crops.when.on': 'on {date}',

    'crops.add.title': 'Add new crop',
    'crops.add.subtitle': 'Crop, land and sowing date',
    'crops.edit.title': 'Edit crop',
    'crops.form.whichCrop': 'Which crop are you growing?',
    'crops.form.whichCropHint': 'Tap a crop picture',
    'crops.form.other': 'Other crop',
    'crops.form.otherHint': 'Not in the list? Add it by name',
    'crops.form.change': 'Change',
    'crops.form.changeCrop': 'Change crop',
    'crops.form.keepCrop': 'Keep this crop',
    'crops.form.otherName': 'Crop name',
    'crops.form.otherNamePh': 'e.g. Pea, Turmeric, Coriander',
    'crops.form.section.basic': 'Crop and land',
    'crops.form.section.dates': 'Dates',
    'crops.form.section.field': 'Field details',
    'crops.form.variety': 'Variety',
    'crops.form.varietyPh': 'e.g. HD 2967',
    'crops.form.varietyHint': 'The variety name is printed on the seed packet or bill',
    'crops.form.varietyChips': 'Well-known varieties (examples only)',
    'crops.form.area': 'Land area',
    'crops.form.unit': 'Unit',
    'crops.form.bighaHint': 'In your settings 1 bigha ≈ {n} acre',
    'crops.form.farm': 'Farm',
    'crops.form.noFarm': 'No farm',
    'crops.form.newFarm': 'Add new farm',
    'crops.form.farmHint': 'Choosing a farm fills soil, irrigation and location for you',
    'crops.form.noFarmsYet': 'No farms added yet. Adding farms groups your crops by farm.',
    'crops.form.sowingDate': 'Sowing date',
    'crops.form.sowingHint': 'Not sown yet? Leave it empty or pick a future date',
    'crops.form.nurseryDate': 'Nursery sowing date',
    'crops.form.nurseryHint': 'The day seed was sown in the nursery',
    'crops.form.transplantDate': 'Transplanting date',
    'crops.form.transplantHint': 'Leave empty if not transplanted yet — we will estimate from the nursery date',
    'crops.form.season': 'Season',
    'crops.form.seasonAuto': 'Picked automatically from the date. Change it if needed.',
    'crops.form.seasonManual': 'Season chosen by you',
    'crops.form.seasonNoDate': 'The season is picked from the sowing date. You can also choose it now.',
    'crops.form.harvest': 'Expected harvest',
    'crops.form.harvestAuto': 'Estimate from the average duration. Change it for your variety.',
    'crops.form.harvestReset': 'Use the estimate ({date})',
    'crops.form.harvestNeedsDate': 'Add the sowing date to see the harvest estimate',
    'crops.form.soil': 'Soil',
    'crops.form.irrigation': 'Irrigation source',
    'crops.form.location': 'Location',
    'crops.form.locationHint': 'Weather alerts and advice are for this place',
    'crops.form.locationApp': 'Place selected in the app',
    'crops.form.locationTitle': 'Choose crop location',
    'crops.form.changeLocation': 'Change location',
    'crops.form.notes': 'Notes',
    'crops.form.notesPh': 'e.g. where the seed came from, previous crop',
    'crops.form.save': 'Save crop',
    'crops.form.saveChanges': 'Save changes',
    'crops.form.saved': 'Crop saved. Your task calendar is ready.',
    'crops.form.savedNoDate': 'Crop saved',
    'crops.form.updated': 'Changes saved',
    'crops.form.fixErrors': 'Please fix the highlighted details',
    'crops.form.error.crop': 'Choose a crop first',
    'crops.form.error.name': 'Write the crop name',
    'crops.form.error.area': 'Enter an area above 0',
    'crops.form.error.areaMax': 'This area looks too large, please check',
    'crops.form.error.dateInvalid': 'Choose a valid date',
    'crops.form.error.dateOld': 'The date cannot be more than 3 years old',
    'crops.form.error.dateFuture': 'The date cannot be more than 6 months ahead',
    'crops.form.error.transplantBefore': 'Transplanting must be after nursery sowing',
    'crops.form.error.transplantGap': 'More than 5 months between nursery and transplanting, please check',
    'crops.form.error.harvestBefore': 'Harvest must be after sowing/transplanting',
    'crops.form.error.harvestFar': 'The harvest date is too far away, please check',
    'crops.form.delete': 'Delete this crop',
    'crops.form.deleteTitle': 'Delete this crop?',
    'crops.form.deleteBody': 'All its calendar tasks and reminders will be removed too. This cannot be undone.',
    'crops.form.deleted': 'Crop deleted',
    'crops.form.discardTitle': 'Changes not saved',
    'crops.form.discardBody': 'Go back without saving?',
    'crops.form.discard': 'Yes, go back',
    'crops.form.keep': 'No, stay',

    'crops.notFound.title': 'Crop not found',
    'crops.notFound.body': 'It may have been deleted. See your crop list.',
    'crops.notFound.action': 'See my crops',

    'crops.soil.alluvial': 'Alluvial soil',
    'crops.soil.black': 'Black soil',
    'crops.soil.red': 'Red soil',
    'crops.soil.laterite': 'Laterite soil',
    'crops.soil.sandy': 'Sandy soil',
    'crops.soil.clay': 'Clay soil',
    'crops.soil.loamy': 'Loamy soil',
    'crops.soil.unknown': 'Not sure',
    'crops.irrigation.canal': 'Canal',
    'crops.irrigation.tubewell': 'Tubewell / borewell',
    'crops.irrigation.drip': 'Drip',
    'crops.irrigation.sprinkler': 'Sprinkler',
    'crops.irrigation.rainfed': 'Rainfed',
    'crops.irrigation.pond': 'Pond / well',
    'crops.irrigation.other': 'Other',

    'crops.detail.edit': 'Edit crop',
    'crops.detail.actions': 'For this crop',
    'crops.detail.stage.title': 'Crop stage',
    'crops.detail.dayFromSowing': 'Day {n} since sowing',
    'crops.detail.dayFromTransplant': 'Day {n} since transplanting',
    'crops.detail.progress': '{pct}% done',
    'crops.detail.nextStage': 'Next: {stage} in {n} days',
    'crops.detail.fromDay': 'From day {n}',
    'crops.detail.inDays': 'In {n} days',
    'crops.detail.now': 'Now',
    'crops.detail.harvestStep': 'Harvest',
    'crops.detail.harvestStepDay': 'Around day {n}',
    'crops.detail.plannedNote': 'Add the sowing date — then we can show the stage, tasks and harvest time.',
    'crops.detail.plannedNoteTransplant': 'Add the transplanting or nursery date — then we can show the stage, tasks and harvest time.',
    'crops.detail.addDate': 'Add date',
    'crops.detail.beforeSowing': '{n} days to sowing',
    'crops.detail.beforeTransplant': '{n} days to transplanting',
    'crops.detail.harvestedNote': 'This crop is past its harvest time. Remember to add your next crop.',
    'crops.detail.estimateNote': 'Stages are estimates for an average mid-duration variety.',
    'crops.detail.farmLine': 'Farm: {farm}',

    'crops.health.title': 'Crop health',
    'crops.health.healthy': 'Looked healthy in the last check',
    'crops.health.issue': 'Possible problem: {issue}',
    'crops.health.checkedOn': 'Photo check on {date} • {pct}% estimate',
    'crops.health.old': 'This check is old — check again with a new photo',
    'crops.health.none': 'No check yet',
    'crops.health.noneBody': 'Take a photo of a leaf or plant to check for disease and pests.',
    'crops.health.check': 'Check with Crop Doctor',
    'crops.health.status.good': 'Crop looks fine',
    'crops.health.status.watch': 'Keep watch',
    'crops.health.status.risk': 'At risk — act soon',
    'crops.health.aiNote': "AI estimate from today's advice",

    'crops.risk.title': 'Weather risk',
    'crops.risk.none': 'No major weather risk in the next 3 days',
    'crops.risk.noneAdvisory': 'No major risk right now',
    'crops.risk.noForecast': 'No fresh weather forecast — connect to the internet and check again',
    'crops.risk.seeWeather': 'Weather',
    'crops.risk.level.high': 'High risk',
    'crops.risk.level.medium': 'Take care',
    'crops.risk.level.low': 'Low risk',
    'crops.risk.germRain.title': 'Heavy rain at germination',
    'crops.risk.germRain.text': 'Rain is likely {day}. Do not let water stand in the field or the seed may rot.',
    'crops.risk.flowerRain.title': 'Rain at flowering',
    'crops.risk.flowerRain.text': 'Rain is likely {day}. Flowers may drop and fungal disease may rise. Avoid spraying then and drain the field.',
    'crops.risk.heat.title': 'Heat during flowering or grain filling',
    'crops.risk.heat.text': 'Temperature may reach {temp}°C {day}. Give a light evening irrigation to keep the soil moist.',
    'crops.risk.frost.title': 'Frost risk to flowers and grain',
    'crops.risk.frost.text': 'Night temperature may fall to {temp}°C {day}. Give a light evening irrigation and make smoke on the field bunds at night.',
    'crops.risk.matureRain.title': 'Rain or storm on a ripe crop',
    'crops.risk.matureRain.text': 'Rain or strong wind is likely {day}. Plan the harvest around the weather and keep the cut crop covered.',
    'crops.risk.wind.title': 'Strong wind may flatten the crop',
    'crops.risk.wind.text': 'Wind may reach {kmh} km/h {day}. Do not irrigate then, so the crop does not fall over.',
    'crops.risk.humid.title': 'Disease risk from wet weather',
    'crops.risk.humid.text': 'Clouds and rain are likely for the next few days. If you see spots or mould on leaves, check with Crop Doctor.',

    'crops.task.title': 'Next task',
    'crops.task.markDone': 'Mark task done',
    'crops.task.doneToast': 'Well done! Task completed',
    'crops.task.undo': 'Undo',
    'crops.task.due.today': 'Due today',
    'crops.task.due.tomorrow': 'Due tomorrow',
    'crops.task.due.inDays': 'In {n} days',
    'crops.task.due.overdue': '{n} days overdue',
    'crops.task.none': 'No pending task right now',
    'crops.task.noDate': 'Add the sowing date to get the full task calendar',
    'crops.task.calendar': 'Calendar',

    'crops.harvest.title': 'Expected harvest',
    'crops.harvest.daysLeft': '{n} days left',
    'crops.harvest.due': 'Harvest time has come',
    'crops.harvest.past': 'The expected harvest date has passed',
    'crops.harvest.picking': 'Picking continues for about {n} days',
    'crops.harvest.note': 'Estimate from the average duration. It can vary by 1–2 weeks with variety and weather.',
    'crops.harvest.custom': 'Date entered by you',
    'crops.harvest.noDate': 'Add a date to see the estimate',
    'crops.harvest.noDateShort': 'No date',
    'crops.harvest.calendarNote': 'The harvest task in your calendar is on {date}, from the average duration.',

    'crops.advice.screenTitle': 'Crop advice',
    'crops.advice.title': "Today's advice",
    'crops.advice.seeAll': 'See full advice',
    'crops.advice.source.ai': 'AI advice',
    'crops.advice.source.rules': 'As per calendar',
    'crops.advice.preparing': 'Preparing AI advice…',
    'crops.advice.rulesBasis': 'Based on your crop calendar and weather',
    'crops.advice.offlineNote': 'No internet, so advice is based on your calendar and weather.',
    'crops.advice.unavailableNote': 'AI advice is not switched on yet, so advice is based on your calendar and weather.',
    'crops.advice.errorNote': '{error} Meanwhile, advice is based on your calendar and weather.',
    'crops.advice.tabs': 'Choose period',
    'crops.advice.tab.today': 'Today',
    'crops.advice.tab.week': 'This week',
    'crops.advice.tab.month': 'This month',
    'crops.advice.heading.today': 'What to do today',
    'crops.advice.heading.week': 'What to do this week',
    'crops.advice.heading.month': 'What to do this month',
    'crops.advice.empty.today': 'Nothing special to do today',
    'crops.advice.empty.week': 'Nothing special this week',
    'crops.advice.empty.month': 'No separate advice for this month',
    'crops.advice.emptyNoDate': 'Add the sowing date and we will prepare daily and weekly advice.',
    'crops.advice.nextTask': 'Next important task',
    'crops.advice.noNextTask': 'No urgent task pending right now',
    'crops.advice.openCalendar': 'Open calendar',
    'crops.advice.risks': 'Things to watch',
    'crops.advice.save': 'Save advice',
    'crops.advice.unsaved': 'Removed from saved',
    'crops.advice.saveTitle': '{crop} — advice for {period} ({date})',
    'crops.advice.shareTitle': '{crop} — advice for {period}',
    'crops.advice.shareFooter': '— from the Kisan Mitra app',
    'crops.advice.askAi': 'Ask AI for details',
    'crops.advice.askMore': 'Ask AI about your crop',
    'crops.advice.askPrompt': 'I got this advice for my {crop} crop ({stage}): "{line}". Please explain it simply — what to do, when and how?',
    'crops.advice.askCrop': 'I need advice for my {crop} crop ({stage}).',
    'crops.advice.openLine': '{title}: open full details',
    'crops.advice.savedTitle': 'Saved advice',
    'crops.advice.savedNote': 'This advice is from {date}. Today\'s advice is below.',
    'crops.advice.savedRemove': 'Remove from saved',
    'crops.advice.nextTaskAi': 'Nothing in your calendar right now. AI suggests:',

    'crops.topic.irrigation': 'Irrigation',
    'crops.topic.pest': 'Pest watch',
    'crops.topic.protection': 'Crop protection',
    'crops.topic.fertilizer': 'Fertilizer',
    'crops.topic.weather': 'Weather alert',
    'crops.topic.weatherInfo': 'Weather',
    'crops.topic.weeding': 'Weeding',
    'crops.topic.spray': 'Spraying',
    'crops.topic.sowing': 'Sowing / transplanting',
    'crops.topic.seed': 'Seed treatment',
    'crops.topic.harvest': 'Harvest',
    'crops.topic.general': 'Advice',

    'crops.action.doctor': 'Crop doctor',
    'crops.action.expense': 'Add expense',
    'crops.action.ai': 'Ask AI',
    'crops.action.calendar': 'Calendar',
    'crops.action.edit': 'Edit',

    'crops.info.title': 'About this crop',
    'crops.info.subtitle': 'General guidance — local KVK advice and your soil test come first',
    'crops.info.mine': 'Your details',
    'crops.info.sowing': 'Sowing time',
    'crops.info.seasons': 'Seasons: {list}',
    'crops.info.duration': 'Duration: about {min}–{max} days',
    'crops.info.seed': 'Seed rate',
    'crops.info.seedRate': '{min}–{max} kg per acre',
    'crops.info.seedRateOne': '{min} kg per acre',
    'crops.info.spacing': 'Spacing and depth',
    'crops.info.irrigation': 'Critical irrigation stages',
    'crops.info.npk': 'Fertilizer (NPK)',
    'crops.info.npkLine': 'Nitrogen {n} • Phosphorus {p} • Potash {k} kg per acre',
    'crops.info.npkHint': 'General recommendation for medium-fertility soil. These are pure nutrients, not fertilizer bags.',
    'crops.info.soil': 'Suitable soil',
    'crops.info.varieties': 'Common varieties',
    'crops.info.varietiesNote': 'Examples only. Ask your KVK which variety is recommended for your area.',
    'crops.info.diseases': 'Major diseases and pests',
    'crops.info.diseasesNote': 'If you see symptoms, check a photo with Crop Doctor.',
    'crops.info.notAvailable': 'Detailed information for this crop is not in the app yet. You can ask the AI.',
    'crops.info.variety': 'Variety',
    'crops.info.season': 'Season',
    'crops.info.farm': 'Farm',
    'crops.info.place': 'Location',
    'crops.info.soilMine': 'Soil',
    'crops.info.irrigationMine': 'Irrigation',
    'crops.info.notes': 'Notes',
    'crops.info.notSet': 'Not added',
  },
});
