// Strings for the search screen and the disease detail sheet. Result subtitles
// ("अपनी फसल में जोड़ें", app features) are registered by services/search.ts, and disease
// type labels by ./disease-utils.ts.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    'search.title': 'खोजें',
    'search.placeholder': 'फसल, रोग, योजना या मंडी भाव',
    'search.inputLabel': 'फसल, रोग, योजना या मंडी भाव खोजें',
    'search.recent': 'हाल की खोजें',
    'search.clearRecent': 'सब मिटाएं',
    'search.recentCleared': 'हाल की खोजें मिटा दी गईं',
    'search.removeRecent': '“{q}” को हाल की खोजों से हटाएं',
    'search.undo': 'वापस लाएं',
    'search.popular': 'लोकप्रिय खोजें',
    'search.hint.title': 'लिखकर या बोलकर खोजें',
    'search.hint.body': 'फसल का नाम, रोग, सरकारी योजना या मंडी भाव लिखें। माइक दबाकर बोल भी सकते हैं। खोज बिना इंटरनेट के भी चलती है।',
    'search.typeMore': 'खोजने के लिए कम से कम 2 अक्षर लिखें',
    'search.resultsOne': '“{q}” के लिए 1 नतीजा',
    'search.resultsMany': '“{q}” के लिए {n} नतीजे',
    'search.group.feature': 'ऐप की सुविधाएं',
    'search.group.my-crop': 'मेरी फसलें',
    'search.group.crop': 'फसलें',
    'search.group.mandi': 'मंडी भाव',
    'search.group.disease': 'रोग और कीट',
    'search.group.technique': 'खेती तकनीक',
    'search.group.scheme': 'सरकारी योजनाएं',
    'search.group.conversation': 'AI से पिछली बातचीत',
    'search.group.saved': 'सेव की गई जानकारी',
    'search.showMore': '{n} और देखें',
    'search.showLess': 'कम दिखाएं',
    'search.capped': 'सबसे मिलते-जुलते {shown} नतीजे दिखाए गए हैं। बाकी के लिए खोज में एक और शब्द जोड़ें, जैसे फसल का नाम।',
    'search.noResults.title': '“{q}” के लिए कुछ नहीं मिला',
    'search.noResults.body': 'दूसरे या छोटे शब्द से खोजें, या यही सवाल AI से पूछें।',
    'search.askAI': 'AI से पूछें',
    'search.askAI.title': 'जो चाहिए वह नहीं मिला?',
    'search.askAI.body': 'अपना सवाल सीधे AI सहायक से पूछें।',
    'search.clearQuery': 'खोज साफ़ करें',
    'search.disease.crops': 'किन फसलों में',
    'search.disease.symptoms': 'लक्षण',
    'search.disease.conditions': 'कब ज़्यादा फैलता है',
    'search.disease.organic': 'जैविक उपाय',
    'search.disease.chemical': 'रासायनिक उपाय',
    'search.disease.prevention': 'बचाव',
    'search.disease.sources': 'जानकारी के स्रोत',
    'search.disease.checkDoctor': 'फसल डॉक्टर से जांचें',
    'search.disease.general': 'यह सामान्य जानकारी है, पक्की पहचान नहीं। दवा डालने से पहले नज़दीकी कृषि विज्ञान केंद्र (KVK) या कृषि विशेषज्ञ से पुष्टि करें।',
    'search.disease.reviewed': 'जानकारी जांची गई: {date}',
    'search.disease.severity.high': 'ज़्यादा नुकसान का ख़तरा',
    'search.disease.severity.medium': 'मध्यम नुकसान का ख़तरा',
    'search.disease.severity.low': 'कम नुकसान का ख़तरा',
    'search.disease.notFound': 'इस रोग की जानकारी नहीं मिली',
    'search.disease.save': 'सेव करें',
    'search.disease.savedLabel': 'सेव है',
    'search.disease.removed': 'सेव से हटा दिया गया',
    'search.disease.hindiOnly': '',
    'search.disease.sourceLink': '{title} (वेबसाइट खुलेगी)',
  },
  en: {
    'search.title': 'Search',
    'search.placeholder': 'Crops, diseases, schemes, prices',
    'search.inputLabel': 'Search crops, diseases, schemes or mandi prices',
    'search.recent': 'Recent searches',
    'search.clearRecent': 'Clear all',
    'search.recentCleared': 'Recent searches cleared',
    'search.removeRecent': 'Remove “{q}” from recent searches',
    'search.undo': 'Undo',
    'search.popular': 'Popular searches',
    'search.hint.title': 'Type or speak to search',
    'search.hint.body': 'Type a crop, disease, government scheme or mandi price. You can also tap the mic and speak. Search works without internet.',
    'search.typeMore': 'Type at least 2 letters to search',
    'search.resultsOne': '1 result for “{q}”',
    'search.resultsMany': '{n} results for “{q}”',
    'search.group.feature': 'App features',
    'search.group.my-crop': 'My crops',
    'search.group.crop': 'Crops',
    'search.group.mandi': 'Mandi prices',
    'search.group.disease': 'Diseases & pests',
    'search.group.technique': 'Farming techniques',
    'search.group.scheme': 'Government schemes',
    'search.group.conversation': 'Past AI chats',
    'search.group.saved': 'Saved items',
    'search.showMore': 'Show {n} more',
    'search.showLess': 'Show less',
    'search.capped': 'Showing the {shown} closest matches. Add another word, like a crop name, to see the rest.',
    'search.noResults.title': 'Nothing found for “{q}”',
    'search.noResults.body': 'Try a different or shorter word, or ask the AI.',
    'search.askAI': 'Ask AI',
    'search.askAI.title': "Didn't find what you need?",
    'search.askAI.body': 'Ask your question directly to the AI assistant.',
    'search.clearQuery': 'Clear search',
    'search.disease.crops': 'Crops affected',
    'search.disease.symptoms': 'Symptoms',
    'search.disease.conditions': 'When it spreads',
    'search.disease.organic': 'Organic control',
    'search.disease.chemical': 'Chemical control',
    'search.disease.prevention': 'Prevention',
    'search.disease.sources': 'Sources',
    'search.disease.checkDoctor': 'Check with Crop Doctor',
    'search.disease.general': 'This is general information, not a confirmed diagnosis. Confirm with your nearest Krishi Vigyan Kendra (KVK) or an agriculture expert before spraying.',
    'search.disease.reviewed': 'Information checked: {date}',
    'search.disease.severity.high': 'High loss risk',
    'search.disease.severity.medium': 'Medium loss risk',
    'search.disease.severity.low': 'Low loss risk',
    'search.disease.notFound': 'No information found for this disease',
    'search.disease.save': 'Save',
    'search.disease.savedLabel': 'Saved',
    'search.disease.removed': 'Removed from saved',
    'search.disease.hindiOnly': 'Detailed advice is available in Hindi only.',
    'search.disease.sourceLink': '{title} (opens website)',
  },
});
