// फसल डॉक्टर strings (doctor.*). Service-level strings (errors, recheck task text) are
// registered by services/diagnosis.ts.
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    // ---- Crop Doctor ----
    'doctor.title': 'फसल डॉक्टर',
    'doctor.subtitle': 'फोटो से पहचानें फसल की समस्या',
    'doctor.historyAction': 'पिछली जांच देखें',
    'doctor.steps': 'जांच के चरण',
    'doctor.step.crop': 'फसल',
    'doctor.step.photo': 'फोटो',
    'doctor.step.note': 'विवरण',
    'doctor.step.n': 'चरण {n}',
    'doctor.step.done': 'पूरा हुआ',

    'doctor.crop.title': 'फसल चुनें',
    'doctor.crop.choose': 'फसल चुनें',
    'doctor.crop.change': 'बदलें',
    'doctor.crop.changeAria': 'फसल बदलें, अभी चुनी है: {crop}',
    'doctor.crop.mine': 'मेरी फसलें',
    'doctor.crop.all': 'सभी फसलें',
    'doctor.crop.yours': 'आपकी फसल • {stage}',
    'doctor.crop.picked': 'इसी फसल की जांच होगी',
    'doctor.crop.sheetDesc': 'जिस फसल की फोटो लेनी है, उसे चुनें',

    'doctor.photo.title': 'फोटो लें',
    'doctor.photo.hint': 'बीमार पत्ती या हिस्से की पास से साफ़ फोटो लें',
    'doctor.photo.placeholder': 'पत्ती को फ्रेम के बीच में रखें',
    'doctor.photo.take': 'फोटो लें',
    'doctor.photo.gallery': 'गैलरी से चुनें',
    'doctor.photo.retake': 'दोबारा फोटो लें',
    'doctor.photo.another': 'दूसरी फोटो चुनें',
    'doctor.photo.remove': 'फोटो हटाएं',
    'doctor.photo.alt': '{crop} की चुनी गई फोटो',
    'doctor.photo.preparing': 'फोटो तैयार हो रही है…',

    'doctor.note.title': 'समस्या बताएं',
    'doctor.note.label': 'क्या दिख रहा है?',
    'doctor.note.placeholder': 'जैसे: पत्तियों पर पीले धब्बे हैं, 4–5 दिन से बढ़ रहे हैं',
    'doctor.note.hint': 'माइक दबाकर बोलकर भी बता सकते हैं। इससे जांच बेहतर होगी।',
    'doctor.note.mic': 'बोलकर बताएं कि क्या दिख रहा है',

    'doctor.analyse': 'विश्लेषण करें',
    'doctor.progress.1': 'फोटो जांच रहे हैं…',
    'doctor.progress.2': 'पत्ती के लक्षण पहचान रहे हैं…',
    'doctor.progress.3': 'उपाय तैयार कर रहे हैं…',
    'doctor.progress.4': 'थोड़ा और समय लग रहा है, कृपया रुकें…',
    'doctor.cancel': 'जांच रोकें',
    'doctor.need.crop': 'पहले फसल चुनें',
    'doctor.need.photo': 'विश्लेषण के लिए फोटो लें या गैलरी से चुनें',
    'doctor.offline': 'जांच के लिए इंटरनेट चाहिए। फोटो अभी ले लें, इंटरनेट आते ही "विश्लेषण करें" दबाएं।',
    'doctor.offlineShort': 'इंटरनेट आने पर विश्लेषण कर पाएंगे',
    'doctor.done': 'फसल की जांच पूरी हो गई',
    'doctor.doneAction': 'रिजल्ट देखें',
    'doctor.failedAway': 'फसल की जांच नहीं हो पाई।',
    'doctor.error.title': 'जांच नहीं हो पाई',

    'doctor.tips.title': 'अच्छी फोटो कैसे लें',
    'doctor.tips.close': 'एक ही पत्ती या हिस्सा पास से लें, ताकि वह पूरे फ्रेम में दिखे।',
    'doctor.tips.light': 'दिन की रोशनी में फोटो लें। तेज़ धूप की चमक और गहरी छाया से बचें।',
    'doctor.tips.focus': 'फ़ोन स्थिर रखें और फोकस होने दें। धुंधली फोटो से गलत जांच हो सकती है।',
    'doctor.tips.both': 'बीमार हिस्सा और उसके पास का हरा हिस्सा, दोनों दिखें।',

    'doctor.examples.title': 'उदाहरण देखें',
    'doctor.examples.subtitle': 'ऐसी फोटो से जांच सबसे अच्छी होती है',
    'doctor.example.rust': 'रतुआ',
    'doctor.example.blight': 'झुलसा',
    'doctor.example.yellowing': 'पीलापन',
    'doctor.example.healthy': 'स्वस्थ',
    'doctor.example.open': 'उदाहरण फोटो देखें: {name}',
    'doctor.example.sheetTitle': 'उदाहरण: {name}',
    'doctor.example.sheetDesc': 'यह फोटो लेने का सही तरीका दिखाता है, बीमारी की पहचान नहीं।',
    'doctor.example.rust.1': 'पत्ती की ऊपरी सतह सीधे कैमरे के सामने रखें।',
    'doctor.example.rust.2': 'पाउडर वाले धब्बे या धारियां साफ़ दिखें। ज़ूम करने की जगह फ़ोन पास ले जाएं।',
    'doctor.example.blight.1': 'धब्बे का किनारा और उसके आसपास का हरा हिस्सा फ्रेम में रखें।',
    'doctor.example.blight.2': 'तने या फल पर भी धब्बे हों तो उनकी अलग फोटो लेकर दोबारा जांचें।',
    'doctor.example.yellowing.1': 'पूरी पत्ती दिखाएं, ताकि पता चले पीलापन किनारे से है या नसों के बीच।',
    'doctor.example.yellowing.2': 'नोट में लिखें कि पीलापन नई पत्तियों में है या पुरानी में।',
    'doctor.example.healthy.1': 'स्वस्थ पत्ती ऐसी दिखती है: एक जैसा हरा रंग, कोई धब्बा या छेद नहीं।',
    'doctor.example.healthy.2': 'शक हो तो बीमार और स्वस्थ पत्ती की अलग-अलग फोटो लेकर मिलान करें।',
    'doctor.example.always': 'हर फोटो में ध्यान रखें',
    'doctor.example.always.1': 'पीछे सादी जगह हो। चाहें तो पत्ती के पीछे हथेली या कागज़ रखें।',
    'doctor.example.always.2': 'एक फोटो में एक ही पत्ती या हिस्सा।',
    'doctor.example.always.3': 'उंगली या परछाई धब्बों पर न पड़े।',
    'doctor.example.list': 'उदाहरण फोटो',

    'doctor.recent': 'पिछली जांच',

    // ---- Result ----
    'doctor.result.title': 'रिजल्ट',
    'doctor.result.subtitle': 'AI आधारित प्रारंभिक विश्लेषण',
    'doctor.result.notFound': 'यह जांच नहीं मिली',
    'doctor.result.notFoundBody': 'हो सकता है यह हटा दी गई हो। नई फोटो से दोबारा जांच करें।',
    'doctor.result.newCheck': 'नई जांच करें',
    'doctor.result.confidence': '{n}% निश्चितता',
    'doctor.result.estimate': 'AI का अनुमान, पक्की जांच नहीं',
    'doctor.result.checkedOn': 'जांच: {date}',
    'doctor.result.photoAlt': '{crop} की जांच की गई फोटो',
    'doctor.result.healthyTitle': 'फसल स्वस्थ दिख रही है',
    'doctor.result.healthyBody': 'इस फोटो में कोई बीमारी या कीट साफ़ नहीं दिखा। खेत की नियमित जांच करते रहें।',
    'doctor.result.unusableTitle': 'इस फोटो से जांच नहीं हो सकी',
    'doctor.result.unusableHelp': 'साफ़ फोटो दोबारा लें: पत्ती पास से, दिन की रोशनी में।',
    'doctor.result.retake': 'दोबारा फोटो लें',
    'doctor.result.notice': 'ज़रूरी सूचना',
    'doctor.result.lowConfidence':
      'AI को इस फोटो से पक्का अंदाज़ा नहीं है। पास से, साफ़ रोशनी में दूसरी फोटो लेकर दोबारा जांचें, और ज़रूरत हो तो नज़दीकी कृषि विज्ञान केंद्र (KVK) में पौधा दिखाएं।',
    'doctor.result.symptoms': 'लक्षण',
    'doctor.result.seen': 'फोटो में क्या दिखा',
    'doctor.result.causes': 'संभावित कारण',
    'doctor.result.immediate': 'तुरंत क्या करें',
    'doctor.result.organic': 'जैविक उपाय',
    'doctor.result.chemical': 'रासायनिक उपाय',
    'doctor.result.prevention': 'रोकथाम',
    'doctor.result.chemSafety':
      'लेबल पर लिखी मात्रा ही डालें। छिड़काव के समय मास्क, दस्ताने और पूरे कपड़े पहनें, हवा की उल्टी दिशा में न छिड़कें। दवा लेने से पहले कृषि विशेषज्ञ से अपनी फसल के लिए पुष्टि करें।',
    'doctor.result.noChemical': 'AI ने कोई रासायनिक दवा नहीं सुझाई। ज़रूरत लगे तो कृषि विज्ञान केंद्र (KVK) से पूछें।',
    'doctor.result.more': 'विस्तृत सुझाव देखें',
    'doctor.result.less': 'कम सुझाव दिखाएं',
    'doctor.result.unsaved': 'सेव से हटा दिया',
    'doctor.result.actions': 'रिजल्ट के काम',
    'doctor.result.askHeading': 'और सवाल हैं?',
    'doctor.result.askTitle': 'AI से और पूछें',
    'doctor.result.askBody': 'इस समस्या पर अपने सवाल पूछें, जैसे दवा कब डालें या कितनी बार।',
    'doctor.result.askPrompt':
      'मेरी {crop} की फसल की फोटो में फसल डॉक्टर ने "{issue}" की संभावना बताई है। {symptoms}इसके बारे में विस्तार से बताइए: अभी क्या करूं, क्या न करूं, और कब दोबारा जांचूं?',
    'doctor.result.askSymptoms': 'दिख रहे लक्षण: {list}। ',
    'doctor.result.recheck': '3 दिन बाद दोबारा जांचें',
    'doctor.result.recheckHint': 'कैलेंडर में {date} की याद जुड़ जाएगी',
    'doctor.result.recheckSet': '{date} को दोबारा जांच की याद जुड़ी है',
    'doctor.result.recheckAdded': '{date} को दोबारा जांच की याद कैलेंडर में जुड़ गई',
    'doctor.result.recheckBadge': 'जुड़ गया',
    'doctor.result.openCalendar': 'कैलेंडर देखें',
    'doctor.result.kbTitle': 'और जानकारी',
    'doctor.result.kbSubtitle': '{name} • किसान मित्र जानकारी कोष',
    'doctor.result.kbDesc': 'सरकारी और कृषि विश्वविद्यालय स्रोतों पर आधारित सामान्य जानकारी',
    'doctor.result.kbReviewed': 'जानकारी जांची गई: {date}',
    'doctor.result.kbHindiOnly': 'यह जानकारी अभी सिर्फ़ हिंदी में है।',
    'doctor.result.kbNote': 'यह सामान्य जानकारी है। अपने इलाके के लिए KVK या कृषि अधिकारी की सलाह सबसे ऊपर है।',
    'doctor.result.kbSourceOpen': 'स्रोत खोलें: {title}',
    'doctor.result.shareTitle': 'फसल डॉक्टर जांच — {crop}',
    'doctor.result.shareIssue': 'समस्या: {issue}',
    'doctor.result.shareFooter': '— किसान मित्र ऐप से',
    'doctor.result.speakConfidence': 'AI का अनुमान: {n} प्रतिशत निश्चितता।',

    // ---- History ----
    'doctor.history.title': 'पिछली जांच',
    'doctor.history.count': '{n} जांच सेव हैं',
    'doctor.history.filter': 'फसल के हिसाब से देखें',
    'doctor.history.all': 'सभी',
    'doctor.history.list': 'फसल जांच की सूची',
    'doctor.history.emptyTitle': 'अभी कोई जांच नहीं हुई',
    'doctor.history.emptyBody': 'फसल की फोटो लें और जानें कि पत्ती पर धब्बे, कीट या पीलापन क्यों है।',
    'doctor.history.emptyAction': 'फसल की जांच करें',
    'doctor.history.delete': 'यह जांच हटाएं',
    'doctor.history.deleteAria': 'जांच हटाएं: {issue}',
    'doctor.history.deleteBody': 'फोटो और रिजल्ट इस फ़ोन से हट जाएंगे।',
    'doctor.history.deleted': 'जांच हटा दी गई',
    'doctor.history.healthy': 'स्वस्थ फसल',
    'doctor.history.unusable': 'फोटो साफ़ नहीं थी',
    'doctor.history.keep': 'आखिरी {n} जांच ही फ़ोन में रखी जाती हैं।',
    'doctor.history.new': 'नई जांच करें',
  },
  en: {
    'doctor.title': 'Crop Doctor',
    'doctor.subtitle': 'Find crop problems from a photo',
    'doctor.historyAction': 'See past checks',
    'doctor.steps': 'Check steps',
    'doctor.step.crop': 'Crop',
    'doctor.step.photo': 'Photo',
    'doctor.step.note': 'Details',
    'doctor.step.n': 'Step {n}',
    'doctor.step.done': 'done',

    'doctor.crop.title': 'Choose crop',
    'doctor.crop.choose': 'Choose crop',
    'doctor.crop.change': 'Change',
    'doctor.crop.changeAria': 'Change crop, selected: {crop}',
    'doctor.crop.mine': 'My crops',
    'doctor.crop.all': 'All crops',
    'doctor.crop.yours': 'Your crop • {stage}',
    'doctor.crop.picked': 'This crop will be checked',
    'doctor.crop.sheetDesc': 'Choose the crop you are photographing',

    'doctor.photo.title': 'Take a photo',
    'doctor.photo.hint': 'Take a close, clear photo of the sick leaf or part',
    'doctor.photo.placeholder': 'Keep the leaf in the middle of the frame',
    'doctor.photo.take': 'Take photo',
    'doctor.photo.gallery': 'Choose from gallery',
    'doctor.photo.retake': 'Take again',
    'doctor.photo.another': 'Choose another',
    'doctor.photo.remove': 'Remove photo',
    'doctor.photo.alt': 'Selected photo of {crop}',
    'doctor.photo.preparing': 'Preparing photo…',

    'doctor.note.title': 'Describe the problem',
    'doctor.note.label': 'What do you see?',
    'doctor.note.placeholder': 'e.g. yellow spots on leaves, spreading for 4–5 days',
    'doctor.note.hint': 'You can also tap the mic and speak. It helps the check.',
    'doctor.note.mic': 'Speak what you see',

    'doctor.analyse': 'Analyse',
    'doctor.progress.1': 'Checking the photo…',
    'doctor.progress.2': 'Looking at leaf symptoms…',
    'doctor.progress.3': 'Preparing remedies…',
    'doctor.progress.4': 'Taking a little longer, please wait…',
    'doctor.cancel': 'Stop check',
    'doctor.need.crop': 'Choose a crop first',
    'doctor.need.photo': 'Take a photo or choose one from the gallery',
    'doctor.offline': 'The check needs internet. Take the photo now and tap "Analyse" when you are online.',
    'doctor.offlineShort': 'You can analyse once you are online',
    'doctor.done': 'Your crop check is complete',
    'doctor.doneAction': 'See result',
    'doctor.failedAway': 'The crop check failed.',
    'doctor.error.title': 'Could not check',

    'doctor.tips.title': 'How to take a good photo',
    'doctor.tips.close': 'Take one leaf or part from close up, so it fills the frame.',
    'doctor.tips.light': 'Use daylight. Avoid harsh glare and deep shade.',
    'doctor.tips.focus': 'Hold the phone still and let it focus. A blurry photo can give a wrong result.',
    'doctor.tips.both': 'Show the sick part and the green part next to it.',

    'doctor.examples.title': 'See examples',
    'doctor.examples.subtitle': 'Photos like these give the best results',
    'doctor.example.rust': 'Rust',
    'doctor.example.blight': 'Blight',
    'doctor.example.yellowing': 'Yellowing',
    'doctor.example.healthy': 'Healthy',
    'doctor.example.open': 'See example photo: {name}',
    'doctor.example.sheetTitle': 'Example: {name}',
    'doctor.example.sheetDesc': 'This shows how to frame the photo, not how to diagnose.',
    'doctor.example.rust.1': 'Hold the upper side of the leaf straight towards the camera.',
    'doctor.example.rust.2': 'Make the powdery spots or stripes clear. Move the phone closer instead of zooming.',
    'doctor.example.blight.1': 'Keep the edge of the spot and the green area around it in the frame.',
    'doctor.example.blight.2': 'If the stem or fruit also has spots, check again with a separate photo.',
    'doctor.example.yellowing.1': 'Show the whole leaf, so it is clear whether yellowing starts at the edge or between veins.',
    'doctor.example.yellowing.2': 'Write in the note whether new or old leaves are yellow.',
    'doctor.example.healthy.1': 'A healthy leaf looks like this: even green, no spots or holes.',
    'doctor.example.healthy.2': 'If unsure, compare separate photos of a sick and a healthy leaf.',
    'doctor.example.always': 'In every photo',
    'doctor.example.always.1': 'Use a plain background. You can hold your palm or paper behind the leaf.',
    'doctor.example.always.2': 'One leaf or part per photo.',
    'doctor.example.always.3': 'Keep fingers and shadows off the spots.',
    'doctor.example.list': 'Example photos',

    'doctor.recent': 'Past checks',

    'doctor.result.title': 'Result',
    'doctor.result.subtitle': 'Preliminary AI-based analysis',
    'doctor.result.notFound': 'This check was not found',
    'doctor.result.notFoundBody': 'It may have been deleted. Check again with a new photo.',
    'doctor.result.newCheck': 'New check',
    'doctor.result.confidence': '{n}% confidence',
    'doctor.result.estimate': 'AI estimate, not a lab test',
    'doctor.result.checkedOn': 'Checked: {date}',
    'doctor.result.photoAlt': 'Checked photo of {crop}',
    'doctor.result.healthyTitle': 'The crop looks healthy',
    'doctor.result.healthyBody': 'No disease or pest was clearly visible in this photo. Keep checking the field regularly.',
    'doctor.result.unusableTitle': 'This photo could not be checked',
    'doctor.result.unusableHelp': 'Take a clear photo again: leaf close up, in daylight.',
    'doctor.result.retake': 'Take photo again',
    'doctor.result.notice': 'Important',
    'doctor.result.lowConfidence':
      'The AI is not sure from this photo. Take another close photo in good light and check again, and if needed show the plant at your nearest Krishi Vigyan Kendra (KVK).',
    'doctor.result.symptoms': 'Symptoms',
    'doctor.result.seen': 'Seen in the photo',
    'doctor.result.causes': 'Possible causes',
    'doctor.result.immediate': 'What to do now',
    'doctor.result.organic': 'Organic options',
    'doctor.result.chemical': 'Chemical options',
    'doctor.result.prevention': 'Prevention',
    'doctor.result.chemSafety':
      'Use only the dose on the label. Wear a mask, gloves and full clothes while spraying, and never spray against the wind. Confirm with an agriculture expert for your crop before buying.',
    'doctor.result.noChemical': 'The AI did not suggest a chemical. Ask your Krishi Vigyan Kendra (KVK) if needed.',
    'doctor.result.more': 'See detailed advice',
    'doctor.result.less': 'Show less',
    'doctor.result.unsaved': 'Removed from saved',
    'doctor.result.actions': 'Result actions',
    'doctor.result.askHeading': 'More questions?',
    'doctor.result.askTitle': 'Ask AI more',
    'doctor.result.askBody': 'Ask your questions about this problem, like when or how often to spray.',
    'doctor.result.askPrompt':
      'Crop Doctor found a likely "{issue}" in a photo of my {crop} crop. {symptoms}Please explain in detail: what should I do now, what should I avoid, and when should I check again?',
    'doctor.result.askSymptoms': 'Visible symptoms: {list}. ',
    'doctor.result.recheck': 'Check again in 3 days',
    'doctor.result.recheckHint': 'Adds a reminder for {date} to your calendar',
    'doctor.result.recheckSet': 'Re-check reminder set for {date}',
    'doctor.result.recheckAdded': 'Re-check on {date} added to your calendar',
    'doctor.result.recheckBadge': 'Added',
    'doctor.result.openCalendar': 'Open calendar',
    'doctor.result.kbTitle': 'More information',
    'doctor.result.kbSubtitle': '{name} • Kisan Mitra knowledge base',
    'doctor.result.kbDesc': 'General information based on government and agricultural university sources',
    'doctor.result.kbReviewed': 'Information checked: {date}',
    'doctor.result.kbHindiOnly': 'These details are available in Hindi only.',
    'doctor.result.kbNote': 'This is general information. Your KVK or agriculture officer\'s advice for your area comes first.',
    'doctor.result.kbSourceOpen': 'Open source: {title}',
    'doctor.result.shareTitle': 'Crop Doctor check — {crop}',
    'doctor.result.shareIssue': 'Problem: {issue}',
    'doctor.result.shareFooter': '— from the Kisan Mitra app',
    'doctor.result.speakConfidence': 'AI estimate: {n} percent confidence.',

    'doctor.history.title': 'Past checks',
    'doctor.history.count': '{n} checks saved',
    'doctor.history.filter': 'Filter by crop',
    'doctor.history.all': 'All',
    'doctor.history.list': 'List of crop checks',
    'doctor.history.emptyTitle': 'No checks yet',
    'doctor.history.emptyBody': 'Take a photo of your crop to learn why leaves have spots, pests or yellowing.',
    'doctor.history.emptyAction': 'Check my crop',
    'doctor.history.delete': 'Delete this check',
    'doctor.history.deleteAria': 'Delete check: {issue}',
    'doctor.history.deleteBody': 'The photo and result will be removed from this phone.',
    'doctor.history.deleted': 'Check deleted',
    'doctor.history.healthy': 'Healthy crop',
    'doctor.history.unusable': 'Photo was not clear',
    'doctor.history.keep': 'Only the last {n} checks are kept on the phone.',
    'doctor.history.new': 'New check',
  },
});
