// Strings for the Kheti tab hub and the farming-technique screens (prefix "kheti.").
import { registerStrings } from '../../lib/i18n';
import '../../lib/common-strings';

registerStrings({
  hi: {
    // Hub
    'kheti.title': 'खेती',
    'kheti.subtitle': 'आपकी खेती के सारे औज़ार',
    'kheti.section.myFarming': 'मेरी खेती',
    'kheti.section.tools': 'हिसाब और औज़ार',
    'kheti.section.info': 'जानकारी',
    'kheti.section.community': 'समुदाय',
    'kheti.tile.crops': 'मेरी फसलें',
    'kheti.tile.calendar': 'खेती कैलेंडर',
    'kheti.tile.doctor': 'फसल डॉक्टर',
    'kheti.tile.soil': 'मिट्टी जांच',
    'kheti.tile.hisab': 'खेती हिसाब',
    'kheti.tile.hisabDesc': 'खर्च और कमाई लिखें',
    'kheti.tile.calculators': 'कैलकुलेटर',
    'kheti.tile.calculatorsDesc': 'खाद, बीज और सिंचाई का हिसाब',
    'kheti.tile.techniques': 'खेती तकनीक',
    'kheti.tile.schemes': 'सरकारी योजनाएं',
    'kheti.tile.saved': 'सेव की गई जानकारी',
    'kheti.tile.community': 'किसान समुदाय',
    'kheti.tile.communityDesc': 'दूसरे किसानों से पूछें',
    'kheti.tile.experts': 'विशेषज्ञ से पूछें',
    'kheti.tile.expertsDesc': 'कृषि विशेषज्ञ की सलाह',
    'kheti.tile.soon': 'जल्द आ रहा है',
    'kheti.today.count': 'आज {n} काम करने हैं',
    'kheti.today.one': 'आज 1 काम करना है',
    'kheti.today.none': 'आज कोई काम नहीं है',
    'kheti.today.overdue': '{n} काम पिछले दिनों से बाकी हैं',
    'kheti.today.overdueOne': '1 काम पिछले दिनों से बाकी है',
    'kheti.today.next': 'अगला काम: {title} ({when})',
    'kheti.today.allClear': 'सारे काम समय पर हैं। पूरा कैलेंडर देखें।',
    'kheti.today.noCrops': 'खेती कैलेंडर',
    'kheti.today.noCropsBody': 'फसल जोड़ें — बुवाई से कटाई तक के काम अपने आप कैलेंडर में आ जाएंगे।',
    'kheti.today.more': 'और {n} काम',
    'kheti.today.moreOne': 'और 1 काम',
    'kheti.season.title': 'इस मौसम की फसलें',
    'kheti.season.subtitle': '{season} — फसल चुनें और अपनी सूची में जोड़ें',
    'kheti.season.add': '{crop} जोड़ें',
    'kheti.season.list': 'इस मौसम की फसलें, जोड़ने के लिए चुनें',
    'kheti.featured.title': 'आज की तकनीक',

    // Techniques list
    'kheti.tech.title': 'खेती तकनीक',
    'kheti.tech.subtitle': 'आसान और नई तकनीकें सीखें',
    'kheti.tech.filter': 'तकनीक का प्रकार',
    'kheti.tech.all': 'सभी',
    'kheti.tech.search': 'तकनीक खोजें, जैसे: ड्रिप, जैविक',
    'kheti.tech.count': '{n} तकनीकें',
    'kheti.tech.countOne': '1 तकनीक',
    'kheti.tech.emptyTitle': 'कोई तकनीक नहीं मिली',
    'kheti.tech.emptyBody': 'दूसरे शब्द से खोजें या सभी तकनीकें देखें।',
    'kheti.tech.showAll': 'सभी तकनीकें देखें',
    'kheti.tech.list': 'खेती की तकनीकें',

    // Technique details
    'kheti.tech.whatIs': 'यह क्या है',
    'kheti.tech.benefits': 'फायदे',
    'kheti.tech.steps': 'कैसे करें',
    'kheti.tech.cost': 'लागत',
    'kheti.tech.costNote': 'लागत अनुमानित है — आज के दाम स्थानीय दुकान या कृषि विभाग से पूछ लें।',
    'kheti.tech.cautions': 'सावधानियां',
    'kheti.tech.crops': 'किन फसलों में उपयोगी',
    'kheti.tech.allCrops': 'सभी फसलों में उपयोगी',
    'kheti.tech.scheme': 'सरकारी मदद',
    'kheti.tech.schemeOpen': '{name} देखें',
    'kheti.tech.schemesOpen': 'सरकारी योजनाएं देखें',
    'kheti.tech.sources': 'जानकारी के स्रोत',
    'kheti.tech.reviewed': 'अंतिम समीक्षा: {date}',
    'kheti.tech.localNote': 'यह सामान्य जानकारी है। अपने इलाके के हिसाब से सही तरीका नज़दीकी कृषि विज्ञान केंद्र (KVK) या कृषि अधिकारी से ज़रूर पूछें।',
    'kheti.tech.hindiOnly': 'पूरी जानकारी हिंदी में है।',
    'kheti.tech.doseNote': 'दवा और बीज की मात्रा सिर्फ उदाहरण है। हमेशा दवा के लेबल, अपने राज्य की सिफारिश और नज़दीकी KVK या कृषि अधिकारी की सलाह के हिसाब से ही डालें। दवा छूते समय दस्ताने और मास्क पहनें।',
    'kheti.tech.notFoundTitle': 'यह जानकारी नहीं मिली',
    'kheti.tech.notFoundBody': 'हो सकता है यह तकनीक अब उपलब्ध न हो। बाकी तकनीकें देखें।',
    'kheti.tech.isSaved': 'सेव है',
    'kheti.tech.removed': 'सेव से हटा दिया',
    'kheti.tech.stepsSpeech': 'कैसे करें।',
    'kheti.tech.shareFooter': '— किसान मित्र ऐप से',
    'kheti.tech.externalLink': '(बाहरी वेबसाइट खुलेगी)',
    'kheti.tech.actions': 'इस जानकारी पर काम',
  },
  en: {
    'kheti.title': 'Farming',
    'kheti.subtitle': 'All your farming tools',
    'kheti.section.myFarming': 'My farming',
    'kheti.section.tools': 'Accounts and tools',
    'kheti.section.info': 'Information',
    'kheti.section.community': 'Community',
    'kheti.tile.crops': 'My crops',
    'kheti.tile.calendar': 'Crop calendar',
    'kheti.tile.doctor': 'Crop doctor',
    'kheti.tile.soil': 'Soil test',
    'kheti.tile.hisab': 'Farm accounts',
    'kheti.tile.hisabDesc': 'Record costs and income',
    'kheti.tile.calculators': 'Calculators',
    'kheti.tile.calculatorsDesc': 'Fertilizer, seed and irrigation',
    'kheti.tile.techniques': 'Farming techniques',
    'kheti.tile.schemes': 'Government schemes',
    'kheti.tile.saved': 'Saved information',
    'kheti.tile.community': 'Farmer community',
    'kheti.tile.communityDesc': 'Ask other farmers',
    'kheti.tile.experts': 'Ask an expert',
    'kheti.tile.expertsDesc': 'Advice from agri experts',
    'kheti.tile.soon': 'Coming soon',
    'kheti.today.count': '{n} tasks to do today',
    'kheti.today.one': '1 task to do today',
    'kheti.today.none': 'No tasks today',
    'kheti.today.overdue': '{n} tasks pending from earlier days',
    'kheti.today.overdueOne': '1 task pending from an earlier day',
    'kheti.today.next': 'Next task: {title} ({when})',
    'kheti.today.allClear': 'All tasks are on time. See the full calendar.',
    'kheti.today.noCrops': 'Crop calendar',
    'kheti.today.noCropsBody': 'Add a crop — tasks from sowing to harvest appear in the calendar automatically.',
    'kheti.today.more': '{n} more tasks',
    'kheti.today.moreOne': '1 more task',
    'kheti.season.title': 'Crops for this season',
    'kheti.season.subtitle': '{season} — pick a crop to add it to your list',
    'kheti.season.add': 'Add {crop}',
    'kheti.season.list': 'Crops for this season, choose one to add',
    'kheti.featured.title': 'Technique of the day',
    'kheti.tech.title': 'Farming techniques',
    'kheti.tech.subtitle': 'Learn simple, modern methods',
    'kheti.tech.filter': 'Type of technique',
    'kheti.tech.all': 'All',
    'kheti.tech.search': 'Search, e.g. drip, organic',
    'kheti.tech.count': '{n} techniques',
    'kheti.tech.countOne': '1 technique',
    'kheti.tech.emptyTitle': 'No technique found',
    'kheti.tech.emptyBody': 'Try another word or see all techniques.',
    'kheti.tech.showAll': 'See all techniques',
    'kheti.tech.list': 'Farming techniques',
    'kheti.tech.whatIs': 'What it is',
    'kheti.tech.benefits': 'Benefits',
    'kheti.tech.steps': 'How to do it',
    'kheti.tech.cost': 'Cost',
    'kheti.tech.costNote': 'Costs are indicative — check current prices locally or with the agriculture department.',
    'kheti.tech.cautions': 'Precautions',
    'kheti.tech.crops': 'Suitable crops',
    'kheti.tech.allCrops': 'Useful for all crops',
    'kheti.tech.scheme': 'Government support',
    'kheti.tech.schemeOpen': 'See {name}',
    'kheti.tech.schemesOpen': 'See government schemes',
    'kheti.tech.sources': 'Sources',
    'kheti.tech.reviewed': 'Last reviewed: {date}',
    'kheti.tech.localNote': 'This is general information. Ask your nearest Krishi Vigyan Kendra (KVK) or agriculture officer for the right method in your area.',
    'kheti.tech.hindiOnly': 'Detailed steps are available in Hindi.',
    'kheti.tech.doseNote':
      'Chemical and seed doses are examples only. Always follow the product label, the recommendation for your state and your nearest KVK or agriculture officer. Wear gloves and a mask when handling chemicals.',
    'kheti.tech.notFoundTitle': 'Information not found',
    'kheti.tech.notFoundBody': 'This technique may no longer be available. See the other techniques.',
    'kheti.tech.isSaved': 'Saved',
    'kheti.tech.removed': 'Removed from saved',
    'kheti.tech.stepsSpeech': 'How to do it.',
    'kheti.tech.shareFooter': '— from the Kisan Mitra app',
    'kheti.tech.externalLink': '(opens an external website)',
    'kheti.tech.actions': 'Actions for this information',
  },
});
